// Code generated by onlycli; DO NOT EDIT.

package runtime

import (
	"bytes"
	"compress/gzip"
	"crypto/tls"
	"encoding/json"
	"fmt"
	"io"
	"math"
	"net/http"
	"net/url"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/spf13/cobra"
)

type Response struct {
	StatusCode int
	Headers    http.Header
	Body       []byte
}

type Client struct {
	BaseURL    string
	Token      string
	AuthType   string
	Verbose    bool
	PageLimit  int
	DryRun     bool
	MaxRetries int
	HTTPClient *http.Client
}

func NewClientFromConfig(cmd *cobra.Command) *Client {
	var verbose bool
	if cmd != nil {
		if cmd.PersistentFlags().Lookup("verbose") != nil {
			verbose, _ = cmd.PersistentFlags().GetBool("verbose")
		}
	}

	var pageLimit int
	if cmd != nil {
		if cmd.PersistentFlags().Lookup("page-limit") != nil {
			pageLimit, _ = cmd.PersistentFlags().GetInt("page-limit")
		}
	}

	var dryRun bool
	if cmd != nil {
		if cmd.PersistentFlags().Lookup("dry-run") != nil {
			dryRun, _ = cmd.PersistentFlags().GetBool("dry-run")
		}
	}

	var maxRetries int
	if cmd != nil {
		if cmd.PersistentFlags().Lookup("max-retries") != nil {
			maxRetries, _ = cmd.PersistentFlags().GetInt("max-retries")
		}
	}

	profile := ""
	if cmd != nil && cmd.PersistentFlags().Lookup("profile") != nil {
		profile, _ = cmd.PersistentFlags().GetString("profile")
	}

	var baseURL, token, authType string
	if cfg, err := LoadConfig(); err == nil && cfg != nil {
		p := GetProfile(cfg, profile)
		if p != nil {
			baseURL = p.BaseURL
			token = p.Token
			authType = p.AuthType
		}
	}
	if baseURL == "" {
		baseURL = os.Getenv("PETSTORE_BASE_URL")
	}
	if baseURL == "" {
		baseURL = "https://petstore3.swagger.io/api/v3"
	}
	if token == "" {
		token = os.Getenv("PETSTORE_TOKEN")
	}
	if authType == "" {
		authType = "apikey"
	}

	tr := &http.Transport{
		TLSClientConfig:    &tls.Config{MinVersion: tls.VersionTLS12},
		ForceAttemptHTTP2:  true,
		DisableCompression: true,
	}

	return &Client{
		BaseURL:    baseURL,
		Token:      token,
		AuthType:   authType,
		Verbose:    verbose,
		PageLimit:  pageLimit,
		DryRun:     dryRun,
		MaxRetries: maxRetries,
		HTTPClient: &http.Client{Transport: tr},
	}
}

func NewClientFromEnv() *Client {
	return NewClientFromConfig(nil)
}

func (c *Client) Do(method, path string, params map[string]string, body []byte) (*Response, error) {
	if c.PageLimit > 0 && method == "GET" {
		return c.doAllPages(method, path, params, body)
	}
	return c.doSingle(method, path, params, body)
}

func (c *Client) doAllPages(method, path string, params map[string]string, body []byte) (*Response, error) {
	var bodies [][]byte
	var last *Response
	nextURL := ""
	for i := 0; i < c.PageLimit; i++ {
		var resp *Response
		var err error
		if nextURL != "" {
			resp, err = c.doAbsoluteURL(method, nextURL, body)
		} else {
			resp, err = c.doSingle(method, path, params, body)
		}
		if err != nil {
			return nil, err
		}
		last = resp
		bodies = append(bodies, resp.Body)
		nextURL = parseNextLink(resp.Headers.Get("Link"))
		if nextURL == "" {
			break
		}
	}
	if last == nil {
		return nil, fmt.Errorf("no response from pagination")
	}
	merged := mergePaginatedBodies(bodies)
	return &Response{
		StatusCode: last.StatusCode,
		Headers:    last.Headers.Clone(),
		Body:       merged,
	}, nil
}

func mergePaginatedBodies(pages [][]byte) []byte {
	if len(pages) == 0 {
		return nil
	}
	if len(pages) == 1 {
		return pages[0]
	}
	var merged []json.RawMessage
	for _, p := range pages {
		p = bytes.TrimSpace(p)
		if len(p) == 0 {
			continue
		}
		if p[0] != '[' {
			return pages[len(pages)-1]
		}
		var chunk []json.RawMessage
		if err := json.Unmarshal(p, &chunk); err != nil {
			return pages[len(pages)-1]
		}
		merged = append(merged, chunk...)
	}
	out, err := json.Marshal(merged)
	if err != nil {
		return pages[len(pages)-1]
	}
	return out
}

func parseNextLink(linkHeader string) string {
	if linkHeader == "" {
		return ""
	}
	for _, raw := range strings.Split(linkHeader, ",") {
		part := strings.TrimSpace(raw)
		lower := strings.ToLower(part)
		if !strings.Contains(lower, `rel="next"`) && !strings.Contains(lower, `rel='next'`) && !strings.Contains(lower, "rel=next") {
			continue
		}
		start := strings.Index(part, "<")
		end := strings.Index(part, ">")
		if start < 0 || end <= start {
			continue
		}
		return part[start+1 : end]
	}
	return ""
}

func (c *Client) doSingle(method, path string, params map[string]string, body []byte) (*Response, error) {
	u, err := url.Parse(c.BaseURL + path)
	if err != nil {
		return nil, fmt.Errorf("invalid URL: %w", err)
	}
	q := u.Query()
	for k, v := range params {
		q.Set(k, v)
	}
	u.RawQuery = q.Encode()
	return c.doURL(method, u.String(), body)
}

func (c *Client) doAbsoluteURL(method, rawURL string, body []byte) (*Response, error) {
	if _, err := url.Parse(rawURL); err != nil {
		return nil, fmt.Errorf("invalid URL: %w", err)
	}
	return c.doURL(method, rawURL, body)
}

func (c *Client) doURL(method, rawURL string, body []byte) (*Response, error) {
	var bodyReader io.Reader
	if len(body) > 0 {
		bodyReader = bytes.NewReader(body)
	}
	req, err := http.NewRequest(method, rawURL, bodyReader)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}
	c.applyRequestHeaders(req, len(body) > 0)
	if c.DryRun {
		fmt.Fprintf(os.Stdout, "%s %s\n", method, rawURL)
		for k, vv := range req.Header {
			fmt.Fprintf(os.Stdout, "%s: %s\n", k, strings.Join(vv, ", "))
		}
		const maxPreview = 2048
		if len(body) == 0 {
			fmt.Fprintf(os.Stdout, "Body: (empty)\n")
		} else if len(body) > maxPreview {
			fmt.Fprintf(os.Stdout, "Body (%d bytes, preview): %s\n", len(body), string(body[:maxPreview]))
		} else {
			fmt.Fprintf(os.Stdout, "Body: %s\n", string(body))
		}
		fmt.Fprintf(os.Stdout, "dry-run: request not sent\n")
		return &Response{
			StatusCode: 0,
			Headers:    make(http.Header),
			Body:       nil,
		}, nil
	}
	return c.roundTrip(method, rawURL, body)
}

func (c *Client) applyRequestHeaders(req *http.Request, hasBody bool) {
	if c.Token != "" {
		switch strings.ToLower(c.AuthType) {
		case "bearer", "oauth2":
			req.Header.Set("Authorization", "Bearer "+c.Token)
		case "basic":
			req.Header.Set("Authorization", "Basic "+c.Token)
		case "apikey":
			req.Header.Set("Authorization", c.Token)
		}
	}
	if hasBody {
		req.Header.Set("Content-Type", "application/json")
	}
	req.Header.Set("Accept", "application/json")
	req.Header.Set("Accept-Encoding", "gzip, deflate")
	req.Header.Set("User-Agent", "petstore-cli/onlycli")
}

func retryBackoffAfterAttempt(attempt int, retryAfterHeader string) time.Duration {
	h := strings.TrimSpace(retryAfterHeader)
	if h != "" {
		if sec, err := strconv.Atoi(h); err == nil && sec >= 0 {
			return time.Duration(sec) * time.Second
		}
		if t, err := http.ParseTime(h); err == nil {
			d := time.Until(t)
			if d > 0 {
				return d
			}
		}
	}
	exp := int(math.Min(float64(attempt), 30))
	return time.Second * time.Duration(1<<uint(exp))
}

func (c *Client) roundTrip(method, rawURL string, body []byte) (*Response, error) {
	maxAttempts := 1
	if c.MaxRetries > 0 {
		maxAttempts = 1 + c.MaxRetries
	}

	for attempt := 0; attempt < maxAttempts; attempt++ {
		var bodyReader io.Reader
		if len(body) > 0 {
			bodyReader = bytes.NewReader(body)
		}
		req, err := http.NewRequest(method, rawURL, bodyReader)
		if err != nil {
			return nil, fmt.Errorf("failed to create request: %w", err)
		}
		c.applyRequestHeaders(req, len(body) > 0)

		if c.Verbose {
			fmt.Fprintf(os.Stderr, "> %s %s\n", req.Method, req.URL.String())
			for k, vv := range req.Header {
				fmt.Fprintf(os.Stderr, "> %s: %s\n", k, strings.Join(vv, ", "))
			}
		}

		resp, err := c.HTTPClient.Do(req)
		if err != nil {
			return nil, fmt.Errorf("request failed: %w", err)
		}

		if c.Verbose {
			fmt.Fprintf(os.Stderr, "< %s\n", resp.Status)
			for k, vv := range resp.Header {
				fmt.Fprintf(os.Stderr, "< %s: %s\n", k, strings.Join(vv, ", "))
			}
		}

		shouldRetry := resp.StatusCode == 429 || resp.StatusCode >= 500
		if !shouldRetry || attempt == maxAttempts-1 {
			return c.readResponse(resp)
		}

		io.Copy(io.Discard, resp.Body)
		resp.Body.Close()
		wait := retryBackoffAfterAttempt(attempt, resp.Header.Get("Retry-After"))
		time.Sleep(wait)
	}

	return nil, fmt.Errorf("internal error: roundTrip exited without response")
}

func (c *Client) readResponse(resp *http.Response) (*Response, error) {
	defer resp.Body.Close()

	var reader io.Reader = resp.Body
	for _, encPart := range strings.Split(resp.Header.Get("Content-Encoding"), ",") {
		encPart = strings.TrimSpace(strings.ToLower(encPart))
		if encPart == "gzip" {
			gz, err := gzip.NewReader(resp.Body)
			if err != nil {
				return nil, fmt.Errorf("gzip decompress: %w", err)
			}
			defer gz.Close()
			reader = gz
			break
		}
	}

	raw, err := io.ReadAll(reader)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	return &Response{
		StatusCode: resp.StatusCode,
		Headers:    resp.Header.Clone(),
		Body:       raw,
	}, nil
}
