// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsUpdateOrgVariableCmd = &cobra.Command{
	Use:   "update-org-variable",
	Short: "Update an organization variable",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/actions/variables/{name}"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		nameVal, _ := cmd.Flags().GetString("name")
		if nameVal == "" {
			return fmt.Errorf("required flag --%s not set", "name")
		}
		path = strings.Replace(path, "{name}", nameVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "value", JSONPath: "value", Type: "string"},
			{FlagName: "visibility", JSONPath: "visibility", Type: "string"},
			{FlagName: "selected-repository-ids", JSONPath: "selected_repository_ids", Type: "array"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PATCH", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsUpdateOrgVariableCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = actionsUpdateOrgVariableCmd.MarkFlagRequired("org")
	actionsUpdateOrgVariableCmd.Flags().String("name", "", "The name of the variable.")
	_ = actionsUpdateOrgVariableCmd.MarkFlagRequired("name")
	actionsUpdateOrgVariableCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	actionsUpdateOrgVariableCmd.Flags().String("value", "", "The value of the variable.")
	actionsUpdateOrgVariableCmd.Flags().String("visibility", "", "The type of repositories in the organization that can access the variable. `selected` means only the repositories specified by `selected_repository_ids` can access the variable.")
	_ = actionsUpdateOrgVariableCmd.RegisterFlagCompletionFunc("visibility", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"all", "private", "selected"}, cobra.ShellCompDirectiveNoFileComp
	})
	actionsUpdateOrgVariableCmd.Flags().String("selected-repository-ids", "", "An array of repository ids that can access the organization variable. You can only provide a list of repository ids when the `visibility` is set to `selected`.")
}
