// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsGetReviewsForRunCmd = &cobra.Command{
	Use:   "get-reviews-for-run",
	Short: "Get the review history for a workflow run",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/actions/runs/{run_id}/approvals"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		runIdVal, _ := cmd.Flags().GetString("run-id")
		if runIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "run-id")
		}
		path = strings.Replace(path, "{run_id}", runIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsGetReviewsForRunCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = actionsGetReviewsForRunCmd.MarkFlagRequired("owner")
	actionsGetReviewsForRunCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = actionsGetReviewsForRunCmd.MarkFlagRequired("repo")
	actionsGetReviewsForRunCmd.Flags().String("run-id", "", "The unique identifier of the workflow run.")
	_ = actionsGetReviewsForRunCmd.MarkFlagRequired("run-id")
}
