// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsAddCustomLabelsToSelfHostedRunnerForRepoCmd = &cobra.Command{
	Use:   "add-custom-labels-to-self-hosted-runner-for-repo",
	Short: "Add custom labels to a self-hosted runner for a repository",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/actions/runners/{runner_id}/labels"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		runnerIdVal, _ := cmd.Flags().GetString("runner-id")
		if runnerIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "runner-id")
		}
		path = strings.Replace(path, "{runner_id}", runnerIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "labels", JSONPath: "labels", Type: "array"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsAddCustomLabelsToSelfHostedRunnerForRepoCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = actionsAddCustomLabelsToSelfHostedRunnerForRepoCmd.MarkFlagRequired("owner")
	actionsAddCustomLabelsToSelfHostedRunnerForRepoCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = actionsAddCustomLabelsToSelfHostedRunnerForRepoCmd.MarkFlagRequired("repo")
	actionsAddCustomLabelsToSelfHostedRunnerForRepoCmd.Flags().String("runner-id", "", "Unique identifier of the self-hosted runner.")
	_ = actionsAddCustomLabelsToSelfHostedRunnerForRepoCmd.MarkFlagRequired("runner-id")
	actionsAddCustomLabelsToSelfHostedRunnerForRepoCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	actionsAddCustomLabelsToSelfHostedRunnerForRepoCmd.Flags().String("labels", "", "The names of the custom labels to add to the runner.")
	_ = actionsAddCustomLabelsToSelfHostedRunnerForRepoCmd.MarkFlagRequired("labels")
}
