// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsReviewCustomGatesForRunCmd = &cobra.Command{
	Use:   "review-custom-gates-for-run",
	Short: "Review custom deployment protection rules for a workflow run",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/actions/runs/{run_id}/deployment_protection_rule"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		runIdVal, _ := cmd.Flags().GetString("run-id")
		if runIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "run-id")
		}
		path = strings.Replace(path, "{run_id}", runIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsReviewCustomGatesForRunCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = actionsReviewCustomGatesForRunCmd.MarkFlagRequired("owner")
	actionsReviewCustomGatesForRunCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = actionsReviewCustomGatesForRunCmd.MarkFlagRequired("repo")
	actionsReviewCustomGatesForRunCmd.Flags().String("run-id", "", "The unique identifier of the workflow run.")
	_ = actionsReviewCustomGatesForRunCmd.MarkFlagRequired("run-id")
	actionsReviewCustomGatesForRunCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
}
