// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsGetHostedRunnerForOrgCmd = &cobra.Command{
	Use:   "get-hosted-runner-for-org",
	Short: "Get a GitHub-hosted runner for an organization",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/actions/hosted-runners/{hosted_runner_id}"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		hostedRunnerIdVal, _ := cmd.Flags().GetString("hosted-runner-id")
		if hostedRunnerIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "hosted-runner-id")
		}
		path = strings.Replace(path, "{hosted_runner_id}", hostedRunnerIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsGetHostedRunnerForOrgCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = actionsGetHostedRunnerForOrgCmd.MarkFlagRequired("org")
	actionsGetHostedRunnerForOrgCmd.Flags().String("hosted-runner-id", "", "Unique identifier of the GitHub-hosted runner.")
	_ = actionsGetHostedRunnerForOrgCmd.MarkFlagRequired("hosted-runner-id")
}
