// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsAddRepoAccessToSelfHostedRunnerGroupInOrgCmd = &cobra.Command{
	Use:   "add-repo-access-to-self-hosted-runner-group-in-org",
	Short: "Add repository access to a self-hosted runner group in an organization",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/actions/runner-groups/{runner_group_id}/repositories/{repository_id}"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		runnerGroupIdVal, _ := cmd.Flags().GetString("runner-group-id")
		if runnerGroupIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "runner-group-id")
		}
		path = strings.Replace(path, "{runner_group_id}", runnerGroupIdVal, 1)
		repositoryIdVal, _ := cmd.Flags().GetString("repository-id")
		if repositoryIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "repository-id")
		}
		path = strings.Replace(path, "{repository_id}", repositoryIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("PUT", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsAddRepoAccessToSelfHostedRunnerGroupInOrgCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = actionsAddRepoAccessToSelfHostedRunnerGroupInOrgCmd.MarkFlagRequired("org")
	actionsAddRepoAccessToSelfHostedRunnerGroupInOrgCmd.Flags().String("runner-group-id", "", "Unique identifier of the self-hosted runner group.")
	_ = actionsAddRepoAccessToSelfHostedRunnerGroupInOrgCmd.MarkFlagRequired("runner-group-id")
	actionsAddRepoAccessToSelfHostedRunnerGroupInOrgCmd.Flags().String("repository-id", "", "The unique identifier of the repository.")
	_ = actionsAddRepoAccessToSelfHostedRunnerGroupInOrgCmd.MarkFlagRequired("repository-id")
}
