// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var activityListNotificationsForAuthenticatedUserCmd = &cobra.Command{
	Use:   "list-notifications-for-authenticated-user",
	Short: "List notifications for the authenticated user",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/notifications"

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("all"); v != "" {
			params["all"] = v
		}
		if v, _ := cmd.Flags().GetString("participating"); v != "" {
			params["participating"] = v
		}
		if v, _ := cmd.Flags().GetString("since"); v != "" {
			params["since"] = v
		}
		if v, _ := cmd.Flags().GetString("before"); v != "" {
			params["before"] = v
		}
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		if v, _ := cmd.Flags().GetString("per-page"); v != "" {
			params["per_page"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	activityListNotificationsForAuthenticatedUserCmd.Flags().String("all", "false", "If `true`, show notifications marked as read.")
	activityListNotificationsForAuthenticatedUserCmd.Flags().String("participating", "false", "If `true`, only shows notifications in which the user is directly participating or mentioned.")
	activityListNotificationsForAuthenticatedUserCmd.Flags().String("since", "", "Only show results that were last updated after the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.")
	activityListNotificationsForAuthenticatedUserCmd.Flags().String("before", "", "Only show notifications updated before the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.")
	activityListNotificationsForAuthenticatedUserCmd.Flags().String("page", "1", "The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	activityListNotificationsForAuthenticatedUserCmd.Flags().String("per-page", "50", "The number of results per page (max 50). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
}
