// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsGetForkPrContributorApprovalPermissionsOrganizationCmd = &cobra.Command{
	Use:   "get-fork-pr-contributor-approval-permissions-organization",
	Short: "Get fork PR contributor approval permissions for an organization",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/actions/permissions/fork-pr-contributor-approval"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsGetForkPrContributorApprovalPermissionsOrganizationCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = actionsGetForkPrContributorApprovalPermissionsOrganizationCmd.MarkFlagRequired("org")
}
