// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsGetActionsCacheRetentionLimitForEnterpriseCmd = &cobra.Command{
	Use:   "get-actions-cache-retention-limit-for-enterprise",
	Short: "Get GitHub Actions cache retention limit for an enterprise",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/enterprises/{enterprise}/actions/cache/retention-limit"
		enterpriseVal, _ := cmd.Flags().GetString("enterprise")
		if enterpriseVal == "" {
			return fmt.Errorf("required flag --%s not set", "enterprise")
		}
		path = strings.Replace(path, "{enterprise}", enterpriseVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsGetActionsCacheRetentionLimitForEnterpriseCmd.Flags().String("enterprise", "", "The slug version of the enterprise name.")
	_ = actionsGetActionsCacheRetentionLimitForEnterpriseCmd.MarkFlagRequired("enterprise")
}
