// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsSetSelectedRepositoriesEnabledGithubActionsOrganizationCmd = &cobra.Command{
	Use:   "set-selected-repositories-enabled-github-actions-organization",
	Short: "Set selected repositories enabled for GitHub Actions in an organization",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/actions/permissions/repositories"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "selected-repository-ids", JSONPath: "selected_repository_ids", Type: "array"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsSetSelectedRepositoriesEnabledGithubActionsOrganizationCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = actionsSetSelectedRepositoriesEnabledGithubActionsOrganizationCmd.MarkFlagRequired("org")
	actionsSetSelectedRepositoriesEnabledGithubActionsOrganizationCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	actionsSetSelectedRepositoriesEnabledGithubActionsOrganizationCmd.Flags().String("selected-repository-ids", "", "List of repository IDs to enable for GitHub Actions.")
	_ = actionsSetSelectedRepositoriesEnabledGithubActionsOrganizationCmd.MarkFlagRequired("selected-repository-ids")
}
