// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsRemoveCustomLabelFromSelfHostedRunnerForRepoCmd = &cobra.Command{
	Use:   "remove-custom-label-from-self-hosted-runner-for-repo",
	Short: "Remove a custom label from a self-hosted runner for a repository",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/actions/runners/{runner_id}/labels/{name}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		runnerIdVal, _ := cmd.Flags().GetString("runner-id")
		if runnerIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "runner-id")
		}
		path = strings.Replace(path, "{runner_id}", runnerIdVal, 1)
		nameVal, _ := cmd.Flags().GetString("name")
		if nameVal == "" {
			return fmt.Errorf("required flag --%s not set", "name")
		}
		path = strings.Replace(path, "{name}", nameVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsRemoveCustomLabelFromSelfHostedRunnerForRepoCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = actionsRemoveCustomLabelFromSelfHostedRunnerForRepoCmd.MarkFlagRequired("owner")
	actionsRemoveCustomLabelFromSelfHostedRunnerForRepoCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = actionsRemoveCustomLabelFromSelfHostedRunnerForRepoCmd.MarkFlagRequired("repo")
	actionsRemoveCustomLabelFromSelfHostedRunnerForRepoCmd.Flags().String("runner-id", "", "Unique identifier of the self-hosted runner.")
	_ = actionsRemoveCustomLabelFromSelfHostedRunnerForRepoCmd.MarkFlagRequired("runner-id")
	actionsRemoveCustomLabelFromSelfHostedRunnerForRepoCmd.Flags().String("name", "", "The name of a self-hosted runner's custom label.")
	_ = actionsRemoveCustomLabelFromSelfHostedRunnerForRepoCmd.MarkFlagRequired("name")
}
