// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsRemoveSelfHostedRunnerFromGroupForOrgCmd = &cobra.Command{
	Use:   "remove-self-hosted-runner-from-group-for-org",
	Short: "Remove a self-hosted runner from a group for an organization",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/actions/runner-groups/{runner_group_id}/runners/{runner_id}"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		runnerGroupIdVal, _ := cmd.Flags().GetString("runner-group-id")
		if runnerGroupIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "runner-group-id")
		}
		path = strings.Replace(path, "{runner_group_id}", runnerGroupIdVal, 1)
		runnerIdVal, _ := cmd.Flags().GetString("runner-id")
		if runnerIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "runner-id")
		}
		path = strings.Replace(path, "{runner_id}", runnerIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsRemoveSelfHostedRunnerFromGroupForOrgCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = actionsRemoveSelfHostedRunnerFromGroupForOrgCmd.MarkFlagRequired("org")
	actionsRemoveSelfHostedRunnerFromGroupForOrgCmd.Flags().String("runner-group-id", "", "Unique identifier of the self-hosted runner group.")
	_ = actionsRemoveSelfHostedRunnerFromGroupForOrgCmd.MarkFlagRequired("runner-group-id")
	actionsRemoveSelfHostedRunnerFromGroupForOrgCmd.Flags().String("runner-id", "", "Unique identifier of the self-hosted runner.")
	_ = actionsRemoveSelfHostedRunnerFromGroupForOrgCmd.MarkFlagRequired("runner-id")
}
