// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsDownloadWorkflowRunAttemptLogsCmd = &cobra.Command{
	Use:   "download-workflow-run-attempt-logs",
	Short: "Download workflow run attempt logs",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/actions/runs/{run_id}/attempts/{attempt_number}/logs"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		runIdVal, _ := cmd.Flags().GetString("run-id")
		if runIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "run-id")
		}
		path = strings.Replace(path, "{run_id}", runIdVal, 1)
		attemptNumberVal, _ := cmd.Flags().GetString("attempt-number")
		if attemptNumberVal == "" {
			return fmt.Errorf("required flag --%s not set", "attempt-number")
		}
		path = strings.Replace(path, "{attempt_number}", attemptNumberVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsDownloadWorkflowRunAttemptLogsCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = actionsDownloadWorkflowRunAttemptLogsCmd.MarkFlagRequired("owner")
	actionsDownloadWorkflowRunAttemptLogsCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = actionsDownloadWorkflowRunAttemptLogsCmd.MarkFlagRequired("repo")
	actionsDownloadWorkflowRunAttemptLogsCmd.Flags().String("run-id", "", "The unique identifier of the workflow run.")
	_ = actionsDownloadWorkflowRunAttemptLogsCmd.MarkFlagRequired("run-id")
	actionsDownloadWorkflowRunAttemptLogsCmd.Flags().String("attempt-number", "", "The attempt number of the workflow run.")
	_ = actionsDownloadWorkflowRunAttemptLogsCmd.MarkFlagRequired("attempt-number")
}
