// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsSetSelectedReposForOrgVariableCmd = &cobra.Command{
	Use:   "set-selected-repos-for-org-variable",
	Short: "Set selected repositories for an organization variable",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/actions/variables/{name}/repositories"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		nameVal, _ := cmd.Flags().GetString("name")
		if nameVal == "" {
			return fmt.Errorf("required flag --%s not set", "name")
		}
		path = strings.Replace(path, "{name}", nameVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "selected-repository-ids", JSONPath: "selected_repository_ids", Type: "array"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsSetSelectedReposForOrgVariableCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = actionsSetSelectedReposForOrgVariableCmd.MarkFlagRequired("org")
	actionsSetSelectedReposForOrgVariableCmd.Flags().String("name", "", "The name of the variable.")
	_ = actionsSetSelectedReposForOrgVariableCmd.MarkFlagRequired("name")
	actionsSetSelectedReposForOrgVariableCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	actionsSetSelectedReposForOrgVariableCmd.Flags().String("selected-repository-ids", "", "The IDs of the repositories that can access the organization variable.")
	_ = actionsSetSelectedReposForOrgVariableCmd.MarkFlagRequired("selected-repository-ids")
}
