// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsListWorkflowRunArtifactsCmd = &cobra.Command{
	Use:   "list-workflow-run-artifacts",
	Short: "List workflow run artifacts",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/actions/runs/{run_id}/artifacts"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		runIdVal, _ := cmd.Flags().GetString("run-id")
		if runIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "run-id")
		}
		path = strings.Replace(path, "{run_id}", runIdVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("per-page"); v != "" {
			params["per_page"] = v
		}
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		if v, _ := cmd.Flags().GetString("name"); v != "" {
			params["name"] = v
		}
		if v, _ := cmd.Flags().GetString("direction"); v != "" {
			params["direction"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsListWorkflowRunArtifactsCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = actionsListWorkflowRunArtifactsCmd.MarkFlagRequired("owner")
	actionsListWorkflowRunArtifactsCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = actionsListWorkflowRunArtifactsCmd.MarkFlagRequired("repo")
	actionsListWorkflowRunArtifactsCmd.Flags().String("run-id", "", "The unique identifier of the workflow run.")
	_ = actionsListWorkflowRunArtifactsCmd.MarkFlagRequired("run-id")
	actionsListWorkflowRunArtifactsCmd.Flags().String("per-page", "30", "The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	actionsListWorkflowRunArtifactsCmd.Flags().String("page", "1", "The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	actionsListWorkflowRunArtifactsCmd.Flags().String("name", "", "The name field of an artifact. When specified, only artifacts with this name will be returned.")
	actionsListWorkflowRunArtifactsCmd.Flags().String("direction", "desc", "The direction to sort the results by.")
	_ = actionsListWorkflowRunArtifactsCmd.RegisterFlagCompletionFunc("direction", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"asc", "desc"}, cobra.ShellCompDirectiveNoFileComp
	})
}
