// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsUpdateHostedRunnerForOrgCmd = &cobra.Command{
	Use:   "update-hosted-runner-for-org",
	Short: "Update a GitHub-hosted runner for an organization",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/actions/hosted-runners/{hosted_runner_id}"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		hostedRunnerIdVal, _ := cmd.Flags().GetString("hosted-runner-id")
		if hostedRunnerIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "hosted-runner-id")
		}
		path = strings.Replace(path, "{hosted_runner_id}", hostedRunnerIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "name", JSONPath: "name", Type: "string"},
			{FlagName: "runner-group-id", JSONPath: "runner_group_id", Type: "integer"},
			{FlagName: "maximum-runners", JSONPath: "maximum_runners", Type: "integer"},
			{FlagName: "enable-static-ip", JSONPath: "enable_static_ip", Type: "boolean"},
			{FlagName: "size", JSONPath: "size", Type: "string"},
			{FlagName: "image-id", JSONPath: "image_id", Type: "string"},
			{FlagName: "image-version", JSONPath: "image_version", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PATCH", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsUpdateHostedRunnerForOrgCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = actionsUpdateHostedRunnerForOrgCmd.MarkFlagRequired("org")
	actionsUpdateHostedRunnerForOrgCmd.Flags().String("hosted-runner-id", "", "Unique identifier of the GitHub-hosted runner.")
	_ = actionsUpdateHostedRunnerForOrgCmd.MarkFlagRequired("hosted-runner-id")
	actionsUpdateHostedRunnerForOrgCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	actionsUpdateHostedRunnerForOrgCmd.Flags().String("name", "", "Name of the runner. Must be between 1 and 64 characters and may only contain upper and lowercase letters a-z, numbers 0-9, '.', '-', and '_'.")
	actionsUpdateHostedRunnerForOrgCmd.Flags().String("runner-group-id", "", "The existing runner group to add this runner to.")
	actionsUpdateHostedRunnerForOrgCmd.Flags().String("maximum-runners", "", "The maximum amount of runners to scale up to. Runners will not auto-scale above this number. Use this setting to limit your cost.")
	actionsUpdateHostedRunnerForOrgCmd.Flags().String("enable-static-ip", "", "Whether this runner should be updated with a static public IP. Note limit on account. To list limits on account, use `GET actions/hosted-runners/limits`")
	actionsUpdateHostedRunnerForOrgCmd.Flags().String("size", "", "The machine size of the runner. To list available sizes, use `GET actions/hosted-runners/machine-sizes`")
	actionsUpdateHostedRunnerForOrgCmd.Flags().String("image-id", "", "The unique identifier of the runner image. To list available images, use `GET /actions/hosted-runners/images/github-owned`, `GET /actions/hosted-runners/images/partner`, or `GET /actions/hosted-runners/images/custom`.")
	actionsUpdateHostedRunnerForOrgCmd.Flags().String("image-version", "", "The version of the runner image to deploy. This is relevant only for runners using custom images.")
}
