// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsSetCustomLabelsForSelfHostedRunnerForOrgCmd = &cobra.Command{
	Use:   "set-custom-labels-for-self-hosted-runner-for-org",
	Short: "Set custom labels for a self-hosted runner for an organization",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/actions/runners/{runner_id}/labels"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		runnerIdVal, _ := cmd.Flags().GetString("runner-id")
		if runnerIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "runner-id")
		}
		path = strings.Replace(path, "{runner_id}", runnerIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "labels", JSONPath: "labels", Type: "array"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsSetCustomLabelsForSelfHostedRunnerForOrgCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = actionsSetCustomLabelsForSelfHostedRunnerForOrgCmd.MarkFlagRequired("org")
	actionsSetCustomLabelsForSelfHostedRunnerForOrgCmd.Flags().String("runner-id", "", "Unique identifier of the self-hosted runner.")
	_ = actionsSetCustomLabelsForSelfHostedRunnerForOrgCmd.MarkFlagRequired("runner-id")
	actionsSetCustomLabelsForSelfHostedRunnerForOrgCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	actionsSetCustomLabelsForSelfHostedRunnerForOrgCmd.Flags().String("labels", "", "The names of the custom labels to set for the runner. You can pass an empty array to remove all custom labels.")
	_ = actionsSetCustomLabelsForSelfHostedRunnerForOrgCmd.MarkFlagRequired("labels")
}
