// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsSetForkPrContributorApprovalPermissionsRepositoryCmd = &cobra.Command{
	Use:   "set-fork-pr-contributor-approval-permissions-repository",
	Short: "Set fork PR contributor approval permissions for a repository",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/actions/permissions/fork-pr-contributor-approval"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "approval-policy", JSONPath: "approval_policy", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsSetForkPrContributorApprovalPermissionsRepositoryCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = actionsSetForkPrContributorApprovalPermissionsRepositoryCmd.MarkFlagRequired("owner")
	actionsSetForkPrContributorApprovalPermissionsRepositoryCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = actionsSetForkPrContributorApprovalPermissionsRepositoryCmd.MarkFlagRequired("repo")
	actionsSetForkPrContributorApprovalPermissionsRepositoryCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	actionsSetForkPrContributorApprovalPermissionsRepositoryCmd.Flags().String("approval-policy", "", "The policy that controls when fork PR workflows require approval from a maintainer.")
	_ = actionsSetForkPrContributorApprovalPermissionsRepositoryCmd.RegisterFlagCompletionFunc("approval-policy", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"first_time_contributors_new_to_github", "first_time_contributors", "all_external_contributors"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = actionsSetForkPrContributorApprovalPermissionsRepositoryCmd.MarkFlagRequired("approval-policy")
}
