// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsListJobsForWorkflowRunCmd = &cobra.Command{
	Use:   "list-jobs-for-workflow-run",
	Short: "List jobs for a workflow run",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/actions/runs/{run_id}/jobs"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		runIdVal, _ := cmd.Flags().GetString("run-id")
		if runIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "run-id")
		}
		path = strings.Replace(path, "{run_id}", runIdVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("filter"); v != "" {
			params["filter"] = v
		}
		if v, _ := cmd.Flags().GetString("per-page"); v != "" {
			params["per_page"] = v
		}
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsListJobsForWorkflowRunCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = actionsListJobsForWorkflowRunCmd.MarkFlagRequired("owner")
	actionsListJobsForWorkflowRunCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = actionsListJobsForWorkflowRunCmd.MarkFlagRequired("repo")
	actionsListJobsForWorkflowRunCmd.Flags().String("run-id", "", "The unique identifier of the workflow run.")
	_ = actionsListJobsForWorkflowRunCmd.MarkFlagRequired("run-id")
	actionsListJobsForWorkflowRunCmd.Flags().String("filter", "latest", "Filters jobs by their `completed_at` timestamp. `latest` returns jobs from the most recent execution of the workflow run. `all` returns all jobs for a workflow run, including from old executions of the workflow run.")
	_ = actionsListJobsForWorkflowRunCmd.RegisterFlagCompletionFunc("filter", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"latest", "all"}, cobra.ShellCompDirectiveNoFileComp
	})
	actionsListJobsForWorkflowRunCmd.Flags().String("per-page", "30", "The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	actionsListJobsForWorkflowRunCmd.Flags().String("page", "1", "The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
}
