// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsDeleteOrgVariableCmd = &cobra.Command{
	Use:   "delete-org-variable",
	Short: "Delete an organization variable",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/actions/variables/{name}"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		nameVal, _ := cmd.Flags().GetString("name")
		if nameVal == "" {
			return fmt.Errorf("required flag --%s not set", "name")
		}
		path = strings.Replace(path, "{name}", nameVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsDeleteOrgVariableCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = actionsDeleteOrgVariableCmd.MarkFlagRequired("org")
	actionsDeleteOrgVariableCmd.Flags().String("name", "", "The name of the variable.")
	_ = actionsDeleteOrgVariableCmd.MarkFlagRequired("name")
}
