// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsGetCustomImageVersionForOrgCmd = &cobra.Command{
	Use:   "get-custom-image-version-for-org",
	Short: "Get an image version of a custom image for GitHub Actions Hosted Runners",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/actions/hosted-runners/images/custom/{image_definition_id}/versions/{version}"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		imageDefinitionIdVal, _ := cmd.Flags().GetString("image-definition-id")
		if imageDefinitionIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "image-definition-id")
		}
		path = strings.Replace(path, "{image_definition_id}", imageDefinitionIdVal, 1)
		versionVal, _ := cmd.Flags().GetString("version")
		if versionVal == "" {
			return fmt.Errorf("required flag --%s not set", "version")
		}
		path = strings.Replace(path, "{version}", versionVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsGetCustomImageVersionForOrgCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = actionsGetCustomImageVersionForOrgCmd.MarkFlagRequired("org")
	actionsGetCustomImageVersionForOrgCmd.Flags().String("image-definition-id", "", "Image definition ID of custom image")
	_ = actionsGetCustomImageVersionForOrgCmd.MarkFlagRequired("image-definition-id")
	actionsGetCustomImageVersionForOrgCmd.Flags().String("version", "", "Version of a custom image")
	_ = actionsGetCustomImageVersionForOrgCmd.MarkFlagRequired("version")
}
