// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsDownloadArtifactCmd = &cobra.Command{
	Use:   "download-artifact",
	Short: "Download an artifact",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/actions/artifacts/{artifact_id}/{archive_format}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		artifactIdVal, _ := cmd.Flags().GetString("artifact-id")
		if artifactIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "artifact-id")
		}
		path = strings.Replace(path, "{artifact_id}", artifactIdVal, 1)
		archiveFormatVal, _ := cmd.Flags().GetString("archive-format")
		if archiveFormatVal == "" {
			return fmt.Errorf("required flag --%s not set", "archive-format")
		}
		path = strings.Replace(path, "{archive_format}", archiveFormatVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsDownloadArtifactCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = actionsDownloadArtifactCmd.MarkFlagRequired("owner")
	actionsDownloadArtifactCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = actionsDownloadArtifactCmd.MarkFlagRequired("repo")
	actionsDownloadArtifactCmd.Flags().String("artifact-id", "", "The unique identifier of the artifact.")
	_ = actionsDownloadArtifactCmd.MarkFlagRequired("artifact-id")
	actionsDownloadArtifactCmd.Flags().String("archive-format", "", "")
	_ = actionsDownloadArtifactCmd.MarkFlagRequired("archive-format")
}
