// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsGetEnvironmentPublicKeyCmd = &cobra.Command{
	Use:   "get-environment-public-key",
	Short: "Get an environment public key",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/environments/{environment_name}/secrets/public-key"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		environmentNameVal, _ := cmd.Flags().GetString("environment-name")
		if environmentNameVal == "" {
			return fmt.Errorf("required flag --%s not set", "environment-name")
		}
		path = strings.Replace(path, "{environment_name}", environmentNameVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsGetEnvironmentPublicKeyCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = actionsGetEnvironmentPublicKeyCmd.MarkFlagRequired("owner")
	actionsGetEnvironmentPublicKeyCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = actionsGetEnvironmentPublicKeyCmd.MarkFlagRequired("repo")
	actionsGetEnvironmentPublicKeyCmd.Flags().String("environment-name", "", "The name of the environment. The name must be URL encoded. For example, any slashes in the name must be replaced with `%2F`.")
	_ = actionsGetEnvironmentPublicKeyCmd.MarkFlagRequired("environment-name")
}
