// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsAddSelectedRepoToOrgVariableCmd = &cobra.Command{
	Use:   "add-selected-repo-to-org-variable",
	Short: "Add selected repository to an organization variable",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/actions/variables/{name}/repositories/{repository_id}"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		nameVal, _ := cmd.Flags().GetString("name")
		if nameVal == "" {
			return fmt.Errorf("required flag --%s not set", "name")
		}
		path = strings.Replace(path, "{name}", nameVal, 1)
		repositoryIdVal, _ := cmd.Flags().GetString("repository-id")
		if repositoryIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "repository-id")
		}
		path = strings.Replace(path, "{repository_id}", repositoryIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("PUT", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsAddSelectedRepoToOrgVariableCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = actionsAddSelectedRepoToOrgVariableCmd.MarkFlagRequired("org")
	actionsAddSelectedRepoToOrgVariableCmd.Flags().String("name", "", "The name of the variable.")
	_ = actionsAddSelectedRepoToOrgVariableCmd.MarkFlagRequired("name")
	actionsAddSelectedRepoToOrgVariableCmd.Flags().String("repository-id", "", "")
	_ = actionsAddSelectedRepoToOrgVariableCmd.MarkFlagRequired("repository-id")
}
