// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsDeleteActionsCacheByIdCmd = &cobra.Command{
	Use:   "delete-actions-cache-by-id",
	Short: "Delete a GitHub Actions cache for a repository (using a cache ID)",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/actions/caches/{cache_id}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		cacheIdVal, _ := cmd.Flags().GetString("cache-id")
		if cacheIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "cache-id")
		}
		path = strings.Replace(path, "{cache_id}", cacheIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsDeleteActionsCacheByIdCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = actionsDeleteActionsCacheByIdCmd.MarkFlagRequired("owner")
	actionsDeleteActionsCacheByIdCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = actionsDeleteActionsCacheByIdCmd.MarkFlagRequired("repo")
	actionsDeleteActionsCacheByIdCmd.Flags().String("cache-id", "", "The unique identifier of the GitHub Actions cache.")
	_ = actionsDeleteActionsCacheByIdCmd.MarkFlagRequired("cache-id")
}
