// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsSetGithubActionsPermissionsRepositoryCmd = &cobra.Command{
	Use:   "set-github-actions-permissions-repository",
	Short: "Set GitHub Actions permissions for a repository",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/actions/permissions"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "enabled", JSONPath: "enabled", Type: "boolean"},
			{FlagName: "allowed-actions", JSONPath: "allowed_actions", Type: "string"},
			{FlagName: "sha-pinning-required", JSONPath: "sha_pinning_required", Type: "boolean"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsSetGithubActionsPermissionsRepositoryCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = actionsSetGithubActionsPermissionsRepositoryCmd.MarkFlagRequired("owner")
	actionsSetGithubActionsPermissionsRepositoryCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = actionsSetGithubActionsPermissionsRepositoryCmd.MarkFlagRequired("repo")
	actionsSetGithubActionsPermissionsRepositoryCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	actionsSetGithubActionsPermissionsRepositoryCmd.Flags().String("enabled", "", "Whether GitHub Actions is enabled on the repository.")
	_ = actionsSetGithubActionsPermissionsRepositoryCmd.MarkFlagRequired("enabled")
	actionsSetGithubActionsPermissionsRepositoryCmd.Flags().String("allowed-actions", "", "The permissions policy that controls the actions and reusable workflows that are allowed to run.")
	_ = actionsSetGithubActionsPermissionsRepositoryCmd.RegisterFlagCompletionFunc("allowed-actions", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"all", "local_only", "selected"}, cobra.ShellCompDirectiveNoFileComp
	})
	actionsSetGithubActionsPermissionsRepositoryCmd.Flags().String("sha-pinning-required", "", "Whether actions must be pinned to a full-length commit SHA.")
}
