// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsListSelfHostedRunnersInGroupForOrgCmd = &cobra.Command{
	Use:   "list-self-hosted-runners-in-group-for-org",
	Short: "List self-hosted runners in a group for an organization",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/actions/runner-groups/{runner_group_id}/runners"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		runnerGroupIdVal, _ := cmd.Flags().GetString("runner-group-id")
		if runnerGroupIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "runner-group-id")
		}
		path = strings.Replace(path, "{runner_group_id}", runnerGroupIdVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("per-page"); v != "" {
			params["per_page"] = v
		}
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsListSelfHostedRunnersInGroupForOrgCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = actionsListSelfHostedRunnersInGroupForOrgCmd.MarkFlagRequired("org")
	actionsListSelfHostedRunnersInGroupForOrgCmd.Flags().String("runner-group-id", "", "Unique identifier of the self-hosted runner group.")
	_ = actionsListSelfHostedRunnersInGroupForOrgCmd.MarkFlagRequired("runner-group-id")
	actionsListSelfHostedRunnersInGroupForOrgCmd.Flags().String("per-page", "30", "The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	actionsListSelfHostedRunnersInGroupForOrgCmd.Flags().String("page", "1", "The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
}
