// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var actionsGenerateRunnerJitconfigForOrgCmd = &cobra.Command{
	Use:   "generate-runner-jitconfig-for-org",
	Short: "Create configuration for a just-in-time runner for an organization",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/actions/runners/generate-jitconfig"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "name", JSONPath: "name", Type: "string"},
			{FlagName: "runner-group-id", JSONPath: "runner_group_id", Type: "integer"},
			{FlagName: "labels", JSONPath: "labels", Type: "array"},
			{FlagName: "work-folder", JSONPath: "work_folder", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	actionsGenerateRunnerJitconfigForOrgCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = actionsGenerateRunnerJitconfigForOrgCmd.MarkFlagRequired("org")
	actionsGenerateRunnerJitconfigForOrgCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	actionsGenerateRunnerJitconfigForOrgCmd.Flags().String("name", "", "The name of the new runner.")
	_ = actionsGenerateRunnerJitconfigForOrgCmd.MarkFlagRequired("name")
	actionsGenerateRunnerJitconfigForOrgCmd.Flags().String("runner-group-id", "", "The ID of the runner group to register the runner to.")
	_ = actionsGenerateRunnerJitconfigForOrgCmd.MarkFlagRequired("runner-group-id")
	actionsGenerateRunnerJitconfigForOrgCmd.Flags().String("labels", "", "The names of the custom labels to add to the runner. **Minimum items**: 1. **Maximum items**: 100.")
	_ = actionsGenerateRunnerJitconfigForOrgCmd.MarkFlagRequired("labels")
	actionsGenerateRunnerJitconfigForOrgCmd.Flags().String("work-folder", "_work", "The working directory to be used for job execution, relative to the runner install directory.")
}
