// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var appsCheckTokenCmd = &cobra.Command{
	Use:   "check-token",
	Short: "Check a token",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/applications/{client_id}/token"
		clientIdVal, _ := cmd.Flags().GetString("client-id")
		if clientIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "client-id")
		}
		path = strings.Replace(path, "{client_id}", clientIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "access-token", JSONPath: "access_token", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	appsCheckTokenCmd.Flags().String("client-id", "", "The client ID of the GitHub app.")
	_ = appsCheckTokenCmd.MarkFlagRequired("client-id")
	appsCheckTokenCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	appsCheckTokenCmd.Flags().String("access-token", "", "The access_token of the OAuth or GitHub application.")
	_ = appsCheckTokenCmd.MarkFlagRequired("access-token")
}
