// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var appsSuspendInstallationCmd = &cobra.Command{
	Use:   "suspend-installation",
	Short: "Suspend an app installation",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/app/installations/{installation_id}/suspended"
		installationIdVal, _ := cmd.Flags().GetString("installation-id")
		if installationIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "installation-id")
		}
		path = strings.Replace(path, "{installation_id}", installationIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("PUT", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	appsSuspendInstallationCmd.Flags().String("installation-id", "", "The unique identifier of the installation.")
	_ = appsSuspendInstallationCmd.MarkFlagRequired("installation-id")
}
