// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var appsUpdateWebhookConfigForAppCmd = &cobra.Command{
	Use:   "update-webhook-config-for-app",
	Short: "Update a webhook configuration for an app",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/app/hook/config"

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "url", JSONPath: "url", Type: "string"},
			{FlagName: "content-type", JSONPath: "content_type", Type: "string"},
			{FlagName: "secret", JSONPath: "secret", Type: "string"},
			{FlagName: "insecure-ssl", JSONPath: "insecure_ssl", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PATCH", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	appsUpdateWebhookConfigForAppCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	appsUpdateWebhookConfigForAppCmd.Flags().String("url", "", "The URL to which the payloads will be delivered.")
	appsUpdateWebhookConfigForAppCmd.Flags().String("content-type", "", "The media type used to serialize the payloads. Supported values include `json` and `form`. The default is `form`.")
	appsUpdateWebhookConfigForAppCmd.Flags().String("secret", "", "If provided, the `secret` will be used as the `key` to generate the HMAC hex digest value for [delivery signature headers](https://docs.github.com/webhooks/event-payloads/#delivery-headers).")
	appsUpdateWebhookConfigForAppCmd.Flags().String("insecure-ssl", "", "")
}
