// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var appsScopeTokenCmd = &cobra.Command{
	Use:   "scope-token",
	Short: "Create a scoped access token",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/applications/{client_id}/token/scoped"
		clientIdVal, _ := cmd.Flags().GetString("client-id")
		if clientIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "client-id")
		}
		path = strings.Replace(path, "{client_id}", clientIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "access-token", JSONPath: "access_token", Type: "string"},
			{FlagName: "target", JSONPath: "target", Type: "string"},
			{FlagName: "target-id", JSONPath: "target_id", Type: "integer"},
			{FlagName: "repositories", JSONPath: "repositories", Type: "array"},
			{FlagName: "repository-ids", JSONPath: "repository_ids", Type: "array"},
			{FlagName: "permissions.actions", JSONPath: "permissions.actions", Type: "string"},
			{FlagName: "permissions.administration", JSONPath: "permissions.administration", Type: "string"},
			{FlagName: "permissions.artifact-metadata", JSONPath: "permissions.artifact_metadata", Type: "string"},
			{FlagName: "permissions.attestations", JSONPath: "permissions.attestations", Type: "string"},
			{FlagName: "permissions.checks", JSONPath: "permissions.checks", Type: "string"},
			{FlagName: "permissions.codespaces", JSONPath: "permissions.codespaces", Type: "string"},
			{FlagName: "permissions.contents", JSONPath: "permissions.contents", Type: "string"},
			{FlagName: "permissions.dependabot-secrets", JSONPath: "permissions.dependabot_secrets", Type: "string"},
			{FlagName: "permissions.deployments", JSONPath: "permissions.deployments", Type: "string"},
			{FlagName: "permissions.discussions", JSONPath: "permissions.discussions", Type: "string"},
			{FlagName: "permissions.environments", JSONPath: "permissions.environments", Type: "string"},
			{FlagName: "permissions.issues", JSONPath: "permissions.issues", Type: "string"},
			{FlagName: "permissions.merge-queues", JSONPath: "permissions.merge_queues", Type: "string"},
			{FlagName: "permissions.metadata", JSONPath: "permissions.metadata", Type: "string"},
			{FlagName: "permissions.packages", JSONPath: "permissions.packages", Type: "string"},
			{FlagName: "permissions.pages", JSONPath: "permissions.pages", Type: "string"},
			{FlagName: "permissions.pull-requests", JSONPath: "permissions.pull_requests", Type: "string"},
			{FlagName: "permissions.repository-custom-properties", JSONPath: "permissions.repository_custom_properties", Type: "string"},
			{FlagName: "permissions.repository-hooks", JSONPath: "permissions.repository_hooks", Type: "string"},
			{FlagName: "permissions.repository-projects", JSONPath: "permissions.repository_projects", Type: "string"},
			{FlagName: "permissions.secret-scanning-alerts", JSONPath: "permissions.secret_scanning_alerts", Type: "string"},
			{FlagName: "permissions.secrets", JSONPath: "permissions.secrets", Type: "string"},
			{FlagName: "permissions.security-events", JSONPath: "permissions.security_events", Type: "string"},
			{FlagName: "permissions.single-file", JSONPath: "permissions.single_file", Type: "string"},
			{FlagName: "permissions.statuses", JSONPath: "permissions.statuses", Type: "string"},
			{FlagName: "permissions.vulnerability-alerts", JSONPath: "permissions.vulnerability_alerts", Type: "string"},
			{FlagName: "permissions.workflows", JSONPath: "permissions.workflows", Type: "string"},
			{FlagName: "permissions.custom-properties-for-organizations", JSONPath: "permissions.custom_properties_for_organizations", Type: "string"},
			{FlagName: "permissions.members", JSONPath: "permissions.members", Type: "string"},
			{FlagName: "permissions.organization-administration", JSONPath: "permissions.organization_administration", Type: "string"},
			{FlagName: "permissions.organization-custom-roles", JSONPath: "permissions.organization_custom_roles", Type: "string"},
			{FlagName: "permissions.organization-custom-org-roles", JSONPath: "permissions.organization_custom_org_roles", Type: "string"},
			{FlagName: "permissions.organization-custom-properties", JSONPath: "permissions.organization_custom_properties", Type: "string"},
			{FlagName: "permissions.organization-copilot-seat-management", JSONPath: "permissions.organization_copilot_seat_management", Type: "string"},
			{FlagName: "permissions.organization-copilot-agent-settings", JSONPath: "permissions.organization_copilot_agent_settings", Type: "string"},
			{FlagName: "permissions.organization-announcement-banners", JSONPath: "permissions.organization_announcement_banners", Type: "string"},
			{FlagName: "permissions.organization-events", JSONPath: "permissions.organization_events", Type: "string"},
			{FlagName: "permissions.organization-hooks", JSONPath: "permissions.organization_hooks", Type: "string"},
			{FlagName: "permissions.organization-personal-access-tokens", JSONPath: "permissions.organization_personal_access_tokens", Type: "string"},
			{FlagName: "permissions.organization-personal-access-token-requests", JSONPath: "permissions.organization_personal_access_token_requests", Type: "string"},
			{FlagName: "permissions.organization-plan", JSONPath: "permissions.organization_plan", Type: "string"},
			{FlagName: "permissions.organization-projects", JSONPath: "permissions.organization_projects", Type: "string"},
			{FlagName: "permissions.organization-packages", JSONPath: "permissions.organization_packages", Type: "string"},
			{FlagName: "permissions.organization-secrets", JSONPath: "permissions.organization_secrets", Type: "string"},
			{FlagName: "permissions.organization-self-hosted-runners", JSONPath: "permissions.organization_self_hosted_runners", Type: "string"},
			{FlagName: "permissions.organization-user-blocking", JSONPath: "permissions.organization_user_blocking", Type: "string"},
			{FlagName: "permissions.email-addresses", JSONPath: "permissions.email_addresses", Type: "string"},
			{FlagName: "permissions.followers", JSONPath: "permissions.followers", Type: "string"},
			{FlagName: "permissions.git-ssh-keys", JSONPath: "permissions.git_ssh_keys", Type: "string"},
			{FlagName: "permissions.gpg-keys", JSONPath: "permissions.gpg_keys", Type: "string"},
			{FlagName: "permissions.interaction-limits", JSONPath: "permissions.interaction_limits", Type: "string"},
			{FlagName: "permissions.profile", JSONPath: "permissions.profile", Type: "string"},
			{FlagName: "permissions.starring", JSONPath: "permissions.starring", Type: "string"},
			{FlagName: "permissions.enterprise-custom-properties-for-organizations", JSONPath: "permissions.enterprise_custom_properties_for_organizations", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	appsScopeTokenCmd.Flags().String("client-id", "", "The client ID of the GitHub app.")
	_ = appsScopeTokenCmd.MarkFlagRequired("client-id")
	appsScopeTokenCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	appsScopeTokenCmd.Flags().String("access-token", "", "The access token used to authenticate to the GitHub API.")
	_ = appsScopeTokenCmd.MarkFlagRequired("access-token")
	appsScopeTokenCmd.Flags().String("target", "", "The name of the user or organization to scope the user access token to. **Required** unless `target_id` is specified.")
	appsScopeTokenCmd.Flags().String("target-id", "", "The ID of the user or organization to scope the user access token to. **Required** unless `target` is specified.")
	appsScopeTokenCmd.Flags().String("repositories", "", "The list of repository names to scope the user access token to. `repositories` may not be specified if `repository_ids` is specified.")
	appsScopeTokenCmd.Flags().String("repository-ids", "", "The list of repository IDs to scope the user access token to. `repository_ids` may not be specified if `repositories` is specified.")
	appsScopeTokenCmd.Flags().String("permissions.actions", "", "The level of permission to grant the access token for GitHub Actions workflows, workflow runs, and artifacts.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.actions", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.administration", "", "The level of permission to grant the access token for repository creation, deletion, settings, teams, and collaborators creation.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.administration", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.artifact-metadata", "", "The level of permission to grant the access token to create and retrieve build artifact metadata records.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.artifact-metadata", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.attestations", "", "The level of permission to create and retrieve the access token for repository attestations.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.attestations", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.checks", "", "The level of permission to grant the access token for checks on code.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.checks", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.codespaces", "", "The level of permission to grant the access token to create, edit, delete, and list Codespaces.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.codespaces", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.contents", "", "The level of permission to grant the access token for repository contents, commits, branches, downloads, releases, and merges.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.contents", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.dependabot-secrets", "", "The level of permission to grant the access token to manage Dependabot secrets.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.dependabot-secrets", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.deployments", "", "The level of permission to grant the access token for deployments and deployment statuses.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.deployments", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.discussions", "", "The level of permission to grant the access token for discussions and related comments and labels.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.discussions", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.environments", "", "The level of permission to grant the access token for managing repository environments.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.environments", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.issues", "", "The level of permission to grant the access token for issues and related comments, assignees, labels, and milestones.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.issues", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.merge-queues", "", "The level of permission to grant the access token to manage the merge queues for a repository.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.merge-queues", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.metadata", "", "The level of permission to grant the access token to search repositories, list collaborators, and access repository metadata.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.metadata", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.packages", "", "The level of permission to grant the access token for packages published to GitHub Packages.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.packages", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.pages", "", "The level of permission to grant the access token to retrieve Pages statuses, configuration, and builds, as well as create new builds.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.pages", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.pull-requests", "", "The level of permission to grant the access token for pull requests and related comments, assignees, labels, milestones, and merges.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.pull-requests", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.repository-custom-properties", "", "The level of permission to grant the access token to view and edit custom properties for a repository, when allowed by the property.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.repository-custom-properties", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.repository-hooks", "", "The level of permission to grant the access token to manage the post-receive hooks for a repository.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.repository-hooks", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.repository-projects", "", "The level of permission to grant the access token to manage repository projects, columns, and cards.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.repository-projects", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write", "admin"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.secret-scanning-alerts", "", "The level of permission to grant the access token to view and manage secret scanning alerts.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.secret-scanning-alerts", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.secrets", "", "The level of permission to grant the access token to manage repository secrets.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.secrets", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.security-events", "", "The level of permission to grant the access token to view and manage security events like code scanning alerts.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.security-events", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.single-file", "", "The level of permission to grant the access token to manage just a single file.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.single-file", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.statuses", "", "The level of permission to grant the access token for commit statuses.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.statuses", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.vulnerability-alerts", "", "The level of permission to grant the access token to manage Dependabot alerts.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.vulnerability-alerts", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.workflows", "", "The level of permission to grant the access token to update GitHub Actions workflow files.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.workflows", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.custom-properties-for-organizations", "", "The level of permission to grant the access token to view and edit custom properties for an organization, when allowed by the property.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.custom-properties-for-organizations", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.members", "", "The level of permission to grant the access token for organization teams and members.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.members", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.organization-administration", "", "The level of permission to grant the access token to manage access to an organization.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.organization-administration", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.organization-custom-roles", "", "The level of permission to grant the access token for custom repository roles management.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.organization-custom-roles", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.organization-custom-org-roles", "", "The level of permission to grant the access token for custom organization roles management.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.organization-custom-org-roles", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.organization-custom-properties", "", "The level of permission to grant the access token for repository custom properties management at the organization level.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.organization-custom-properties", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write", "admin"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.organization-copilot-seat-management", "", "The level of permission to grant the access token for managing access to GitHub Copilot for members of an organization with a Copilot Business subscription. This property is in public preview and is subject to change.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.organization-copilot-seat-management", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.organization-copilot-agent-settings", "", "The level of permission to grant the access token to view and manage Copilot coding agent settings for an organization.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.organization-copilot-agent-settings", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.organization-announcement-banners", "", "The level of permission to grant the access token to view and manage announcement banners for an organization.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.organization-announcement-banners", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.organization-events", "", "The level of permission to grant the access token to view events triggered by an activity in an organization.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.organization-events", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.organization-hooks", "", "The level of permission to grant the access token to manage the post-receive hooks for an organization.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.organization-hooks", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.organization-personal-access-tokens", "", "The level of permission to grant the access token for viewing and managing fine-grained personal access token requests to an organization.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.organization-personal-access-tokens", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.organization-personal-access-token-requests", "", "The level of permission to grant the access token for viewing and managing fine-grained personal access tokens that have been approved by an organization.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.organization-personal-access-token-requests", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.organization-plan", "", "The level of permission to grant the access token for viewing an organization's plan.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.organization-plan", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.organization-projects", "", "The level of permission to grant the access token to manage organization projects and projects public preview (where available).")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.organization-projects", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write", "admin"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.organization-packages", "", "The level of permission to grant the access token for organization packages published to GitHub Packages.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.organization-packages", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.organization-secrets", "", "The level of permission to grant the access token to manage organization secrets.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.organization-secrets", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.organization-self-hosted-runners", "", "The level of permission to grant the access token to view and manage GitHub Actions self-hosted runners available to an organization.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.organization-self-hosted-runners", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.organization-user-blocking", "", "The level of permission to grant the access token to view and manage users blocked by the organization.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.organization-user-blocking", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.email-addresses", "", "The level of permission to grant the access token to manage the email addresses belonging to a user.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.email-addresses", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.followers", "", "The level of permission to grant the access token to manage the followers belonging to a user.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.followers", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.git-ssh-keys", "", "The level of permission to grant the access token to manage git SSH keys.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.git-ssh-keys", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.gpg-keys", "", "The level of permission to grant the access token to view and manage GPG keys belonging to a user.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.gpg-keys", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.interaction-limits", "", "The level of permission to grant the access token to view and manage interaction limits on a repository.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.interaction-limits", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.profile", "", "The level of permission to grant the access token to manage the profile settings belonging to a user.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.profile", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.starring", "", "The level of permission to grant the access token to list and manage repositories a user is starring.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.starring", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write"}, cobra.ShellCompDirectiveNoFileComp
	})
	appsScopeTokenCmd.Flags().String("permissions.enterprise-custom-properties-for-organizations", "", "The level of permission to grant the access token for organization custom properties management at the enterprise level.")
	_ = appsScopeTokenCmd.RegisterFlagCompletionFunc("permissions.enterprise-custom-properties-for-organizations", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"read", "write", "admin"}, cobra.ShellCompDirectiveNoFileComp
	})
}
