// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var billingGetGithubBillingUsageSummaryReportUserCmd = &cobra.Command{
	Use:   "get-github-billing-usage-summary-report-user",
	Short: "Get billing usage summary for a user",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/users/{username}/settings/billing/usage/summary"
		usernameVal, _ := cmd.Flags().GetString("username")
		if usernameVal == "" {
			return fmt.Errorf("required flag --%s not set", "username")
		}
		path = strings.Replace(path, "{username}", usernameVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("year"); v != "" {
			params["year"] = v
		}
		if v, _ := cmd.Flags().GetString("month"); v != "" {
			params["month"] = v
		}
		if v, _ := cmd.Flags().GetString("day"); v != "" {
			params["day"] = v
		}
		if v, _ := cmd.Flags().GetString("repository"); v != "" {
			params["repository"] = v
		}
		if v, _ := cmd.Flags().GetString("product"); v != "" {
			params["product"] = v
		}
		if v, _ := cmd.Flags().GetString("sku"); v != "" {
			params["sku"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	billingGetGithubBillingUsageSummaryReportUserCmd.Flags().String("username", "", "The handle for the GitHub user account.")
	_ = billingGetGithubBillingUsageSummaryReportUserCmd.MarkFlagRequired("username")
	billingGetGithubBillingUsageSummaryReportUserCmd.Flags().String("year", "", "If specified, only return results for a single year. The value of `year` is an integer with four digits representing a year. For example, `2025`. Default value is the current year.")
	billingGetGithubBillingUsageSummaryReportUserCmd.Flags().String("month", "", "If specified, only return results for a single month. The value of `month` is an integer between `1` and `12`. Default value is the current month. If no year is specified the default `year` is used.")
	billingGetGithubBillingUsageSummaryReportUserCmd.Flags().String("day", "", "If specified, only return results for a single day. The value of `day` is an integer between `1` and `31`. If no `year` or `month` is specified, the default `year` and `month` are used.")
	billingGetGithubBillingUsageSummaryReportUserCmd.Flags().String("repository", "", "The repository name to query for usage in the format owner/repository.")
	billingGetGithubBillingUsageSummaryReportUserCmd.Flags().String("product", "", "The product name to query usage for. The name is not case sensitive.")
	billingGetGithubBillingUsageSummaryReportUserCmd.Flags().String("sku", "", "The SKU to query for usage.")
}
