// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var campaignsDeleteCampaignCmd = &cobra.Command{
	Use:   "delete-campaign",
	Short: "Delete a campaign for an organization",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/campaigns/{campaign_number}"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		campaignNumberVal, _ := cmd.Flags().GetString("campaign-number")
		if campaignNumberVal == "" {
			return fmt.Errorf("required flag --%s not set", "campaign-number")
		}
		path = strings.Replace(path, "{campaign_number}", campaignNumberVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	campaignsDeleteCampaignCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = campaignsDeleteCampaignCmd.MarkFlagRequired("org")
	campaignsDeleteCampaignCmd.Flags().String("campaign-number", "", "The campaign number.")
	_ = campaignsDeleteCampaignCmd.MarkFlagRequired("campaign-number")
}
