// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var campaignsUpdateCampaignCmd = &cobra.Command{
	Use:   "update-campaign",
	Short: "Update a campaign",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/campaigns/{campaign_number}"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		campaignNumberVal, _ := cmd.Flags().GetString("campaign-number")
		if campaignNumberVal == "" {
			return fmt.Errorf("required flag --%s not set", "campaign-number")
		}
		path = strings.Replace(path, "{campaign_number}", campaignNumberVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "name", JSONPath: "name", Type: "string"},
			{FlagName: "description", JSONPath: "description", Type: "string"},
			{FlagName: "managers", JSONPath: "managers", Type: "array"},
			{FlagName: "team-managers", JSONPath: "team_managers", Type: "array"},
			{FlagName: "ends-at", JSONPath: "ends_at", Type: "string"},
			{FlagName: "contact-link", JSONPath: "contact_link", Type: "string"},
			{FlagName: "state", JSONPath: "state", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PATCH", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	campaignsUpdateCampaignCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = campaignsUpdateCampaignCmd.MarkFlagRequired("org")
	campaignsUpdateCampaignCmd.Flags().String("campaign-number", "", "The campaign number.")
	_ = campaignsUpdateCampaignCmd.MarkFlagRequired("campaign-number")
	campaignsUpdateCampaignCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	campaignsUpdateCampaignCmd.Flags().String("name", "", "The name of the campaign")
	campaignsUpdateCampaignCmd.Flags().String("description", "", "A description for the campaign")
	campaignsUpdateCampaignCmd.Flags().String("managers", "", "The logins of the users to set as the campaign managers. At this time, only a single manager can be supplied.")
	campaignsUpdateCampaignCmd.Flags().String("team-managers", "", "The slugs of the teams to set as the campaign managers.")
	campaignsUpdateCampaignCmd.Flags().String("ends-at", "", "The end date and time of the campaign, in ISO 8601 format':' YYYY-MM-DDTHH:MM:SSZ.")
	campaignsUpdateCampaignCmd.Flags().String("contact-link", "", "The contact link of the campaign. Must be a URI.")
	campaignsUpdateCampaignCmd.Flags().String("state", "", "Indicates whether a campaign is open or closed")
	_ = campaignsUpdateCampaignCmd.RegisterFlagCompletionFunc("state", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"open", "closed"}, cobra.ShellCompDirectiveNoFileComp
	})
}
