// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var checksListForRefCmd = &cobra.Command{
	Use:   "list-for-ref",
	Short: "List check runs for a Git reference",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/commits/{ref}/check-runs"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		refVal, _ := cmd.Flags().GetString("ref")
		if refVal == "" {
			return fmt.Errorf("required flag --%s not set", "ref")
		}
		path = strings.Replace(path, "{ref}", refVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("check-name"); v != "" {
			params["check_name"] = v
		}
		if v, _ := cmd.Flags().GetString("status"); v != "" {
			params["status"] = v
		}
		if v, _ := cmd.Flags().GetString("filter"); v != "" {
			params["filter"] = v
		}
		if v, _ := cmd.Flags().GetString("per-page"); v != "" {
			params["per_page"] = v
		}
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		if v, _ := cmd.Flags().GetString("app-id"); v != "" {
			params["app_id"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	checksListForRefCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = checksListForRefCmd.MarkFlagRequired("owner")
	checksListForRefCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = checksListForRefCmd.MarkFlagRequired("repo")
	checksListForRefCmd.Flags().String("ref", "", "The commit reference. Can be a commit SHA, branch name (`heads/BRANCH_NAME`), or tag name (`tags/TAG_NAME`). For more information, see \"[Git References](https://git-scm.com/book/en/v2/Git-Internals-Git-References)\" in the Git documentation.")
	_ = checksListForRefCmd.MarkFlagRequired("ref")
	checksListForRefCmd.Flags().String("check-name", "", "Returns check runs with the specified `name`.")
	checksListForRefCmd.Flags().String("status", "", "Returns check runs with the specified `status`.")
	_ = checksListForRefCmd.RegisterFlagCompletionFunc("status", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"queued", "in_progress", "completed"}, cobra.ShellCompDirectiveNoFileComp
	})
	checksListForRefCmd.Flags().String("filter", "latest", "Filters check runs by their `completed_at` timestamp. `latest` returns the most recent check runs.")
	_ = checksListForRefCmd.RegisterFlagCompletionFunc("filter", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"latest", "all"}, cobra.ShellCompDirectiveNoFileComp
	})
	checksListForRefCmd.Flags().String("per-page", "30", "The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	checksListForRefCmd.Flags().String("page", "1", "The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	checksListForRefCmd.Flags().String("app-id", "", "")
}
