// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var checksGetCmd = &cobra.Command{
	Use:   "get",
	Short: "Get a check run",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/check-runs/{check_run_id}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		checkRunIdVal, _ := cmd.Flags().GetString("check-run-id")
		if checkRunIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "check-run-id")
		}
		path = strings.Replace(path, "{check_run_id}", checkRunIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	checksGetCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = checksGetCmd.MarkFlagRequired("owner")
	checksGetCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = checksGetCmd.MarkFlagRequired("repo")
	checksGetCmd.Flags().String("check-run-id", "", "The unique identifier of the check run.")
	_ = checksGetCmd.MarkFlagRequired("check-run-id")
}
