// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var classroomListAcceptedAssignmentsForAnAssignmentCmd = &cobra.Command{
	Use:   "list-accepted-assignments-for-an-assignment",
	Short: "List accepted assignments for an assignment",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/assignments/{assignment_id}/accepted_assignments"
		assignmentIdVal, _ := cmd.Flags().GetString("assignment-id")
		if assignmentIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "assignment-id")
		}
		path = strings.Replace(path, "{assignment_id}", assignmentIdVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		if v, _ := cmd.Flags().GetString("per-page"); v != "" {
			params["per_page"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	classroomListAcceptedAssignmentsForAnAssignmentCmd.Flags().String("assignment-id", "", "The unique identifier of the classroom assignment.")
	_ = classroomListAcceptedAssignmentsForAnAssignmentCmd.MarkFlagRequired("assignment-id")
	classroomListAcceptedAssignmentsForAnAssignmentCmd.Flags().String("page", "1", "The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	classroomListAcceptedAssignmentsForAnAssignmentCmd.Flags().String("per-page", "30", "The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
}
