// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var classroomGetAClassroomCmd = &cobra.Command{
	Use:   "get-a-classroom",
	Short: "Get a classroom",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/classrooms/{classroom_id}"
		classroomIdVal, _ := cmd.Flags().GetString("classroom-id")
		if classroomIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "classroom-id")
		}
		path = strings.Replace(path, "{classroom_id}", classroomIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	classroomGetAClassroomCmd.Flags().String("classroom-id", "", "The unique identifier of the classroom.")
	_ = classroomGetAClassroomCmd.MarkFlagRequired("classroom-id")
}
