// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var codeScanningGetCodeqlDatabaseCmd = &cobra.Command{
	Use:   "get-codeql-database",
	Short: "Get a CodeQL database for a repository",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/code-scanning/codeql/databases/{language}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		languageVal, _ := cmd.Flags().GetString("language")
		if languageVal == "" {
			return fmt.Errorf("required flag --%s not set", "language")
		}
		path = strings.Replace(path, "{language}", languageVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	codeScanningGetCodeqlDatabaseCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = codeScanningGetCodeqlDatabaseCmd.MarkFlagRequired("owner")
	codeScanningGetCodeqlDatabaseCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = codeScanningGetCodeqlDatabaseCmd.MarkFlagRequired("repo")
	codeScanningGetCodeqlDatabaseCmd.Flags().String("language", "", "The language of the CodeQL database.")
	_ = codeScanningGetCodeqlDatabaseCmd.MarkFlagRequired("language")
}
