// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var codeSecurityGetRepositoriesForEnterpriseConfigurationCmd = &cobra.Command{
	Use:   "get-repositories-for-enterprise-configuration",
	Short: "Get repositories associated with an enterprise code security configuration",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/enterprises/{enterprise}/code-security/configurations/{configuration_id}/repositories"
		enterpriseVal, _ := cmd.Flags().GetString("enterprise")
		if enterpriseVal == "" {
			return fmt.Errorf("required flag --%s not set", "enterprise")
		}
		path = strings.Replace(path, "{enterprise}", enterpriseVal, 1)
		configurationIdVal, _ := cmd.Flags().GetString("configuration-id")
		if configurationIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "configuration-id")
		}
		path = strings.Replace(path, "{configuration_id}", configurationIdVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("per-page"); v != "" {
			params["per_page"] = v
		}
		if v, _ := cmd.Flags().GetString("before"); v != "" {
			params["before"] = v
		}
		if v, _ := cmd.Flags().GetString("after"); v != "" {
			params["after"] = v
		}
		if v, _ := cmd.Flags().GetString("status"); v != "" {
			params["status"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	codeSecurityGetRepositoriesForEnterpriseConfigurationCmd.Flags().String("enterprise", "", "The slug version of the enterprise name.")
	_ = codeSecurityGetRepositoriesForEnterpriseConfigurationCmd.MarkFlagRequired("enterprise")
	codeSecurityGetRepositoriesForEnterpriseConfigurationCmd.Flags().String("configuration-id", "", "The unique identifier of the code security configuration.")
	_ = codeSecurityGetRepositoriesForEnterpriseConfigurationCmd.MarkFlagRequired("configuration-id")
	codeSecurityGetRepositoriesForEnterpriseConfigurationCmd.Flags().String("per-page", "30", "The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	codeSecurityGetRepositoriesForEnterpriseConfigurationCmd.Flags().String("before", "", "A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results before this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	codeSecurityGetRepositoriesForEnterpriseConfigurationCmd.Flags().String("after", "", "A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results after this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	codeSecurityGetRepositoriesForEnterpriseConfigurationCmd.Flags().String("status", "all", "A comma-separated list of statuses. If specified, only repositories with these attachment statuses will be returned. Can be: `all`, `attached`, `attaching`, `removed`, `enforced`, `failed`, `updating`, `removed_by_enterprise`")
}
