// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var codespacesCheckPermissionsForDevcontainerCmd = &cobra.Command{
	Use:   "check-permissions-for-devcontainer",
	Short: "Check if permissions defined by a devcontainer have been accepted by the authenticated user",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/codespaces/permissions_check"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("ref"); v != "" {
			params["ref"] = v
		}
		if v, _ := cmd.Flags().GetString("devcontainer-path"); v != "" {
			params["devcontainer_path"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	codespacesCheckPermissionsForDevcontainerCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = codespacesCheckPermissionsForDevcontainerCmd.MarkFlagRequired("owner")
	codespacesCheckPermissionsForDevcontainerCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = codespacesCheckPermissionsForDevcontainerCmd.MarkFlagRequired("repo")
	codespacesCheckPermissionsForDevcontainerCmd.Flags().String("ref", "", "The git reference that points to the location of the devcontainer configuration to use for the permission check. The value of `ref` will typically be a branch name (`heads/BRANCH_NAME`). For more information, see \"[Git References](https://git-scm.com/book/en/v2/Git-Internals-Git-References)\" in the Git documentation.")
	_ = codespacesCheckPermissionsForDevcontainerCmd.MarkFlagRequired("ref")
	codespacesCheckPermissionsForDevcontainerCmd.Flags().String("devcontainer-path", "", "Path to the devcontainer.json configuration to use for the permission check.")
	_ = codespacesCheckPermissionsForDevcontainerCmd.MarkFlagRequired("devcontainer-path")
}
