// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var codeSecurityGetConfigurationCmd = &cobra.Command{
	Use:   "get-configuration",
	Short: "Get a code security configuration",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/code-security/configurations/{configuration_id}"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		configurationIdVal, _ := cmd.Flags().GetString("configuration-id")
		if configurationIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "configuration-id")
		}
		path = strings.Replace(path, "{configuration_id}", configurationIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	codeSecurityGetConfigurationCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = codeSecurityGetConfigurationCmd.MarkFlagRequired("org")
	codeSecurityGetConfigurationCmd.Flags().String("configuration-id", "", "The unique identifier of the code security configuration.")
	_ = codeSecurityGetConfigurationCmd.MarkFlagRequired("configuration-id")
}
