// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var codespacesGetRepoSecretCmd = &cobra.Command{
	Use:   "get-repo-secret",
	Short: "Get a repository secret",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/codespaces/secrets/{secret_name}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		secretNameVal, _ := cmd.Flags().GetString("secret-name")
		if secretNameVal == "" {
			return fmt.Errorf("required flag --%s not set", "secret-name")
		}
		path = strings.Replace(path, "{secret_name}", secretNameVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	codespacesGetRepoSecretCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = codespacesGetRepoSecretCmd.MarkFlagRequired("owner")
	codespacesGetRepoSecretCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = codespacesGetRepoSecretCmd.MarkFlagRequired("repo")
	codespacesGetRepoSecretCmd.Flags().String("secret-name", "", "The name of the secret.")
	_ = codespacesGetRepoSecretCmd.MarkFlagRequired("secret-name")
}
