// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var codespacesCreateWithRepoForAuthenticatedUserCmd = &cobra.Command{
	Use:   "create-with-repo-for-authenticated-user",
	Short: "Create a codespace in a repository",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/codespaces"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "ref", JSONPath: "ref", Type: "string"},
			{FlagName: "location", JSONPath: "location", Type: "string"},
			{FlagName: "geo", JSONPath: "geo", Type: "string"},
			{FlagName: "client-ip", JSONPath: "client_ip", Type: "string"},
			{FlagName: "machine", JSONPath: "machine", Type: "string"},
			{FlagName: "devcontainer-path", JSONPath: "devcontainer_path", Type: "string"},
			{FlagName: "multi-repo-permissions-opt-out", JSONPath: "multi_repo_permissions_opt_out", Type: "boolean"},
			{FlagName: "working-directory", JSONPath: "working_directory", Type: "string"},
			{FlagName: "idle-timeout-minutes", JSONPath: "idle_timeout_minutes", Type: "integer"},
			{FlagName: "display-name", JSONPath: "display_name", Type: "string"},
			{FlagName: "retention-period-minutes", JSONPath: "retention_period_minutes", Type: "integer"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	codespacesCreateWithRepoForAuthenticatedUserCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = codespacesCreateWithRepoForAuthenticatedUserCmd.MarkFlagRequired("owner")
	codespacesCreateWithRepoForAuthenticatedUserCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = codespacesCreateWithRepoForAuthenticatedUserCmd.MarkFlagRequired("repo")
	codespacesCreateWithRepoForAuthenticatedUserCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	codespacesCreateWithRepoForAuthenticatedUserCmd.Flags().String("ref", "", "Git ref (typically a branch name) for this codespace")
	codespacesCreateWithRepoForAuthenticatedUserCmd.Flags().String("location", "", "The requested location for a new codespace. Best efforts are made to respect this upon creation. Assigned by IP if not provided.")
	codespacesCreateWithRepoForAuthenticatedUserCmd.Flags().String("geo", "", "The geographic area for this codespace. If not specified, the value is assigned by IP. This property replaces `location`, which is closing down.")
	_ = codespacesCreateWithRepoForAuthenticatedUserCmd.RegisterFlagCompletionFunc("geo", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"EuropeWest", "SoutheastAsia", "UsEast", "UsWest"}, cobra.ShellCompDirectiveNoFileComp
	})
	codespacesCreateWithRepoForAuthenticatedUserCmd.Flags().String("client-ip", "", "IP for location auto-detection when proxying a request")
	codespacesCreateWithRepoForAuthenticatedUserCmd.Flags().String("machine", "", "Machine type to use for this codespace")
	codespacesCreateWithRepoForAuthenticatedUserCmd.Flags().String("devcontainer-path", "", "Path to devcontainer.json config to use for this codespace")
	codespacesCreateWithRepoForAuthenticatedUserCmd.Flags().String("multi-repo-permissions-opt-out", "", "Whether to authorize requested permissions from devcontainer.json")
	codespacesCreateWithRepoForAuthenticatedUserCmd.Flags().String("working-directory", "", "Working directory for this codespace")
	codespacesCreateWithRepoForAuthenticatedUserCmd.Flags().String("idle-timeout-minutes", "", "Time in minutes before codespace stops from inactivity")
	codespacesCreateWithRepoForAuthenticatedUserCmd.Flags().String("display-name", "", "Display name for this codespace")
	codespacesCreateWithRepoForAuthenticatedUserCmd.Flags().String("retention-period-minutes", "", "Duration in minutes after codespace has gone idle in which it will be deleted. Must be integer minutes between 0 and 43200 (30 days).")
}
