// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var codeScanningUpdateAlertCmd = &cobra.Command{
	Use:   "update-alert",
	Short: "Update a code scanning alert",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		alertNumberVal, _ := cmd.Flags().GetString("alert-number")
		if alertNumberVal == "" {
			return fmt.Errorf("required flag --%s not set", "alert-number")
		}
		path = strings.Replace(path, "{alert_number}", alertNumberVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "state", JSONPath: "state", Type: "string"},
			{FlagName: "dismissed-reason", JSONPath: "dismissed_reason", Type: "string"},
			{FlagName: "dismissed-comment", JSONPath: "dismissed_comment", Type: "string"},
			{FlagName: "create-request", JSONPath: "create_request", Type: "boolean"},
			{FlagName: "assignees", JSONPath: "assignees", Type: "array"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PATCH", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	codeScanningUpdateAlertCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = codeScanningUpdateAlertCmd.MarkFlagRequired("owner")
	codeScanningUpdateAlertCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = codeScanningUpdateAlertCmd.MarkFlagRequired("repo")
	codeScanningUpdateAlertCmd.Flags().String("alert-number", "", "The number that identifies an alert. You can find this at the end of the URL for a code scanning alert within GitHub, and in the `number` field in the response from the `GET /repos/{owner}/{repo}/code-scanning/alerts` operation.")
	_ = codeScanningUpdateAlertCmd.MarkFlagRequired("alert-number")
	codeScanningUpdateAlertCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	codeScanningUpdateAlertCmd.Flags().String("state", "", "Sets the state of the code scanning alert. You must provide `dismissed_reason` when you set the state to `dismissed`.")
	_ = codeScanningUpdateAlertCmd.RegisterFlagCompletionFunc("state", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"open", "dismissed"}, cobra.ShellCompDirectiveNoFileComp
	})
	codeScanningUpdateAlertCmd.Flags().String("dismissed-reason", "", "**Required when the state is dismissed.** The reason for dismissing or closing the alert.")
	_ = codeScanningUpdateAlertCmd.RegisterFlagCompletionFunc("dismissed-reason", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"false positive", "won't fix", "used in tests"}, cobra.ShellCompDirectiveNoFileComp
	})
	codeScanningUpdateAlertCmd.Flags().String("dismissed-comment", "", "The dismissal comment associated with the dismissal of the alert.")
	codeScanningUpdateAlertCmd.Flags().String("create-request", "", "If `true`, attempt to create an alert dismissal request.")
	codeScanningUpdateAlertCmd.Flags().String("assignees", "", "The list of users to assign to the code scanning alert. An empty array unassigns all previous assignees from the alert.")
}
