// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var codespacesListRepositoriesForSecretForAuthenticatedUserCmd = &cobra.Command{
	Use:   "list-repositories-for-secret-for-authenticated-user",
	Short: "List selected repositories for a user secret",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/user/codespaces/secrets/{secret_name}/repositories"
		secretNameVal, _ := cmd.Flags().GetString("secret-name")
		if secretNameVal == "" {
			return fmt.Errorf("required flag --%s not set", "secret-name")
		}
		path = strings.Replace(path, "{secret_name}", secretNameVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	codespacesListRepositoriesForSecretForAuthenticatedUserCmd.Flags().String("secret-name", "", "The name of the secret.")
	_ = codespacesListRepositoriesForSecretForAuthenticatedUserCmd.MarkFlagRequired("secret-name")
}
