// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var codeSecurityDeleteConfigurationForEnterpriseCmd = &cobra.Command{
	Use:   "delete-configuration-for-enterprise",
	Short: "Delete a code security configuration for an enterprise",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/enterprises/{enterprise}/code-security/configurations/{configuration_id}"
		enterpriseVal, _ := cmd.Flags().GetString("enterprise")
		if enterpriseVal == "" {
			return fmt.Errorf("required flag --%s not set", "enterprise")
		}
		path = strings.Replace(path, "{enterprise}", enterpriseVal, 1)
		configurationIdVal, _ := cmd.Flags().GetString("configuration-id")
		if configurationIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "configuration-id")
		}
		path = strings.Replace(path, "{configuration_id}", configurationIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	codeSecurityDeleteConfigurationForEnterpriseCmd.Flags().String("enterprise", "", "The slug version of the enterprise name.")
	_ = codeSecurityDeleteConfigurationForEnterpriseCmd.MarkFlagRequired("enterprise")
	codeSecurityDeleteConfigurationForEnterpriseCmd.Flags().String("configuration-id", "", "The unique identifier of the code security configuration.")
	_ = codeSecurityDeleteConfigurationForEnterpriseCmd.MarkFlagRequired("configuration-id")
}
