// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var codeScanningGetAnalysisCmd = &cobra.Command{
	Use:   "get-analysis",
	Short: "Get a code scanning analysis for a repository",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/code-scanning/analyses/{analysis_id}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		analysisIdVal, _ := cmd.Flags().GetString("analysis-id")
		if analysisIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "analysis-id")
		}
		path = strings.Replace(path, "{analysis_id}", analysisIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	codeScanningGetAnalysisCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = codeScanningGetAnalysisCmd.MarkFlagRequired("owner")
	codeScanningGetAnalysisCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = codeScanningGetAnalysisCmd.MarkFlagRequired("repo")
	codeScanningGetAnalysisCmd.Flags().String("analysis-id", "", "The ID of the analysis, as returned from the `GET /repos/{owner}/{repo}/code-scanning/analyses` operation.")
	_ = codeScanningGetAnalysisCmd.MarkFlagRequired("analysis-id")
}
