// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var codespacesSetRepositoriesForSecretForAuthenticatedUserCmd = &cobra.Command{
	Use:   "set-repositories-for-secret-for-authenticated-user",
	Short: "Set selected repositories for a user secret",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/user/codespaces/secrets/{secret_name}/repositories"
		secretNameVal, _ := cmd.Flags().GetString("secret-name")
		if secretNameVal == "" {
			return fmt.Errorf("required flag --%s not set", "secret-name")
		}
		path = strings.Replace(path, "{secret_name}", secretNameVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "selected-repository-ids", JSONPath: "selected_repository_ids", Type: "array"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	codespacesSetRepositoriesForSecretForAuthenticatedUserCmd.Flags().String("secret-name", "", "The name of the secret.")
	_ = codespacesSetRepositoriesForSecretForAuthenticatedUserCmd.MarkFlagRequired("secret-name")
	codespacesSetRepositoriesForSecretForAuthenticatedUserCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	codespacesSetRepositoriesForSecretForAuthenticatedUserCmd.Flags().String("selected-repository-ids", "", "An array of repository ids for which a codespace can access the secret. You can manage the list of selected repositories using the [List selected repositories for a user secret](https://docs.github.com/rest/codespaces/secrets#list-selected-repositories-for-a-user-secret), [Add a selected repository to a user secret](https://docs.github.com/rest/codespaces/secrets#add-a-selected-repository-to-a-user-secret), and [Remove a selected repository from a user secret](https://docs.github.com/rest/codespaces/secrets#remove-a-selected-repository-from-a-user-secret) endpoints.")
	_ = codespacesSetRepositoriesForSecretForAuthenticatedUserCmd.MarkFlagRequired("selected-repository-ids")
}
