// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var codeScanningListAlertsForOrgCmd = &cobra.Command{
	Use:   "list-alerts-for-org",
	Short: "List code scanning alerts for an organization",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/code-scanning/alerts"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("tool-name"); v != "" {
			params["tool_name"] = v
		}
		if v, _ := cmd.Flags().GetString("tool-guid"); v != "" {
			params["tool_guid"] = v
		}
		if v, _ := cmd.Flags().GetString("before"); v != "" {
			params["before"] = v
		}
		if v, _ := cmd.Flags().GetString("after"); v != "" {
			params["after"] = v
		}
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		if v, _ := cmd.Flags().GetString("per-page"); v != "" {
			params["per_page"] = v
		}
		if v, _ := cmd.Flags().GetString("direction"); v != "" {
			params["direction"] = v
		}
		if v, _ := cmd.Flags().GetString("state"); v != "" {
			params["state"] = v
		}
		if v, _ := cmd.Flags().GetString("sort"); v != "" {
			params["sort"] = v
		}
		if v, _ := cmd.Flags().GetString("severity"); v != "" {
			params["severity"] = v
		}
		if v, _ := cmd.Flags().GetString("assignees"); v != "" {
			params["assignees"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	codeScanningListAlertsForOrgCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = codeScanningListAlertsForOrgCmd.MarkFlagRequired("org")
	codeScanningListAlertsForOrgCmd.Flags().String("tool-name", "", "The name of a code scanning tool. Only results by this tool will be listed. You can specify the tool by using either `tool_name` or `tool_guid`, but not both.")
	codeScanningListAlertsForOrgCmd.Flags().String("tool-guid", "", "The GUID of a code scanning tool. Only results by this tool will be listed. Note that some code scanning tools may not include a GUID in their analysis data. You can specify the tool by using either `tool_guid` or `tool_name`, but not both.")
	codeScanningListAlertsForOrgCmd.Flags().String("before", "", "A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results before this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	codeScanningListAlertsForOrgCmd.Flags().String("after", "", "A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results after this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	codeScanningListAlertsForOrgCmd.Flags().String("page", "1", "The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	codeScanningListAlertsForOrgCmd.Flags().String("per-page", "30", "The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	codeScanningListAlertsForOrgCmd.Flags().String("direction", "desc", "The direction to sort the results by.")
	_ = codeScanningListAlertsForOrgCmd.RegisterFlagCompletionFunc("direction", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"asc", "desc"}, cobra.ShellCompDirectiveNoFileComp
	})
	codeScanningListAlertsForOrgCmd.Flags().String("state", "", "If specified, only code scanning alerts with this state will be returned.")
	_ = codeScanningListAlertsForOrgCmd.RegisterFlagCompletionFunc("state", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"open", "closed", "dismissed", "fixed"}, cobra.ShellCompDirectiveNoFileComp
	})
	codeScanningListAlertsForOrgCmd.Flags().String("sort", "created", "The property by which to sort the results.")
	_ = codeScanningListAlertsForOrgCmd.RegisterFlagCompletionFunc("sort", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"created", "updated"}, cobra.ShellCompDirectiveNoFileComp
	})
	codeScanningListAlertsForOrgCmd.Flags().String("severity", "", "If specified, only code scanning alerts with this severity will be returned.")
	_ = codeScanningListAlertsForOrgCmd.RegisterFlagCompletionFunc("severity", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"critical", "high", "medium", "low", "warning", "note", "error"}, cobra.ShellCompDirectiveNoFileComp
	})
	codeScanningListAlertsForOrgCmd.Flags().String("assignees", "", "Filter alerts by assignees. Provide a comma-separated list of user handles (e.g., `octocat` or `octocat,hubot`). Use `*` to list alerts with at least one assignee or `none` to list alerts with no assignees.")
}
