// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var codesOfConductGetConductCodeCmd = &cobra.Command{
	Use:   "get-conduct-code",
	Short: "Get a code of conduct",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/codes_of_conduct/{key}"
		keyVal, _ := cmd.Flags().GetString("key")
		if keyVal == "" {
			return fmt.Errorf("required flag --%s not set", "key")
		}
		path = strings.Replace(path, "{key}", keyVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	codesOfConductGetConductCodeCmd.Flags().String("key", "", "")
	_ = codesOfConductGetConductCodeCmd.MarkFlagRequired("key")
}
