// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var codespacesSetCodespacesAccessCmd = &cobra.Command{
	Use:   "set-codespaces-access",
	Short: "Manage access control for organization codespaces",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/codespaces/access"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "visibility", JSONPath: "visibility", Type: "string"},
			{FlagName: "selected-usernames", JSONPath: "selected_usernames", Type: "array"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	codespacesSetCodespacesAccessCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = codespacesSetCodespacesAccessCmd.MarkFlagRequired("org")
	codespacesSetCodespacesAccessCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	codespacesSetCodespacesAccessCmd.Flags().String("visibility", "", "Which users can access codespaces in the organization. `disabled` means that no users can access codespaces in the organization.")
	_ = codespacesSetCodespacesAccessCmd.RegisterFlagCompletionFunc("visibility", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"disabled", "selected_members", "all_members", "all_members_and_outside_collaborators"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = codespacesSetCodespacesAccessCmd.MarkFlagRequired("visibility")
	codespacesSetCodespacesAccessCmd.Flags().String("selected-usernames", "", "The usernames of the organization members who should have access to codespaces in the organization. Required when `visibility` is `selected_members`. The provided list of usernames will replace any existing value.")
}
