// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var codeScanningGetVariantAnalysisRepoTaskCmd = &cobra.Command{
	Use:   "get-variant-analysis-repo-task",
	Short: "Get the analysis status of a repository in a CodeQL variant analysis",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/code-scanning/codeql/variant-analyses/{codeql_variant_analysis_id}/repos/{repo_owner}/{repo_name}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		codeqlVariantAnalysisIdVal, _ := cmd.Flags().GetString("codeql-variant-analysis-id")
		if codeqlVariantAnalysisIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "codeql-variant-analysis-id")
		}
		path = strings.Replace(path, "{codeql_variant_analysis_id}", codeqlVariantAnalysisIdVal, 1)
		repoOwnerVal, _ := cmd.Flags().GetString("repo-owner")
		if repoOwnerVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo-owner")
		}
		path = strings.Replace(path, "{repo_owner}", repoOwnerVal, 1)
		repoNameVal, _ := cmd.Flags().GetString("repo-name")
		if repoNameVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo-name")
		}
		path = strings.Replace(path, "{repo_name}", repoNameVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	codeScanningGetVariantAnalysisRepoTaskCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = codeScanningGetVariantAnalysisRepoTaskCmd.MarkFlagRequired("owner")
	codeScanningGetVariantAnalysisRepoTaskCmd.Flags().String("repo", "", "The name of the controller repository.")
	_ = codeScanningGetVariantAnalysisRepoTaskCmd.MarkFlagRequired("repo")
	codeScanningGetVariantAnalysisRepoTaskCmd.Flags().String("codeql-variant-analysis-id", "", "The ID of the variant analysis.")
	_ = codeScanningGetVariantAnalysisRepoTaskCmd.MarkFlagRequired("codeql-variant-analysis-id")
	codeScanningGetVariantAnalysisRepoTaskCmd.Flags().String("repo-owner", "", "The account owner of the variant analysis repository. The name is not case sensitive.")
	_ = codeScanningGetVariantAnalysisRepoTaskCmd.MarkFlagRequired("repo-owner")
	codeScanningGetVariantAnalysisRepoTaskCmd.Flags().String("repo-name", "", "The name of the variant analysis repository.")
	_ = codeScanningGetVariantAnalysisRepoTaskCmd.MarkFlagRequired("repo-name")
}
