// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var copilotCopilotEnterpriseOneDayUsageMetricsCmd = &cobra.Command{
	Use:   "copilot-enterprise-one-day-usage-metrics",
	Short: "Get Copilot enterprise usage metrics for a specific day",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/enterprises/{enterprise}/copilot/metrics/reports/enterprise-1-day"
		enterpriseVal, _ := cmd.Flags().GetString("enterprise")
		if enterpriseVal == "" {
			return fmt.Errorf("required flag --%s not set", "enterprise")
		}
		path = strings.Replace(path, "{enterprise}", enterpriseVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("day"); v != "" {
			params["day"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	copilotCopilotEnterpriseOneDayUsageMetricsCmd.Flags().String("enterprise", "", "The slug version of the enterprise name.")
	_ = copilotCopilotEnterpriseOneDayUsageMetricsCmd.MarkFlagRequired("enterprise")
	copilotCopilotEnterpriseOneDayUsageMetricsCmd.Flags().String("day", "", "The day to request data for, in `YYYY-MM-DD` format.")
	_ = copilotCopilotEnterpriseOneDayUsageMetricsCmd.MarkFlagRequired("day")
}
