// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var copilotCopilotOrganizationUsageMetricsCmd = &cobra.Command{
	Use:   "copilot-organization-usage-metrics",
	Short: "Get Copilot organization usage metrics",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/copilot/metrics/reports/organization-28-day/latest"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	copilotCopilotOrganizationUsageMetricsCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = copilotCopilotOrganizationUsageMetricsCmd.MarkFlagRequired("org")
}
