// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var dependencyGraphDiffRangeCmd = &cobra.Command{
	Use:   "diff-range",
	Short: "Get a diff of the dependencies between commits",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/dependency-graph/compare/{basehead}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		baseheadVal, _ := cmd.Flags().GetString("basehead")
		if baseheadVal == "" {
			return fmt.Errorf("required flag --%s not set", "basehead")
		}
		path = strings.Replace(path, "{basehead}", baseheadVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("name"); v != "" {
			params["name"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	dependencyGraphDiffRangeCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = dependencyGraphDiffRangeCmd.MarkFlagRequired("owner")
	dependencyGraphDiffRangeCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = dependencyGraphDiffRangeCmd.MarkFlagRequired("repo")
	dependencyGraphDiffRangeCmd.Flags().String("basehead", "", "The base and head Git revisions to compare. The Git revisions will be resolved to commit SHAs. Named revisions will be resolved to their corresponding HEAD commits, and an appropriate merge base will be determined. This parameter expects the format `{base}...{head}`.")
	_ = dependencyGraphDiffRangeCmd.MarkFlagRequired("basehead")
	dependencyGraphDiffRangeCmd.Flags().String("name", "", "The full path, relative to the repository root, of the dependency manifest file.")
}
