// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var dependabotRepositoryAccessForOrgCmd = &cobra.Command{
	Use:   "repository-access-for-org",
	Short: "Lists the repositories Dependabot can access in an organization",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/organizations/{org}/dependabot/repository-access"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		if v, _ := cmd.Flags().GetString("per-page"); v != "" {
			params["per_page"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	dependabotRepositoryAccessForOrgCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = dependabotRepositoryAccessForOrgCmd.MarkFlagRequired("org")
	dependabotRepositoryAccessForOrgCmd.Flags().String("page", "1", "The page number of results to fetch.")
	dependabotRepositoryAccessForOrgCmd.Flags().String("per-page", "30", "Number of results per page.")
}
