// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var dependencyGraphCmd = &cobra.Command{
	Use:   "dependency-graph",
	Short: "dependency-graph operations",
}
