// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var enterpriseTeamsDeleteCmd = &cobra.Command{
	Use:   "delete",
	Short: "Delete an enterprise team",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/enterprises/{enterprise}/teams/{team_slug}"
		enterpriseVal, _ := cmd.Flags().GetString("enterprise")
		if enterpriseVal == "" {
			return fmt.Errorf("required flag --%s not set", "enterprise")
		}
		path = strings.Replace(path, "{enterprise}", enterpriseVal, 1)
		teamSlugVal, _ := cmd.Flags().GetString("team-slug")
		if teamSlugVal == "" {
			return fmt.Errorf("required flag --%s not set", "team-slug")
		}
		path = strings.Replace(path, "{team_slug}", teamSlugVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	enterpriseTeamsDeleteCmd.Flags().String("enterprise", "", "The slug version of the enterprise name.")
	_ = enterpriseTeamsDeleteCmd.MarkFlagRequired("enterprise")
	enterpriseTeamsDeleteCmd.Flags().String("team-slug", "", "The slug of the team name.")
	_ = enterpriseTeamsDeleteCmd.MarkFlagRequired("team-slug")
}
