// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var gistsListForUserCmd = &cobra.Command{
	Use:   "list-for-user",
	Short: "List gists for a user",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/users/{username}/gists"
		usernameVal, _ := cmd.Flags().GetString("username")
		if usernameVal == "" {
			return fmt.Errorf("required flag --%s not set", "username")
		}
		path = strings.Replace(path, "{username}", usernameVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("since"); v != "" {
			params["since"] = v
		}
		if v, _ := cmd.Flags().GetString("per-page"); v != "" {
			params["per_page"] = v
		}
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	gistsListForUserCmd.Flags().String("username", "", "The handle for the GitHub user account.")
	_ = gistsListForUserCmd.MarkFlagRequired("username")
	gistsListForUserCmd.Flags().String("since", "", "Only show results that were last updated after the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.")
	gistsListForUserCmd.Flags().String("per-page", "30", "The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	gistsListForUserCmd.Flags().String("page", "1", "The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
}
