// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var gistsStarCmd = &cobra.Command{
	Use:   "star",
	Short: "Star a gist",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/gists/{gist_id}/star"
		gistIdVal, _ := cmd.Flags().GetString("gist-id")
		if gistIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "gist-id")
		}
		path = strings.Replace(path, "{gist_id}", gistIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("PUT", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	gistsStarCmd.Flags().String("gist-id", "", "The unique identifier of the gist.")
	_ = gistsStarCmd.MarkFlagRequired("gist-id")
}
