// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var gistsDeleteCommentCmd = &cobra.Command{
	Use:   "delete-comment",
	Short: "Delete a gist comment",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/gists/{gist_id}/comments/{comment_id}"
		gistIdVal, _ := cmd.Flags().GetString("gist-id")
		if gistIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "gist-id")
		}
		path = strings.Replace(path, "{gist_id}", gistIdVal, 1)
		commentIdVal, _ := cmd.Flags().GetString("comment-id")
		if commentIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "comment-id")
		}
		path = strings.Replace(path, "{comment_id}", commentIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	gistsDeleteCommentCmd.Flags().String("gist-id", "", "The unique identifier of the gist.")
	_ = gistsDeleteCommentCmd.MarkFlagRequired("gist-id")
	gistsDeleteCommentCmd.Flags().String("comment-id", "", "The unique identifier of the comment.")
	_ = gistsDeleteCommentCmd.MarkFlagRequired("comment-id")
}
