// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var gitGetTreeCmd = &cobra.Command{
	Use:   "get-tree",
	Short: "Get a tree",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/git/trees/{tree_sha}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		treeShaVal, _ := cmd.Flags().GetString("tree-sha")
		if treeShaVal == "" {
			return fmt.Errorf("required flag --%s not set", "tree-sha")
		}
		path = strings.Replace(path, "{tree_sha}", treeShaVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("recursive"); v != "" {
			params["recursive"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	gitGetTreeCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = gitGetTreeCmd.MarkFlagRequired("owner")
	gitGetTreeCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = gitGetTreeCmd.MarkFlagRequired("repo")
	gitGetTreeCmd.Flags().String("tree-sha", "", "The SHA1 value or ref (branch or tag) name of the tree.")
	_ = gitGetTreeCmd.MarkFlagRequired("tree-sha")
	gitGetTreeCmd.Flags().String("recursive", "", "Setting this parameter to any value returns the objects or subtrees referenced by the tree specified in `:tree_sha`. For example, setting `recursive` to any of the following will enable returning objects or subtrees: `0`, `1`, `\"true\"`, and `\"false\"`. Omit this parameter to prevent recursively returning objects or subtrees.")
}
