// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var gitCreateTreeCmd = &cobra.Command{
	Use:   "create-tree",
	Short: "Create a tree",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/git/trees"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "tree", JSONPath: "tree", Type: "array"},
			{FlagName: "base-tree", JSONPath: "base_tree", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	gitCreateTreeCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = gitCreateTreeCmd.MarkFlagRequired("owner")
	gitCreateTreeCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = gitCreateTreeCmd.MarkFlagRequired("repo")
	gitCreateTreeCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	gitCreateTreeCmd.Flags().String("tree", "", "Objects (of `path`, `mode`, `type`, and `sha`) specifying a tree structure.")
	_ = gitCreateTreeCmd.MarkFlagRequired("tree")
	gitCreateTreeCmd.Flags().String("base-tree", "", "The SHA1 of an existing Git tree object which will be used as the base for the new tree. If provided, a new Git tree object will be created from entries in the Git tree object pointed to by `base_tree` and entries defined in the `tree` parameter. Entries defined in the `tree` parameter will overwrite items from `base_tree` with the same `path`. If you're creating new changes on a branch, then normally you'd set `base_tree` to the SHA1 of the Git tree object of the current latest commit on the branch you're working on. If not provided, GitHub will create a new Git tree object from only the entries defined in the `tree` parameter. If you create a new commit pointing to such a tree, then all files which were a part of the parent commit's tree and were not defined in the `tree` parameter will be listed as deleted by the new commit.")
}
