// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var gitGetCommitCmd = &cobra.Command{
	Use:   "get-commit",
	Short: "Get a commit object",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/git/commits/{commit_sha}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		commitShaVal, _ := cmd.Flags().GetString("commit-sha")
		if commitShaVal == "" {
			return fmt.Errorf("required flag --%s not set", "commit-sha")
		}
		path = strings.Replace(path, "{commit_sha}", commitShaVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	gitGetCommitCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = gitGetCommitCmd.MarkFlagRequired("owner")
	gitGetCommitCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = gitGetCommitCmd.MarkFlagRequired("repo")
	gitGetCommitCmd.Flags().String("commit-sha", "", "The SHA of the commit.")
	_ = gitGetCommitCmd.MarkFlagRequired("commit-sha")
}
