// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var gitignoreGetAllTemplatesCmd = &cobra.Command{
	Use:   "get-all-templates",
	Short: "Get all gitignore templates",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/gitignore/templates"

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
}
