// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var hostedComputeGetNetworkSettingsForOrgCmd = &cobra.Command{
	Use:   "get-network-settings-for-org",
	Short: "Get a hosted compute network settings resource for an organization",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/settings/network-settings/{network_settings_id}"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		networkSettingsIdVal, _ := cmd.Flags().GetString("network-settings-id")
		if networkSettingsIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "network-settings-id")
		}
		path = strings.Replace(path, "{network_settings_id}", networkSettingsIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	hostedComputeGetNetworkSettingsForOrgCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = hostedComputeGetNetworkSettingsForOrgCmd.MarkFlagRequired("org")
	hostedComputeGetNetworkSettingsForOrgCmd.Flags().String("network-settings-id", "", "Unique identifier of the hosted compute network settings.")
	_ = hostedComputeGetNetworkSettingsForOrgCmd.MarkFlagRequired("network-settings-id")
}
