// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var interactionsSetRestrictionsForAuthenticatedUserCmd = &cobra.Command{
	Use:   "set-restrictions-for-authenticated-user",
	Short: "Set interaction restrictions for your public repositories",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/user/interaction-limits"

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "limit", JSONPath: "limit", Type: "string"},
			{FlagName: "expiry", JSONPath: "expiry", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	interactionsSetRestrictionsForAuthenticatedUserCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	interactionsSetRestrictionsForAuthenticatedUserCmd.Flags().String("limit", "", "The type of GitHub user that can comment, open issues, or create pull requests while the interaction limit is in effect.")
	_ = interactionsSetRestrictionsForAuthenticatedUserCmd.RegisterFlagCompletionFunc("limit", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"existing_users", "contributors_only", "collaborators_only"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = interactionsSetRestrictionsForAuthenticatedUserCmd.MarkFlagRequired("limit")
	interactionsSetRestrictionsForAuthenticatedUserCmd.Flags().String("expiry", "", "The duration of the interaction restriction. Default: `one_day`.")
	_ = interactionsSetRestrictionsForAuthenticatedUserCmd.RegisterFlagCompletionFunc("expiry", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"one_day", "three_days", "one_week", "one_month", "six_months"}, cobra.ShellCompDirectiveNoFileComp
	})
}
