// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var interactionsSetRestrictionsForRepoCmd = &cobra.Command{
	Use:   "set-restrictions-for-repo",
	Short: "Set interaction restrictions for a repository",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/interaction-limits"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "limit", JSONPath: "limit", Type: "string"},
			{FlagName: "expiry", JSONPath: "expiry", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	interactionsSetRestrictionsForRepoCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = interactionsSetRestrictionsForRepoCmd.MarkFlagRequired("owner")
	interactionsSetRestrictionsForRepoCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = interactionsSetRestrictionsForRepoCmd.MarkFlagRequired("repo")
	interactionsSetRestrictionsForRepoCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	interactionsSetRestrictionsForRepoCmd.Flags().String("limit", "", "The type of GitHub user that can comment, open issues, or create pull requests while the interaction limit is in effect.")
	_ = interactionsSetRestrictionsForRepoCmd.RegisterFlagCompletionFunc("limit", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"existing_users", "contributors_only", "collaborators_only"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = interactionsSetRestrictionsForRepoCmd.MarkFlagRequired("limit")
	interactionsSetRestrictionsForRepoCmd.Flags().String("expiry", "", "The duration of the interaction restriction. Default: `one_day`.")
	_ = interactionsSetRestrictionsForRepoCmd.RegisterFlagCompletionFunc("expiry", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"one_day", "three_days", "one_week", "one_month", "six_months"}, cobra.ShellCompDirectiveNoFileComp
	})
}
