// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var issuesGetMilestoneCmd = &cobra.Command{
	Use:   "get-milestone",
	Short: "Get a milestone",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/milestones/{milestone_number}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		milestoneNumberVal, _ := cmd.Flags().GetString("milestone-number")
		if milestoneNumberVal == "" {
			return fmt.Errorf("required flag --%s not set", "milestone-number")
		}
		path = strings.Replace(path, "{milestone_number}", milestoneNumberVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	issuesGetMilestoneCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = issuesGetMilestoneCmd.MarkFlagRequired("owner")
	issuesGetMilestoneCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = issuesGetMilestoneCmd.MarkFlagRequired("repo")
	issuesGetMilestoneCmd.Flags().String("milestone-number", "", "The number that identifies the milestone.")
	_ = issuesGetMilestoneCmd.MarkFlagRequired("milestone-number")
}
