// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var issuesListCommentsCmd = &cobra.Command{
	Use:   "list-comments",
	Short: "List issue comments",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/issues/{issue_number}/comments"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		issueNumberVal, _ := cmd.Flags().GetString("issue-number")
		if issueNumberVal == "" {
			return fmt.Errorf("required flag --%s not set", "issue-number")
		}
		path = strings.Replace(path, "{issue_number}", issueNumberVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("since"); v != "" {
			params["since"] = v
		}
		if v, _ := cmd.Flags().GetString("per-page"); v != "" {
			params["per_page"] = v
		}
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	issuesListCommentsCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = issuesListCommentsCmd.MarkFlagRequired("owner")
	issuesListCommentsCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = issuesListCommentsCmd.MarkFlagRequired("repo")
	issuesListCommentsCmd.Flags().String("issue-number", "", "The number that identifies the issue.")
	_ = issuesListCommentsCmd.MarkFlagRequired("issue-number")
	issuesListCommentsCmd.Flags().String("since", "", "Only show results that were last updated after the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.")
	issuesListCommentsCmd.Flags().String("per-page", "30", "The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	issuesListCommentsCmd.Flags().String("page", "1", "The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
}
