// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var issuesUnlockCmd = &cobra.Command{
	Use:   "unlock",
	Short: "Unlock an issue",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/issues/{issue_number}/lock"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		issueNumberVal, _ := cmd.Flags().GetString("issue-number")
		if issueNumberVal == "" {
			return fmt.Errorf("required flag --%s not set", "issue-number")
		}
		path = strings.Replace(path, "{issue_number}", issueNumberVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	issuesUnlockCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = issuesUnlockCmd.MarkFlagRequired("owner")
	issuesUnlockCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = issuesUnlockCmd.MarkFlagRequired("repo")
	issuesUnlockCmd.Flags().String("issue-number", "", "The number that identifies the issue.")
	_ = issuesUnlockCmd.MarkFlagRequired("issue-number")
}
