// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var issuesListMilestonesCmd = &cobra.Command{
	Use:   "list-milestones",
	Short: "List milestones",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/milestones"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("state"); v != "" {
			params["state"] = v
		}
		if v, _ := cmd.Flags().GetString("sort"); v != "" {
			params["sort"] = v
		}
		if v, _ := cmd.Flags().GetString("direction"); v != "" {
			params["direction"] = v
		}
		if v, _ := cmd.Flags().GetString("per-page"); v != "" {
			params["per_page"] = v
		}
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	issuesListMilestonesCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = issuesListMilestonesCmd.MarkFlagRequired("owner")
	issuesListMilestonesCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = issuesListMilestonesCmd.MarkFlagRequired("repo")
	issuesListMilestonesCmd.Flags().String("state", "open", "The state of the milestone. Either `open`, `closed`, or `all`.")
	_ = issuesListMilestonesCmd.RegisterFlagCompletionFunc("state", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"open", "closed", "all"}, cobra.ShellCompDirectiveNoFileComp
	})
	issuesListMilestonesCmd.Flags().String("sort", "due_on", "What to sort results by. Either `due_on` or `completeness`.")
	_ = issuesListMilestonesCmd.RegisterFlagCompletionFunc("sort", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"due_on", "completeness"}, cobra.ShellCompDirectiveNoFileComp
	})
	issuesListMilestonesCmd.Flags().String("direction", "asc", "The direction of the sort. Either `asc` or `desc`.")
	_ = issuesListMilestonesCmd.RegisterFlagCompletionFunc("direction", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"asc", "desc"}, cobra.ShellCompDirectiveNoFileComp
	})
	issuesListMilestonesCmd.Flags().String("per-page", "30", "The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	issuesListMilestonesCmd.Flags().String("page", "1", "The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
}
