// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var issuesLockCmd = &cobra.Command{
	Use:   "lock",
	Short: "Lock an issue",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/issues/{issue_number}/lock"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		issueNumberVal, _ := cmd.Flags().GetString("issue-number")
		if issueNumberVal == "" {
			return fmt.Errorf("required flag --%s not set", "issue-number")
		}
		path = strings.Replace(path, "{issue_number}", issueNumberVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "lock-reason", JSONPath: "lock_reason", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	issuesLockCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = issuesLockCmd.MarkFlagRequired("owner")
	issuesLockCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = issuesLockCmd.MarkFlagRequired("repo")
	issuesLockCmd.Flags().String("issue-number", "", "The number that identifies the issue.")
	_ = issuesLockCmd.MarkFlagRequired("issue-number")
	issuesLockCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	issuesLockCmd.Flags().String("lock-reason", "", "The reason for locking the issue or pull request conversation. Lock will fail if you don't use one of these reasons: * `off-topic` * `too heated` * `resolved` * `spam`")
	_ = issuesLockCmd.RegisterFlagCompletionFunc("lock-reason", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"off-topic", "too heated", "resolved", "spam"}, cobra.ShellCompDirectiveNoFileComp
	})
}
