// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var issuesCheckUserCanBeAssignedCmd = &cobra.Command{
	Use:   "check-user-can-be-assigned",
	Short: "Check if a user can be assigned",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/assignees/{assignee}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		assigneeVal, _ := cmd.Flags().GetString("assignee")
		if assigneeVal == "" {
			return fmt.Errorf("required flag --%s not set", "assignee")
		}
		path = strings.Replace(path, "{assignee}", assigneeVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	issuesCheckUserCanBeAssignedCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = issuesCheckUserCanBeAssignedCmd.MarkFlagRequired("owner")
	issuesCheckUserCanBeAssignedCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = issuesCheckUserCanBeAssignedCmd.MarkFlagRequired("repo")
	issuesCheckUserCanBeAssignedCmd.Flags().String("assignee", "", "")
	_ = issuesCheckUserCanBeAssignedCmd.MarkFlagRequired("assignee")
}
