// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var licensesGetCmd = &cobra.Command{
	Use:   "get",
	Short: "Get a license",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/licenses/{license}"
		licenseVal, _ := cmd.Flags().GetString("license")
		if licenseVal == "" {
			return fmt.Errorf("required flag --%s not set", "license")
		}
		path = strings.Replace(path, "{license}", licenseVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	licensesGetCmd.Flags().String("license", "", "")
	_ = licensesGetCmd.MarkFlagRequired("license")
}
