// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var metaGetOctocatCmd = &cobra.Command{
	Use:   "get-octocat",
	Short: "Get Octocat",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/octocat"

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("s"); v != "" {
			params["s"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	metaGetOctocatCmd.Flags().String("s", "", "The words to show in Octocat's speech bubble")
}
