// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var migrationsStartForOrgCmd = &cobra.Command{
	Use:   "start-for-org",
	Short: "Start an organization migration",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/migrations"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "repositories", JSONPath: "repositories", Type: "array"},
			{FlagName: "lock-repositories", JSONPath: "lock_repositories", Type: "boolean"},
			{FlagName: "exclude-metadata", JSONPath: "exclude_metadata", Type: "boolean"},
			{FlagName: "exclude-git-data", JSONPath: "exclude_git_data", Type: "boolean"},
			{FlagName: "exclude-attachments", JSONPath: "exclude_attachments", Type: "boolean"},
			{FlagName: "exclude-releases", JSONPath: "exclude_releases", Type: "boolean"},
			{FlagName: "exclude-owner-projects", JSONPath: "exclude_owner_projects", Type: "boolean"},
			{FlagName: "org-metadata-only", JSONPath: "org_metadata_only", Type: "boolean"},
			{FlagName: "exclude", JSONPath: "exclude", Type: "array"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	migrationsStartForOrgCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = migrationsStartForOrgCmd.MarkFlagRequired("org")
	migrationsStartForOrgCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	migrationsStartForOrgCmd.Flags().String("repositories", "", "A list of arrays indicating which repositories should be migrated.")
	_ = migrationsStartForOrgCmd.MarkFlagRequired("repositories")
	migrationsStartForOrgCmd.Flags().String("lock-repositories", "false", "Indicates whether repositories should be locked (to prevent manipulation) while migrating data.")
	migrationsStartForOrgCmd.Flags().String("exclude-metadata", "false", "Indicates whether metadata should be excluded and only git source should be included for the migration.")
	migrationsStartForOrgCmd.Flags().String("exclude-git-data", "false", "Indicates whether the repository git data should be excluded from the migration.")
	migrationsStartForOrgCmd.Flags().String("exclude-attachments", "false", "Indicates whether attachments should be excluded from the migration (to reduce migration archive file size).")
	migrationsStartForOrgCmd.Flags().String("exclude-releases", "false", "Indicates whether releases should be excluded from the migration (to reduce migration archive file size).")
	migrationsStartForOrgCmd.Flags().String("exclude-owner-projects", "false", "Indicates whether projects owned by the organization or users should be excluded. from the migration.")
	migrationsStartForOrgCmd.Flags().String("org-metadata-only", "false", "Indicates whether this should only include organization metadata (repositories array should be empty and will ignore other flags).")
	migrationsStartForOrgCmd.Flags().String("exclude", "", "Exclude related items from being returned in the response in order to improve performance of the request.")
}
