// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var migrationsSetLfsPreferenceCmd = &cobra.Command{
	Use:   "set-lfs-preference",
	Short: "Update Git LFS preference",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/import/lfs"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "use-lfs", JSONPath: "use_lfs", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PATCH", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	migrationsSetLfsPreferenceCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = migrationsSetLfsPreferenceCmd.MarkFlagRequired("owner")
	migrationsSetLfsPreferenceCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = migrationsSetLfsPreferenceCmd.MarkFlagRequired("repo")
	migrationsSetLfsPreferenceCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	migrationsSetLfsPreferenceCmd.Flags().String("use-lfs", "", "Whether to store large files during the import. `opt_in` means large files will be stored using Git LFS. `opt_out` means large files will be removed during the import.")
	_ = migrationsSetLfsPreferenceCmd.RegisterFlagCompletionFunc("use-lfs", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"opt_in", "opt_out"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = migrationsSetLfsPreferenceCmd.MarkFlagRequired("use-lfs")
}
