// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var oidcCreateOidcCustomPropertyInclusionForEnterpriseCmd = &cobra.Command{
	Use:   "create-oidc-custom-property-inclusion-for-enterprise",
	Short: "Create an OIDC custom property inclusion for an enterprise",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/enterprises/{enterprise}/actions/oidc/customization/properties/repo"
		enterpriseVal, _ := cmd.Flags().GetString("enterprise")
		if enterpriseVal == "" {
			return fmt.Errorf("required flag --%s not set", "enterprise")
		}
		path = strings.Replace(path, "{enterprise}", enterpriseVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "custom-property-name", JSONPath: "custom_property_name", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	oidcCreateOidcCustomPropertyInclusionForEnterpriseCmd.Flags().String("enterprise", "", "The slug version of the enterprise name.")
	_ = oidcCreateOidcCustomPropertyInclusionForEnterpriseCmd.MarkFlagRequired("enterprise")
	oidcCreateOidcCustomPropertyInclusionForEnterpriseCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	oidcCreateOidcCustomPropertyInclusionForEnterpriseCmd.Flags().String("custom-property-name", "", "The name of the custom property to include in the OIDC token")
	_ = oidcCreateOidcCustomPropertyInclusionForEnterpriseCmd.MarkFlagRequired("custom-property-name")
}
