// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var oidcDeleteOidcCustomPropertyInclusionForOrgCmd = &cobra.Command{
	Use:   "delete-oidc-custom-property-inclusion-for-org",
	Short: "Delete an OIDC custom property inclusion for an organization",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/actions/oidc/customization/properties/repo/{custom_property_name}"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		customPropertyNameVal, _ := cmd.Flags().GetString("custom-property-name")
		if customPropertyNameVal == "" {
			return fmt.Errorf("required flag --%s not set", "custom-property-name")
		}
		path = strings.Replace(path, "{custom_property_name}", customPropertyNameVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	oidcDeleteOidcCustomPropertyInclusionForOrgCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = oidcDeleteOidcCustomPropertyInclusionForOrgCmd.MarkFlagRequired("org")
	oidcDeleteOidcCustomPropertyInclusionForOrgCmd.Flags().String("custom-property-name", "", "The name of the custom property to remove from OIDC token inclusion")
	_ = oidcDeleteOidcCustomPropertyInclusionForOrgCmd.MarkFlagRequired("custom-property-name")
}
