// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var oidcCreateOidcCustomPropertyInclusionForOrgCmd = &cobra.Command{
	Use:   "create-oidc-custom-property-inclusion-for-org",
	Short: "Create an OIDC custom property inclusion for an organization",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/actions/oidc/customization/properties/repo"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "custom-property-name", JSONPath: "custom_property_name", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	oidcCreateOidcCustomPropertyInclusionForOrgCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = oidcCreateOidcCustomPropertyInclusionForOrgCmd.MarkFlagRequired("org")
	oidcCreateOidcCustomPropertyInclusionForOrgCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	oidcCreateOidcCustomPropertyInclusionForOrgCmd.Flags().String("custom-property-name", "", "The name of the custom property to include in the OIDC token")
	_ = oidcCreateOidcCustomPropertyInclusionForOrgCmd.MarkFlagRequired("custom-property-name")
}
