// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var oidcDeleteOidcCustomPropertyInclusionForEnterpriseCmd = &cobra.Command{
	Use:   "delete-oidc-custom-property-inclusion-for-enterprise",
	Short: "Delete an OIDC custom property inclusion for an enterprise",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/enterprises/{enterprise}/actions/oidc/customization/properties/repo/{custom_property_name}"
		enterpriseVal, _ := cmd.Flags().GetString("enterprise")
		if enterpriseVal == "" {
			return fmt.Errorf("required flag --%s not set", "enterprise")
		}
		path = strings.Replace(path, "{enterprise}", enterpriseVal, 1)
		customPropertyNameVal, _ := cmd.Flags().GetString("custom-property-name")
		if customPropertyNameVal == "" {
			return fmt.Errorf("required flag --%s not set", "custom-property-name")
		}
		path = strings.Replace(path, "{custom_property_name}", customPropertyNameVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	oidcDeleteOidcCustomPropertyInclusionForEnterpriseCmd.Flags().String("enterprise", "", "The slug version of the enterprise name.")
	_ = oidcDeleteOidcCustomPropertyInclusionForEnterpriseCmd.MarkFlagRequired("enterprise")
	oidcDeleteOidcCustomPropertyInclusionForEnterpriseCmd.Flags().String("custom-property-name", "", "The name of the custom property to remove from OIDC token inclusion")
	_ = oidcDeleteOidcCustomPropertyInclusionForEnterpriseCmd.MarkFlagRequired("custom-property-name")
}
