// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var oidcUpdateOidcCustomSubTemplateForOrgCmd = &cobra.Command{
	Use:   "update-oidc-custom-sub-template-for-org",
	Short: "Set the customization template for an OIDC subject claim for an organization",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/actions/oidc/customization/sub"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "include-claim-keys", JSONPath: "include_claim_keys", Type: "array"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	oidcUpdateOidcCustomSubTemplateForOrgCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = oidcUpdateOidcCustomSubTemplateForOrgCmd.MarkFlagRequired("org")
	oidcUpdateOidcCustomSubTemplateForOrgCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	oidcUpdateOidcCustomSubTemplateForOrgCmd.Flags().String("include-claim-keys", "", "Array of unique strings. Each claim key can only contain alphanumeric characters and underscores.")
	_ = oidcUpdateOidcCustomSubTemplateForOrgCmd.MarkFlagRequired("include-claim-keys")
}
