// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var orgsApiInsightsGetSummaryStatsCmd = &cobra.Command{
	Use:   "api-insights-get-summary-stats",
	Short: "Get summary stats",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/insights/api/summary-stats"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("min-timestamp"); v != "" {
			params["min_timestamp"] = v
		}
		if v, _ := cmd.Flags().GetString("max-timestamp"); v != "" {
			params["max_timestamp"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	orgsApiInsightsGetSummaryStatsCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = orgsApiInsightsGetSummaryStatsCmd.MarkFlagRequired("org")
	orgsApiInsightsGetSummaryStatsCmd.Flags().String("min-timestamp", "", "The minimum timestamp to query for stats. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.")
	_ = orgsApiInsightsGetSummaryStatsCmd.MarkFlagRequired("min-timestamp")
	orgsApiInsightsGetSummaryStatsCmd.Flags().String("max-timestamp", "", "The maximum timestamp to query for stats. Defaults to the time 30 days ago. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.")
}
