// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var orgsGetOrgRulesetVersionCmd = &cobra.Command{
	Use:   "get-org-ruleset-version",
	Short: "Get organization ruleset version",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/rulesets/{ruleset_id}/history/{version_id}"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		rulesetIdVal, _ := cmd.Flags().GetString("ruleset-id")
		if rulesetIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "ruleset-id")
		}
		path = strings.Replace(path, "{ruleset_id}", rulesetIdVal, 1)
		versionIdVal, _ := cmd.Flags().GetString("version-id")
		if versionIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "version-id")
		}
		path = strings.Replace(path, "{version_id}", versionIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	orgsGetOrgRulesetVersionCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = orgsGetOrgRulesetVersionCmd.MarkFlagRequired("org")
	orgsGetOrgRulesetVersionCmd.Flags().String("ruleset-id", "", "The ID of the ruleset.")
	_ = orgsGetOrgRulesetVersionCmd.MarkFlagRequired("ruleset-id")
	orgsGetOrgRulesetVersionCmd.Flags().String("version-id", "", "The ID of the version")
	_ = orgsGetOrgRulesetVersionCmd.MarkFlagRequired("version-id")
}
