// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var orgsRevokeAllOrgRolesUserCmd = &cobra.Command{
	Use:   "revoke-all-org-roles-user",
	Short: "Remove all organization roles for a user",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/organization-roles/users/{username}"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		usernameVal, _ := cmd.Flags().GetString("username")
		if usernameVal == "" {
			return fmt.Errorf("required flag --%s not set", "username")
		}
		path = strings.Replace(path, "{username}", usernameVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	orgsRevokeAllOrgRolesUserCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = orgsRevokeAllOrgRolesUserCmd.MarkFlagRequired("org")
	orgsRevokeAllOrgRolesUserCmd.Flags().String("username", "", "The handle for the GitHub user account.")
	_ = orgsRevokeAllOrgRolesUserCmd.MarkFlagRequired("username")
}
