// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var orgsCreateIssueTypeCmd = &cobra.Command{
	Use:   "create-issue-type",
	Short: "Create issue type for an organization",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/issue-types"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "name", JSONPath: "name", Type: "string"},
			{FlagName: "is-enabled", JSONPath: "is_enabled", Type: "boolean"},
			{FlagName: "description", JSONPath: "description", Type: "string"},
			{FlagName: "color", JSONPath: "color", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	orgsCreateIssueTypeCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = orgsCreateIssueTypeCmd.MarkFlagRequired("org")
	orgsCreateIssueTypeCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	orgsCreateIssueTypeCmd.Flags().String("name", "", "Name of the issue type.")
	_ = orgsCreateIssueTypeCmd.MarkFlagRequired("name")
	orgsCreateIssueTypeCmd.Flags().String("is-enabled", "", "Whether or not the issue type is enabled at the organization level.")
	_ = orgsCreateIssueTypeCmd.MarkFlagRequired("is-enabled")
	orgsCreateIssueTypeCmd.Flags().String("description", "", "Description of the issue type.")
	orgsCreateIssueTypeCmd.Flags().String("color", "", "Color for the issue type.")
	_ = orgsCreateIssueTypeCmd.RegisterFlagCompletionFunc("color", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"gray", "blue", "green", "yellow", "orange", "red", "pink", "purple"}, cobra.ShellCompDirectiveNoFileComp
	})
}
