// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var orgsListPatGrantsCmd = &cobra.Command{
	Use:   "list-pat-grants",
	Short: "List fine-grained personal access tokens with access to organization resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/personal-access-tokens"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("per-page"); v != "" {
			params["per_page"] = v
		}
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		if v, _ := cmd.Flags().GetString("sort"); v != "" {
			params["sort"] = v
		}
		if v, _ := cmd.Flags().GetString("direction"); v != "" {
			params["direction"] = v
		}
		if v, _ := cmd.Flags().GetString("owner"); v != "" {
			params["owner"] = v
		}
		if v, _ := cmd.Flags().GetString("repository"); v != "" {
			params["repository"] = v
		}
		if v, _ := cmd.Flags().GetString("permission"); v != "" {
			params["permission"] = v
		}
		if v, _ := cmd.Flags().GetString("last-used-before"); v != "" {
			params["last_used_before"] = v
		}
		if v, _ := cmd.Flags().GetString("last-used-after"); v != "" {
			params["last_used_after"] = v
		}
		if v, _ := cmd.Flags().GetString("token-id"); v != "" {
			params["token_id"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	orgsListPatGrantsCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = orgsListPatGrantsCmd.MarkFlagRequired("org")
	orgsListPatGrantsCmd.Flags().String("per-page", "30", "The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	orgsListPatGrantsCmd.Flags().String("page", "1", "The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	orgsListPatGrantsCmd.Flags().String("sort", "created_at", "The property by which to sort the results.")
	_ = orgsListPatGrantsCmd.RegisterFlagCompletionFunc("sort", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"created_at"}, cobra.ShellCompDirectiveNoFileComp
	})
	orgsListPatGrantsCmd.Flags().String("direction", "desc", "The direction to sort the results by.")
	_ = orgsListPatGrantsCmd.RegisterFlagCompletionFunc("direction", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"asc", "desc"}, cobra.ShellCompDirectiveNoFileComp
	})
	orgsListPatGrantsCmd.Flags().String("owner", "", "A list of owner usernames to use to filter the results.")
	orgsListPatGrantsCmd.Flags().String("repository", "", "The name of the repository to use to filter the results.")
	orgsListPatGrantsCmd.Flags().String("permission", "", "The permission to use to filter the results.")
	orgsListPatGrantsCmd.Flags().String("last-used-before", "", "Only show fine-grained personal access tokens used before the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.")
	orgsListPatGrantsCmd.Flags().String("last-used-after", "", "Only show fine-grained personal access tokens used after the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.")
	orgsListPatGrantsCmd.Flags().String("token-id", "", "The ID of the token")
}
