// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var orgsDeleteAttestationsByIdCmd = &cobra.Command{
	Use:   "delete-attestations-by-id",
	Short: "Delete attestations by ID",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/attestations/{attestation_id}"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		attestationIdVal, _ := cmd.Flags().GetString("attestation-id")
		if attestationIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "attestation-id")
		}
		path = strings.Replace(path, "{attestation_id}", attestationIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	orgsDeleteAttestationsByIdCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = orgsDeleteAttestationsByIdCmd.MarkFlagRequired("org")
	orgsDeleteAttestationsByIdCmd.Flags().String("attestation-id", "", "Attestation ID")
	_ = orgsDeleteAttestationsByIdCmd.MarkFlagRequired("attestation-id")
}
