// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var orgsListPendingInvitationsCmd = &cobra.Command{
	Use:   "list-pending-invitations",
	Short: "List pending organization invitations",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/invitations"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("per-page"); v != "" {
			params["per_page"] = v
		}
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		if v, _ := cmd.Flags().GetString("role"); v != "" {
			params["role"] = v
		}
		if v, _ := cmd.Flags().GetString("invitation-source"); v != "" {
			params["invitation_source"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	orgsListPendingInvitationsCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = orgsListPendingInvitationsCmd.MarkFlagRequired("org")
	orgsListPendingInvitationsCmd.Flags().String("per-page", "30", "The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	orgsListPendingInvitationsCmd.Flags().String("page", "1", "The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	orgsListPendingInvitationsCmd.Flags().String("role", "all", "Filter invitations by their member role.")
	_ = orgsListPendingInvitationsCmd.RegisterFlagCompletionFunc("role", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"all", "admin", "direct_member", "billing_manager", "hiring_manager"}, cobra.ShellCompDirectiveNoFileComp
	})
	orgsListPendingInvitationsCmd.Flags().String("invitation-source", "all", "Filter invitations by their invitation source.")
	_ = orgsListPendingInvitationsCmd.RegisterFlagCompletionFunc("invitation-source", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"all", "member", "scim"}, cobra.ShellCompDirectiveNoFileComp
	})
}
