// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var orgsCancelInvitationCmd = &cobra.Command{
	Use:   "cancel-invitation",
	Short: "Cancel an organization invitation",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/invitations/{invitation_id}"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		invitationIdVal, _ := cmd.Flags().GetString("invitation-id")
		if invitationIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "invitation-id")
		}
		path = strings.Replace(path, "{invitation_id}", invitationIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	orgsCancelInvitationCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = orgsCancelInvitationCmd.MarkFlagRequired("org")
	orgsCancelInvitationCmd.Flags().String("invitation-id", "", "The unique identifier of the invitation.")
	_ = orgsCancelInvitationCmd.MarkFlagRequired("invitation-id")
}
