// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var orgsCustomPropertiesForReposCreateOrUpdateOrganizationDefinitionsCmd = &cobra.Command{
	Use:   "custom-properties-for-repos-create-or-update-organization-definitions",
	Short: "Create or update custom properties for an organization",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/properties/schema"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "properties", JSONPath: "properties", Type: "array"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PATCH", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	orgsCustomPropertiesForReposCreateOrUpdateOrganizationDefinitionsCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = orgsCustomPropertiesForReposCreateOrUpdateOrganizationDefinitionsCmd.MarkFlagRequired("org")
	orgsCustomPropertiesForReposCreateOrUpdateOrganizationDefinitionsCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	orgsCustomPropertiesForReposCreateOrUpdateOrganizationDefinitionsCmd.Flags().String("properties", "", "The array of custom properties to create or update.")
	_ = orgsCustomPropertiesForReposCreateOrUpdateOrganizationDefinitionsCmd.MarkFlagRequired("properties")
}
