// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var orgsApiInsightsGetTimeStatsByUserCmd = &cobra.Command{
	Use:   "api-insights-get-time-stats-by-user",
	Short: "Get time stats by user",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/insights/api/time-stats/users/{user_id}"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		userIdVal, _ := cmd.Flags().GetString("user-id")
		if userIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "user-id")
		}
		path = strings.Replace(path, "{user_id}", userIdVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("min-timestamp"); v != "" {
			params["min_timestamp"] = v
		}
		if v, _ := cmd.Flags().GetString("max-timestamp"); v != "" {
			params["max_timestamp"] = v
		}
		if v, _ := cmd.Flags().GetString("timestamp-increment"); v != "" {
			params["timestamp_increment"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	orgsApiInsightsGetTimeStatsByUserCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = orgsApiInsightsGetTimeStatsByUserCmd.MarkFlagRequired("org")
	orgsApiInsightsGetTimeStatsByUserCmd.Flags().String("user-id", "", "The ID of the user to query for stats")
	_ = orgsApiInsightsGetTimeStatsByUserCmd.MarkFlagRequired("user-id")
	orgsApiInsightsGetTimeStatsByUserCmd.Flags().String("min-timestamp", "", "The minimum timestamp to query for stats. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.")
	_ = orgsApiInsightsGetTimeStatsByUserCmd.MarkFlagRequired("min-timestamp")
	orgsApiInsightsGetTimeStatsByUserCmd.Flags().String("max-timestamp", "", "The maximum timestamp to query for stats. Defaults to the time 30 days ago. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.")
	orgsApiInsightsGetTimeStatsByUserCmd.Flags().String("timestamp-increment", "", "The increment of time used to breakdown the query results (5m, 10m, 1h, etc.)")
	_ = orgsApiInsightsGetTimeStatsByUserCmd.MarkFlagRequired("timestamp-increment")
}
