// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var orgsDisableSelectedRepositoryImmutableReleasesOrganizationCmd = &cobra.Command{
	Use:   "disable-selected-repository-immutable-releases-organization",
	Short: "Disable a selected repository for immutable releases in an organization",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/settings/immutable-releases/repositories/{repository_id}"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		repositoryIdVal, _ := cmd.Flags().GetString("repository-id")
		if repositoryIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "repository-id")
		}
		path = strings.Replace(path, "{repository_id}", repositoryIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	orgsDisableSelectedRepositoryImmutableReleasesOrganizationCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = orgsDisableSelectedRepositoryImmutableReleasesOrganizationCmd.MarkFlagRequired("org")
	orgsDisableSelectedRepositoryImmutableReleasesOrganizationCmd.Flags().String("repository-id", "", "The unique identifier of the repository.")
	_ = orgsDisableSelectedRepositoryImmutableReleasesOrganizationCmd.MarkFlagRequired("repository-id")
}
