// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var orgsListWebhookDeliveriesCmd = &cobra.Command{
	Use:   "list-webhook-deliveries",
	Short: "List deliveries for an organization webhook",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/hooks/{hook_id}/deliveries"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		hookIdVal, _ := cmd.Flags().GetString("hook-id")
		if hookIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "hook-id")
		}
		path = strings.Replace(path, "{hook_id}", hookIdVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("per-page"); v != "" {
			params["per_page"] = v
		}
		if v, _ := cmd.Flags().GetString("cursor"); v != "" {
			params["cursor"] = v
		}
		if v, _ := cmd.Flags().GetString("status"); v != "" {
			params["status"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	orgsListWebhookDeliveriesCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = orgsListWebhookDeliveriesCmd.MarkFlagRequired("org")
	orgsListWebhookDeliveriesCmd.Flags().String("hook-id", "", "The unique identifier of the hook. You can find this value in the `X-GitHub-Hook-ID` header of a webhook delivery.")
	_ = orgsListWebhookDeliveriesCmd.MarkFlagRequired("hook-id")
	orgsListWebhookDeliveriesCmd.Flags().String("per-page", "30", "The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	orgsListWebhookDeliveriesCmd.Flags().String("cursor", "", "Used for pagination: the starting delivery from which the page of deliveries is fetched. Refer to the `link` header for the next and previous page cursors.")
	orgsListWebhookDeliveriesCmd.Flags().String("status", "", "Returns webhook deliveries filtered by delivery outcome classification based on `status_code` range. A `status` of `success` returns deliveries with a `status_code` in the 200-399 range (inclusive). A `status` of `failure` returns deliveries with a `status_code` in the 400-599 range (inclusive).")
	_ = orgsListWebhookDeliveriesCmd.RegisterFlagCompletionFunc("status", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"success", "failure"}, cobra.ShellCompDirectiveNoFileComp
	})
}
