// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var orgsGetMembershipForAuthenticatedUserCmd = &cobra.Command{
	Use:   "get-membership-for-authenticated-user",
	Short: "Get an organization membership for the authenticated user",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/user/memberships/orgs/{org}"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	orgsGetMembershipForAuthenticatedUserCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = orgsGetMembershipForAuthenticatedUserCmd.MarkFlagRequired("org")
}
