// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var orgsRemoveSecurityManagerTeamCmd = &cobra.Command{
	Use:   "remove-security-manager-team",
	Short: "Remove a security manager team",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/security-managers/teams/{team_slug}"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		teamSlugVal, _ := cmd.Flags().GetString("team-slug")
		if teamSlugVal == "" {
			return fmt.Errorf("required flag --%s not set", "team-slug")
		}
		path = strings.Replace(path, "{team_slug}", teamSlugVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	orgsRemoveSecurityManagerTeamCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = orgsRemoveSecurityManagerTeamCmd.MarkFlagRequired("org")
	orgsRemoveSecurityManagerTeamCmd.Flags().String("team-slug", "", "The slug of the team name.")
	_ = orgsRemoveSecurityManagerTeamCmd.MarkFlagRequired("team-slug")
}
