// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var orgsApiInsightsGetTimeStatsByActorCmd = &cobra.Command{
	Use:   "api-insights-get-time-stats-by-actor",
	Short: "Get time stats by actor",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/insights/api/time-stats/{actor_type}/{actor_id}"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		actorTypeVal, _ := cmd.Flags().GetString("actor-type")
		if actorTypeVal == "" {
			return fmt.Errorf("required flag --%s not set", "actor-type")
		}
		path = strings.Replace(path, "{actor_type}", actorTypeVal, 1)
		actorIdVal, _ := cmd.Flags().GetString("actor-id")
		if actorIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "actor-id")
		}
		path = strings.Replace(path, "{actor_id}", actorIdVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("min-timestamp"); v != "" {
			params["min_timestamp"] = v
		}
		if v, _ := cmd.Flags().GetString("max-timestamp"); v != "" {
			params["max_timestamp"] = v
		}
		if v, _ := cmd.Flags().GetString("timestamp-increment"); v != "" {
			params["timestamp_increment"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	orgsApiInsightsGetTimeStatsByActorCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = orgsApiInsightsGetTimeStatsByActorCmd.MarkFlagRequired("org")
	orgsApiInsightsGetTimeStatsByActorCmd.Flags().String("actor-type", "", "The type of the actor")
	_ = orgsApiInsightsGetTimeStatsByActorCmd.RegisterFlagCompletionFunc("actor-type", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"installation", "classic_pat", "fine_grained_pat", "oauth_app", "github_app_user_to_server"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = orgsApiInsightsGetTimeStatsByActorCmd.MarkFlagRequired("actor-type")
	orgsApiInsightsGetTimeStatsByActorCmd.Flags().String("actor-id", "", "The ID of the actor")
	_ = orgsApiInsightsGetTimeStatsByActorCmd.MarkFlagRequired("actor-id")
	orgsApiInsightsGetTimeStatsByActorCmd.Flags().String("min-timestamp", "", "The minimum timestamp to query for stats. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.")
	_ = orgsApiInsightsGetTimeStatsByActorCmd.MarkFlagRequired("min-timestamp")
	orgsApiInsightsGetTimeStatsByActorCmd.Flags().String("max-timestamp", "", "The maximum timestamp to query for stats. Defaults to the time 30 days ago. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.")
	orgsApiInsightsGetTimeStatsByActorCmd.Flags().String("timestamp-increment", "", "The increment of time used to breakdown the query results (5m, 10m, 1h, etc.)")
	_ = orgsApiInsightsGetTimeStatsByActorCmd.MarkFlagRequired("timestamp-increment")
}
