// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var orgsGetOrgRulesetHistoryCmd = &cobra.Command{
	Use:   "get-org-ruleset-history",
	Short: "Get organization ruleset history",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/rulesets/{ruleset_id}/history"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		rulesetIdVal, _ := cmd.Flags().GetString("ruleset-id")
		if rulesetIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "ruleset-id")
		}
		path = strings.Replace(path, "{ruleset_id}", rulesetIdVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("per-page"); v != "" {
			params["per_page"] = v
		}
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	orgsGetOrgRulesetHistoryCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = orgsGetOrgRulesetHistoryCmd.MarkFlagRequired("org")
	orgsGetOrgRulesetHistoryCmd.Flags().String("per-page", "30", "The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	orgsGetOrgRulesetHistoryCmd.Flags().String("page", "1", "The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	orgsGetOrgRulesetHistoryCmd.Flags().String("ruleset-id", "", "The ID of the ruleset.")
	_ = orgsGetOrgRulesetHistoryCmd.MarkFlagRequired("ruleset-id")
}
