// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var orgsListOrgRoleUsersCmd = &cobra.Command{
	Use:   "list-org-role-users",
	Short: "List users that are assigned to an organization role",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/organization-roles/{role_id}/users"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		roleIdVal, _ := cmd.Flags().GetString("role-id")
		if roleIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "role-id")
		}
		path = strings.Replace(path, "{role_id}", roleIdVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("per-page"); v != "" {
			params["per_page"] = v
		}
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	orgsListOrgRoleUsersCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = orgsListOrgRoleUsersCmd.MarkFlagRequired("org")
	orgsListOrgRoleUsersCmd.Flags().String("role-id", "", "The unique identifier of the role.")
	_ = orgsListOrgRoleUsersCmd.MarkFlagRequired("role-id")
	orgsListOrgRoleUsersCmd.Flags().String("per-page", "30", "The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	orgsListOrgRoleUsersCmd.Flags().String("page", "1", "The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
}
