// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var packagesListDockerMigrationConflictingPackagesForAuthenticatedUserCmd = &cobra.Command{
	Use:   "list-docker-migration-conflicting-packages-for-authenticated-user",
	Short: "Get list of conflicting packages during Docker migration for authenticated-user",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/user/docker/conflicts"

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
}
