// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var packagesGetPackageForAuthenticatedUserCmd = &cobra.Command{
	Use:   "get-package-for-authenticated-user",
	Short: "Get a package for the authenticated user",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/user/packages/{package_type}/{package_name}"
		packageTypeVal, _ := cmd.Flags().GetString("package-type")
		if packageTypeVal == "" {
			return fmt.Errorf("required flag --%s not set", "package-type")
		}
		path = strings.Replace(path, "{package_type}", packageTypeVal, 1)
		packageNameVal, _ := cmd.Flags().GetString("package-name")
		if packageNameVal == "" {
			return fmt.Errorf("required flag --%s not set", "package-name")
		}
		path = strings.Replace(path, "{package_name}", packageNameVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	packagesGetPackageForAuthenticatedUserCmd.Flags().String("package-type", "", "The type of supported package. Packages in GitHub's Gradle registry have the type `maven`. Docker images pushed to GitHub's Container registry (`ghcr.io`) have the type `container`. You can use the type `docker` to find images that were pushed to GitHub's Docker registry (`docker.pkg.github.com`), even if these have now been migrated to the Container registry.")
	_ = packagesGetPackageForAuthenticatedUserCmd.RegisterFlagCompletionFunc("package-type", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"npm", "maven", "rubygems", "docker", "nuget", "container"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = packagesGetPackageForAuthenticatedUserCmd.MarkFlagRequired("package-type")
	packagesGetPackageForAuthenticatedUserCmd.Flags().String("package-name", "", "The name of the package.")
	_ = packagesGetPackageForAuthenticatedUserCmd.MarkFlagRequired("package-name")
}
