// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var packagesGetAllPackageVersionsForPackageOwnedByUserCmd = &cobra.Command{
	Use:   "get-all-package-versions-for-package-owned-by-user",
	Short: "List package versions for a package owned by a user",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/users/{username}/packages/{package_type}/{package_name}/versions"
		packageTypeVal, _ := cmd.Flags().GetString("package-type")
		if packageTypeVal == "" {
			return fmt.Errorf("required flag --%s not set", "package-type")
		}
		path = strings.Replace(path, "{package_type}", packageTypeVal, 1)
		packageNameVal, _ := cmd.Flags().GetString("package-name")
		if packageNameVal == "" {
			return fmt.Errorf("required flag --%s not set", "package-name")
		}
		path = strings.Replace(path, "{package_name}", packageNameVal, 1)
		usernameVal, _ := cmd.Flags().GetString("username")
		if usernameVal == "" {
			return fmt.Errorf("required flag --%s not set", "username")
		}
		path = strings.Replace(path, "{username}", usernameVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	packagesGetAllPackageVersionsForPackageOwnedByUserCmd.Flags().String("package-type", "", "The type of supported package. Packages in GitHub's Gradle registry have the type `maven`. Docker images pushed to GitHub's Container registry (`ghcr.io`) have the type `container`. You can use the type `docker` to find images that were pushed to GitHub's Docker registry (`docker.pkg.github.com`), even if these have now been migrated to the Container registry.")
	_ = packagesGetAllPackageVersionsForPackageOwnedByUserCmd.RegisterFlagCompletionFunc("package-type", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"npm", "maven", "rubygems", "docker", "nuget", "container"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = packagesGetAllPackageVersionsForPackageOwnedByUserCmd.MarkFlagRequired("package-type")
	packagesGetAllPackageVersionsForPackageOwnedByUserCmd.Flags().String("package-name", "", "The name of the package.")
	_ = packagesGetAllPackageVersionsForPackageOwnedByUserCmd.MarkFlagRequired("package-name")
	packagesGetAllPackageVersionsForPackageOwnedByUserCmd.Flags().String("username", "", "The handle for the GitHub user account.")
	_ = packagesGetAllPackageVersionsForPackageOwnedByUserCmd.MarkFlagRequired("username")
}
