// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var privateRegistriesDeleteOrgPrivateRegistryCmd = &cobra.Command{
	Use:   "delete-org-private-registry",
	Short: "Delete a private registry for an organization",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/private-registries/{secret_name}"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		secretNameVal, _ := cmd.Flags().GetString("secret-name")
		if secretNameVal == "" {
			return fmt.Errorf("required flag --%s not set", "secret-name")
		}
		path = strings.Replace(path, "{secret_name}", secretNameVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	privateRegistriesDeleteOrgPrivateRegistryCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = privateRegistriesDeleteOrgPrivateRegistryCmd.MarkFlagRequired("org")
	privateRegistriesDeleteOrgPrivateRegistryCmd.Flags().String("secret-name", "", "The name of the secret.")
	_ = privateRegistriesDeleteOrgPrivateRegistryCmd.MarkFlagRequired("secret-name")
}
