// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var projectsListViewItemsForOrgCmd = &cobra.Command{
	Use:   "list-view-items-for-org",
	Short: "List items for an organization project view",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/projectsV2/{project_number}/views/{view_number}/items"
		projectNumberVal, _ := cmd.Flags().GetString("project-number")
		if projectNumberVal == "" {
			return fmt.Errorf("required flag --%s not set", "project-number")
		}
		path = strings.Replace(path, "{project_number}", projectNumberVal, 1)
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		viewNumberVal, _ := cmd.Flags().GetString("view-number")
		if viewNumberVal == "" {
			return fmt.Errorf("required flag --%s not set", "view-number")
		}
		path = strings.Replace(path, "{view_number}", viewNumberVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("fields"); v != "" {
			params["fields"] = v
		}
		if v, _ := cmd.Flags().GetString("before"); v != "" {
			params["before"] = v
		}
		if v, _ := cmd.Flags().GetString("after"); v != "" {
			params["after"] = v
		}
		if v, _ := cmd.Flags().GetString("per-page"); v != "" {
			params["per_page"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	projectsListViewItemsForOrgCmd.Flags().String("project-number", "", "The project's number.")
	_ = projectsListViewItemsForOrgCmd.MarkFlagRequired("project-number")
	projectsListViewItemsForOrgCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = projectsListViewItemsForOrgCmd.MarkFlagRequired("org")
	projectsListViewItemsForOrgCmd.Flags().String("view-number", "", "The number that identifies the project view.")
	_ = projectsListViewItemsForOrgCmd.MarkFlagRequired("view-number")
	projectsListViewItemsForOrgCmd.Flags().String("fields", "", "Limit results to specific fields, by their IDs. If not specified, the title field will be returned. Example: `fields[]=123&fields[]=456&fields[]=789` or `fields=123,456,789`")
	projectsListViewItemsForOrgCmd.Flags().String("before", "", "A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results before this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	projectsListViewItemsForOrgCmd.Flags().String("after", "", "A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results after this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	projectsListViewItemsForOrgCmd.Flags().String("per-page", "30", "The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
}
