// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var projectsCreateViewForOrgCmd = &cobra.Command{
	Use:   "create-view-for-org",
	Short: "Create a view for an organization-owned project",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/projectsV2/{project_number}/views"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		projectNumberVal, _ := cmd.Flags().GetString("project-number")
		if projectNumberVal == "" {
			return fmt.Errorf("required flag --%s not set", "project-number")
		}
		path = strings.Replace(path, "{project_number}", projectNumberVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "name", JSONPath: "name", Type: "string"},
			{FlagName: "layout", JSONPath: "layout", Type: "string"},
			{FlagName: "filter", JSONPath: "filter", Type: "string"},
			{FlagName: "visible-fields", JSONPath: "visible_fields", Type: "array"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	projectsCreateViewForOrgCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = projectsCreateViewForOrgCmd.MarkFlagRequired("org")
	projectsCreateViewForOrgCmd.Flags().String("project-number", "", "The project's number.")
	_ = projectsCreateViewForOrgCmd.MarkFlagRequired("project-number")
	projectsCreateViewForOrgCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	projectsCreateViewForOrgCmd.Flags().String("name", "", "The name of the view.")
	_ = projectsCreateViewForOrgCmd.MarkFlagRequired("name")
	projectsCreateViewForOrgCmd.Flags().String("layout", "", "The layout of the view.")
	_ = projectsCreateViewForOrgCmd.RegisterFlagCompletionFunc("layout", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"table", "board", "roadmap"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = projectsCreateViewForOrgCmd.MarkFlagRequired("layout")
	projectsCreateViewForOrgCmd.Flags().String("filter", "", "The filter query for the view. See [Filtering projects](https://docs.github.com/issues/planning-and-tracking-with-projects/customizing-views-in-your-project/filtering-projects) for more information.")
	projectsCreateViewForOrgCmd.Flags().String("visible-fields", "", "`visible_fields` is not applicable to `roadmap` layout views. For `table` and `board` layouts, this represents the field IDs that should be visible in the view. If not provided, the default visible fields will be used.")
}
