// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var projectsUpdateItemForOrgCmd = &cobra.Command{
	Use:   "update-item-for-org",
	Short: "Update project item for organization",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/projectsV2/{project_number}/items/{item_id}"
		projectNumberVal, _ := cmd.Flags().GetString("project-number")
		if projectNumberVal == "" {
			return fmt.Errorf("required flag --%s not set", "project-number")
		}
		path = strings.Replace(path, "{project_number}", projectNumberVal, 1)
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		itemIdVal, _ := cmd.Flags().GetString("item-id")
		if itemIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "item-id")
		}
		path = strings.Replace(path, "{item_id}", itemIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "fields", JSONPath: "fields", Type: "array"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PATCH", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	projectsUpdateItemForOrgCmd.Flags().String("project-number", "", "The project's number.")
	_ = projectsUpdateItemForOrgCmd.MarkFlagRequired("project-number")
	projectsUpdateItemForOrgCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = projectsUpdateItemForOrgCmd.MarkFlagRequired("org")
	projectsUpdateItemForOrgCmd.Flags().String("item-id", "", "The unique identifier of the project item.")
	_ = projectsUpdateItemForOrgCmd.MarkFlagRequired("item-id")
	projectsUpdateItemForOrgCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	projectsUpdateItemForOrgCmd.Flags().String("fields", "", "A list of field updates to apply.")
	_ = projectsUpdateItemForOrgCmd.MarkFlagRequired("fields")
}
