// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var projectsGetForOrgCmd = &cobra.Command{
	Use:   "get-for-org",
	Short: "Get project for organization",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/projectsV2/{project_number}"
		projectNumberVal, _ := cmd.Flags().GetString("project-number")
		if projectNumberVal == "" {
			return fmt.Errorf("required flag --%s not set", "project-number")
		}
		path = strings.Replace(path, "{project_number}", projectNumberVal, 1)
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	projectsGetForOrgCmd.Flags().String("project-number", "", "The project's number.")
	_ = projectsGetForOrgCmd.MarkFlagRequired("project-number")
	projectsGetForOrgCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = projectsGetForOrgCmd.MarkFlagRequired("org")
}
