// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var projectsCreateDraftItemForOrgCmd = &cobra.Command{
	Use:   "create-draft-item-for-org",
	Short: "Create draft item for organization owned project",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/projectsV2/{project_number}/drafts"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		projectNumberVal, _ := cmd.Flags().GetString("project-number")
		if projectNumberVal == "" {
			return fmt.Errorf("required flag --%s not set", "project-number")
		}
		path = strings.Replace(path, "{project_number}", projectNumberVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "title", JSONPath: "title", Type: "string"},
			{FlagName: "body", JSONPath: "body", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	projectsCreateDraftItemForOrgCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = projectsCreateDraftItemForOrgCmd.MarkFlagRequired("org")
	projectsCreateDraftItemForOrgCmd.Flags().String("project-number", "", "The project's number.")
	_ = projectsCreateDraftItemForOrgCmd.MarkFlagRequired("project-number")
	projectsCreateDraftItemForOrgCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	projectsCreateDraftItemForOrgCmd.Flags().String("title", "", "The title of the draft issue item to create in the project.")
	_ = projectsCreateDraftItemForOrgCmd.MarkFlagRequired("title")
	projectsCreateDraftItemForOrgCmd.Flags().String("body", "", "The body content of the draft issue item to create in the project.")
}
