// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var projectsListItemsForUserCmd = &cobra.Command{
	Use:   "list-items-for-user",
	Short: "List items for a user owned project",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/users/{username}/projectsV2/{project_number}/items"
		projectNumberVal, _ := cmd.Flags().GetString("project-number")
		if projectNumberVal == "" {
			return fmt.Errorf("required flag --%s not set", "project-number")
		}
		path = strings.Replace(path, "{project_number}", projectNumberVal, 1)
		usernameVal, _ := cmd.Flags().GetString("username")
		if usernameVal == "" {
			return fmt.Errorf("required flag --%s not set", "username")
		}
		path = strings.Replace(path, "{username}", usernameVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("before"); v != "" {
			params["before"] = v
		}
		if v, _ := cmd.Flags().GetString("after"); v != "" {
			params["after"] = v
		}
		if v, _ := cmd.Flags().GetString("per-page"); v != "" {
			params["per_page"] = v
		}
		if v, _ := cmd.Flags().GetString("q"); v != "" {
			params["q"] = v
		}
		if v, _ := cmd.Flags().GetString("fields"); v != "" {
			params["fields"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	projectsListItemsForUserCmd.Flags().String("project-number", "", "The project's number.")
	_ = projectsListItemsForUserCmd.MarkFlagRequired("project-number")
	projectsListItemsForUserCmd.Flags().String("username", "", "The handle for the GitHub user account.")
	_ = projectsListItemsForUserCmd.MarkFlagRequired("username")
	projectsListItemsForUserCmd.Flags().String("before", "", "A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results before this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	projectsListItemsForUserCmd.Flags().String("after", "", "A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results after this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	projectsListItemsForUserCmd.Flags().String("per-page", "30", "The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	projectsListItemsForUserCmd.Flags().String("q", "", "Search query to filter items, see [Filtering projects](https://docs.github.com/issues/planning-and-tracking-with-projects/customizing-views-in-your-project/filtering-projects) for more information.")
	projectsListItemsForUserCmd.Flags().String("fields", "", "Limit results to specific fields, by their IDs. If not specified, the title field will be returned. Example: `fields[]=123&fields[]=456&fields[]=789` or `fields=123,456,789`")
}
