// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var pullsGetReviewCommentCmd = &cobra.Command{
	Use:   "get-review-comment",
	Short: "Get a review comment for a pull request",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/pulls/comments/{comment_id}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		commentIdVal, _ := cmd.Flags().GetString("comment-id")
		if commentIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "comment-id")
		}
		path = strings.Replace(path, "{comment_id}", commentIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	pullsGetReviewCommentCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = pullsGetReviewCommentCmd.MarkFlagRequired("owner")
	pullsGetReviewCommentCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = pullsGetReviewCommentCmd.MarkFlagRequired("repo")
	pullsGetReviewCommentCmd.Flags().String("comment-id", "", "The unique identifier of the comment.")
	_ = pullsGetReviewCommentCmd.MarkFlagRequired("comment-id")
}
