// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var pullsUpdateReviewCommentCmd = &cobra.Command{
	Use:   "update-review-comment",
	Short: "Update a review comment for a pull request",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/pulls/comments/{comment_id}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		commentIdVal, _ := cmd.Flags().GetString("comment-id")
		if commentIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "comment-id")
		}
		path = strings.Replace(path, "{comment_id}", commentIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "body", JSONPath: "body", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PATCH", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	pullsUpdateReviewCommentCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = pullsUpdateReviewCommentCmd.MarkFlagRequired("owner")
	pullsUpdateReviewCommentCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = pullsUpdateReviewCommentCmd.MarkFlagRequired("repo")
	pullsUpdateReviewCommentCmd.Flags().String("comment-id", "", "The unique identifier of the comment.")
	_ = pullsUpdateReviewCommentCmd.MarkFlagRequired("comment-id")
	pullsUpdateReviewCommentCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	pullsUpdateReviewCommentCmd.Flags().String("body", "", "The text of the reply to the review comment.")
	_ = pullsUpdateReviewCommentCmd.MarkFlagRequired("body")
}
