// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var pullsUpdateBranchCmd = &cobra.Command{
	Use:   "update-branch",
	Short: "Update a pull request branch",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/pulls/{pull_number}/update-branch"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		pullNumberVal, _ := cmd.Flags().GetString("pull-number")
		if pullNumberVal == "" {
			return fmt.Errorf("required flag --%s not set", "pull-number")
		}
		path = strings.Replace(path, "{pull_number}", pullNumberVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "expected-head-sha", JSONPath: "expected_head_sha", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	pullsUpdateBranchCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = pullsUpdateBranchCmd.MarkFlagRequired("owner")
	pullsUpdateBranchCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = pullsUpdateBranchCmd.MarkFlagRequired("repo")
	pullsUpdateBranchCmd.Flags().String("pull-number", "", "The number that identifies the pull request.")
	_ = pullsUpdateBranchCmd.MarkFlagRequired("pull-number")
	pullsUpdateBranchCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	pullsUpdateBranchCmd.Flags().String("expected-head-sha", "", "The expected SHA of the pull request's HEAD ref. This is the most recent commit on the pull request's branch. If the expected SHA does not match the pull request's HEAD, you will receive a `422 Unprocessable Entity` status. You can use the \"[List commits](https://docs.github.com/rest/commits/commits#list-commits)\" endpoint to find the most recent commit SHA. Default: SHA of the pull request's current HEAD ref.")
}
