// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var pullsRequestReviewersCmd = &cobra.Command{
	Use:   "request-reviewers",
	Short: "Request reviewers for a pull request",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/pulls/{pull_number}/requested_reviewers"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		pullNumberVal, _ := cmd.Flags().GetString("pull-number")
		if pullNumberVal == "" {
			return fmt.Errorf("required flag --%s not set", "pull-number")
		}
		path = strings.Replace(path, "{pull_number}", pullNumberVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "reviewers", JSONPath: "reviewers", Type: "array"},
			{FlagName: "team-reviewers", JSONPath: "team_reviewers", Type: "array"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	pullsRequestReviewersCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = pullsRequestReviewersCmd.MarkFlagRequired("owner")
	pullsRequestReviewersCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = pullsRequestReviewersCmd.MarkFlagRequired("repo")
	pullsRequestReviewersCmd.Flags().String("pull-number", "", "The number that identifies the pull request.")
	_ = pullsRequestReviewersCmd.MarkFlagRequired("pull-number")
	pullsRequestReviewersCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	pullsRequestReviewersCmd.Flags().String("reviewers", "", "An array of user `login`s that will be requested.")
	pullsRequestReviewersCmd.Flags().String("team-reviewers", "", "An array of team `slug`s that will be requested.")
}
