// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var reactionsDeleteForReleaseCmd = &cobra.Command{
	Use:   "delete-for-release",
	Short: "Delete a release reaction",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/releases/{release_id}/reactions/{reaction_id}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		releaseIdVal, _ := cmd.Flags().GetString("release-id")
		if releaseIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "release-id")
		}
		path = strings.Replace(path, "{release_id}", releaseIdVal, 1)
		reactionIdVal, _ := cmd.Flags().GetString("reaction-id")
		if reactionIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "reaction-id")
		}
		path = strings.Replace(path, "{reaction_id}", reactionIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	reactionsDeleteForReleaseCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = reactionsDeleteForReleaseCmd.MarkFlagRequired("owner")
	reactionsDeleteForReleaseCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = reactionsDeleteForReleaseCmd.MarkFlagRequired("repo")
	reactionsDeleteForReleaseCmd.Flags().String("release-id", "", "The unique identifier of the release.")
	_ = reactionsDeleteForReleaseCmd.MarkFlagRequired("release-id")
	reactionsDeleteForReleaseCmd.Flags().String("reaction-id", "", "The unique identifier of the reaction.")
	_ = reactionsDeleteForReleaseCmd.MarkFlagRequired("reaction-id")
}
