// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var reposCreateDeployKeyCmd = &cobra.Command{
	Use:   "create-deploy-key",
	Short: "Create a deploy key",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/keys"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "title", JSONPath: "title", Type: "string"},
			{FlagName: "key", JSONPath: "key", Type: "string"},
			{FlagName: "read-only", JSONPath: "read_only", Type: "boolean"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	reposCreateDeployKeyCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = reposCreateDeployKeyCmd.MarkFlagRequired("owner")
	reposCreateDeployKeyCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = reposCreateDeployKeyCmd.MarkFlagRequired("repo")
	reposCreateDeployKeyCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	reposCreateDeployKeyCmd.Flags().String("title", "", "A name for the key.")
	reposCreateDeployKeyCmd.Flags().String("key", "", "The contents of the key.")
	_ = reposCreateDeployKeyCmd.MarkFlagRequired("key")
	reposCreateDeployKeyCmd.Flags().String("read-only", "", "If `true`, the key will only be able to read repository contents. Otherwise, the key will be able to read and write. Deploy keys with write access can perform the same actions as an organization member with admin access, or a collaborator on a personal repository. For more information, see \"[Repository permission levels for an organization](https://docs.github.com/articles/repository-permission-levels-for-an-organization/)\" and \"[Permission levels for a user account repository](https://docs.github.com/articles/permission-levels-for-a-user-account-repository/).\"")
}
