// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var reposGetReadmeCmd = &cobra.Command{
	Use:   "get-readme",
	Short: "Get a repository README",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/readme"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("ref"); v != "" {
			params["ref"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	reposGetReadmeCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = reposGetReadmeCmd.MarkFlagRequired("owner")
	reposGetReadmeCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = reposGetReadmeCmd.MarkFlagRequired("repo")
	reposGetReadmeCmd.Flags().String("ref", "", "The name of the commit/branch/tag. Default: the repository’s default branch.")
}
