// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var reposGetWebhookConfigForRepoCmd = &cobra.Command{
	Use:   "get-webhook-config-for-repo",
	Short: "Get a webhook configuration for a repository",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/hooks/{hook_id}/config"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		hookIdVal, _ := cmd.Flags().GetString("hook-id")
		if hookIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "hook-id")
		}
		path = strings.Replace(path, "{hook_id}", hookIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	reposGetWebhookConfigForRepoCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = reposGetWebhookConfigForRepoCmd.MarkFlagRequired("owner")
	reposGetWebhookConfigForRepoCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = reposGetWebhookConfigForRepoCmd.MarkFlagRequired("repo")
	reposGetWebhookConfigForRepoCmd.Flags().String("hook-id", "", "The unique identifier of the hook. You can find this value in the `X-GitHub-Hook-ID` header of a webhook delivery.")
	_ = reposGetWebhookConfigForRepoCmd.MarkFlagRequired("hook-id")
}
