// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var reposCreateReleaseCmd = &cobra.Command{
	Use:   "create-release",
	Short: "Create a release",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/releases"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "tag-name", JSONPath: "tag_name", Type: "string"},
			{FlagName: "target-commitish", JSONPath: "target_commitish", Type: "string"},
			{FlagName: "name", JSONPath: "name", Type: "string"},
			{FlagName: "body", JSONPath: "body", Type: "string"},
			{FlagName: "draft", JSONPath: "draft", Type: "boolean"},
			{FlagName: "prerelease", JSONPath: "prerelease", Type: "boolean"},
			{FlagName: "discussion-category-name", JSONPath: "discussion_category_name", Type: "string"},
			{FlagName: "generate-release-notes", JSONPath: "generate_release_notes", Type: "boolean"},
			{FlagName: "make-latest", JSONPath: "make_latest", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	reposCreateReleaseCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = reposCreateReleaseCmd.MarkFlagRequired("owner")
	reposCreateReleaseCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = reposCreateReleaseCmd.MarkFlagRequired("repo")
	reposCreateReleaseCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	reposCreateReleaseCmd.Flags().String("tag-name", "", "The name of the tag.")
	_ = reposCreateReleaseCmd.MarkFlagRequired("tag-name")
	reposCreateReleaseCmd.Flags().String("target-commitish", "", "Specifies the commitish value that determines where the Git tag is created from. Can be any branch or commit SHA. Unused if the Git tag already exists. Default: the repository's default branch.")
	reposCreateReleaseCmd.Flags().String("name", "", "The name of the release.")
	reposCreateReleaseCmd.Flags().String("body", "", "Text describing the contents of the tag.")
	reposCreateReleaseCmd.Flags().String("draft", "false", "`true` to create a draft (unpublished) release, `false` to create a published one.")
	reposCreateReleaseCmd.Flags().String("prerelease", "false", "`true` to identify the release as a prerelease. `false` to identify the release as a full release.")
	reposCreateReleaseCmd.Flags().String("discussion-category-name", "", "If specified, a discussion of the specified category is created and linked to the release. The value must be a category that already exists in the repository. For more information, see \"[Managing categories for discussions in your repository](https://docs.github.com/discussions/managing-discussions-for-your-community/managing-categories-for-discussions-in-your-repository).\"")
	reposCreateReleaseCmd.Flags().String("generate-release-notes", "false", "Whether to automatically generate the name and body for this release. If `name` is specified, the specified name will be used; otherwise, a name will be automatically generated. If `body` is specified, the body will be pre-pended to the automatically generated notes.")
	reposCreateReleaseCmd.Flags().String("make-latest", "true", "Specifies whether this release should be set as the latest release for the repository. Drafts and prereleases cannot be set as latest. Defaults to `true` for newly published releases. `legacy` specifies that the latest release should be determined based on the release creation date and higher semantic version.")
	_ = reposCreateReleaseCmd.RegisterFlagCompletionFunc("make-latest", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"true", "false", "legacy"}, cobra.ShellCompDirectiveNoFileComp
	})
}
