// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var reposGetRepoRulesetCmd = &cobra.Command{
	Use:   "get-repo-ruleset",
	Short: "Get a repository ruleset",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/rulesets/{ruleset_id}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		rulesetIdVal, _ := cmd.Flags().GetString("ruleset-id")
		if rulesetIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "ruleset-id")
		}
		path = strings.Replace(path, "{ruleset_id}", rulesetIdVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("includes-parents"); v != "" {
			params["includes_parents"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	reposGetRepoRulesetCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = reposGetRepoRulesetCmd.MarkFlagRequired("owner")
	reposGetRepoRulesetCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = reposGetRepoRulesetCmd.MarkFlagRequired("repo")
	reposGetRepoRulesetCmd.Flags().String("ruleset-id", "", "The ID of the ruleset.")
	_ = reposGetRepoRulesetCmd.MarkFlagRequired("ruleset-id")
	reposGetRepoRulesetCmd.Flags().String("includes-parents", "true", "Include rulesets configured at higher levels that apply to this repository")
}
