// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var reposDeleteInvitationCmd = &cobra.Command{
	Use:   "delete-invitation",
	Short: "Delete a repository invitation",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/invitations/{invitation_id}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		invitationIdVal, _ := cmd.Flags().GetString("invitation-id")
		if invitationIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "invitation-id")
		}
		path = strings.Replace(path, "{invitation_id}", invitationIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	reposDeleteInvitationCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = reposDeleteInvitationCmd.MarkFlagRequired("owner")
	reposDeleteInvitationCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = reposDeleteInvitationCmd.MarkFlagRequired("repo")
	reposDeleteInvitationCmd.Flags().String("invitation-id", "", "The unique identifier of the invitation.")
	_ = reposDeleteInvitationCmd.MarkFlagRequired("invitation-id")
}
