// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var reposUpdateDeploymentBranchPolicyCmd = &cobra.Command{
	Use:   "update-deployment-branch-policy",
	Short: "Update a deployment branch policy",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies/{branch_policy_id}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		environmentNameVal, _ := cmd.Flags().GetString("environment-name")
		if environmentNameVal == "" {
			return fmt.Errorf("required flag --%s not set", "environment-name")
		}
		path = strings.Replace(path, "{environment_name}", environmentNameVal, 1)
		branchPolicyIdVal, _ := cmd.Flags().GetString("branch-policy-id")
		if branchPolicyIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "branch-policy-id")
		}
		path = strings.Replace(path, "{branch_policy_id}", branchPolicyIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "name", JSONPath: "name", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	reposUpdateDeploymentBranchPolicyCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = reposUpdateDeploymentBranchPolicyCmd.MarkFlagRequired("owner")
	reposUpdateDeploymentBranchPolicyCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = reposUpdateDeploymentBranchPolicyCmd.MarkFlagRequired("repo")
	reposUpdateDeploymentBranchPolicyCmd.Flags().String("environment-name", "", "The name of the environment. The name must be URL encoded. For example, any slashes in the name must be replaced with `%2F`.")
	_ = reposUpdateDeploymentBranchPolicyCmd.MarkFlagRequired("environment-name")
	reposUpdateDeploymentBranchPolicyCmd.Flags().String("branch-policy-id", "", "The unique identifier of the branch policy.")
	_ = reposUpdateDeploymentBranchPolicyCmd.MarkFlagRequired("branch-policy-id")
	reposUpdateDeploymentBranchPolicyCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	reposUpdateDeploymentBranchPolicyCmd.Flags().String("name", "", "The name pattern that branches must match in order to deploy to the environment. Wildcard characters will not match `/`. For example, to match branches that begin with `release/` and contain an additional single slash, use `release/*/*`. For more information about pattern matching syntax, see the [Ruby File.fnmatch documentation](https://ruby-doc.org/core-2.5.1/File.html#method-c-fnmatch).")
	_ = reposUpdateDeploymentBranchPolicyCmd.MarkFlagRequired("name")
}
