// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var reposCreateDeploymentStatusCmd = &cobra.Command{
	Use:   "create-deployment-status",
	Short: "Create a deployment status",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/deployments/{deployment_id}/statuses"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		deploymentIdVal, _ := cmd.Flags().GetString("deployment-id")
		if deploymentIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "deployment-id")
		}
		path = strings.Replace(path, "{deployment_id}", deploymentIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "state", JSONPath: "state", Type: "string"},
			{FlagName: "target-url", JSONPath: "target_url", Type: "string"},
			{FlagName: "log-url", JSONPath: "log_url", Type: "string"},
			{FlagName: "description", JSONPath: "description", Type: "string"},
			{FlagName: "environment", JSONPath: "environment", Type: "string"},
			{FlagName: "environment-url", JSONPath: "environment_url", Type: "string"},
			{FlagName: "auto-inactive", JSONPath: "auto_inactive", Type: "boolean"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	reposCreateDeploymentStatusCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = reposCreateDeploymentStatusCmd.MarkFlagRequired("owner")
	reposCreateDeploymentStatusCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = reposCreateDeploymentStatusCmd.MarkFlagRequired("repo")
	reposCreateDeploymentStatusCmd.Flags().String("deployment-id", "", "deployment_id parameter")
	_ = reposCreateDeploymentStatusCmd.MarkFlagRequired("deployment-id")
	reposCreateDeploymentStatusCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	reposCreateDeploymentStatusCmd.Flags().String("state", "", "The state of the status. When you set a transient deployment to `inactive`, the deployment will be shown as `destroyed` in GitHub.")
	_ = reposCreateDeploymentStatusCmd.RegisterFlagCompletionFunc("state", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"error", "failure", "inactive", "in_progress", "queued", "pending", "success"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = reposCreateDeploymentStatusCmd.MarkFlagRequired("state")
	reposCreateDeploymentStatusCmd.Flags().String("target-url", "", "The target URL to associate with this status. This URL should contain output to keep the user updated while the task is running or serve as historical information for what happened in the deployment. > [!NOTE] > It's recommended to use the `log_url` parameter, which replaces `target_url`.")
	reposCreateDeploymentStatusCmd.Flags().String("log-url", "", "The full URL of the deployment's output. This parameter replaces `target_url`. We will continue to accept `target_url` to support legacy uses, but we recommend replacing `target_url` with `log_url`. Setting `log_url` will automatically set `target_url` to the same value. Default: `\"\"`")
	reposCreateDeploymentStatusCmd.Flags().String("description", "", "A short description of the status. The maximum description length is 140 characters.")
	reposCreateDeploymentStatusCmd.Flags().String("environment", "", "Name for the target deployment environment, which can be changed when setting a deploy status. For example, `production`, `staging`, or `qa`. If not defined, the environment of the previous status on the deployment will be used, if it exists. Otherwise, the environment of the deployment will be used.")
	reposCreateDeploymentStatusCmd.Flags().String("environment-url", "", "Sets the URL for accessing your environment. Default: `\"\"`")
	reposCreateDeploymentStatusCmd.Flags().String("auto-inactive", "", "Adds a new `inactive` status to all prior non-transient, non-production environment deployments with the same repository and `environment` name as the created status's deployment. An `inactive` status is only added to deployments that had a `success` state. Default: `true`")
}
