// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var reposCreateAutolinkCmd = &cobra.Command{
	Use:   "create-autolink",
	Short: "Create an autolink reference for a repository",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/autolinks"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "key-prefix", JSONPath: "key_prefix", Type: "string"},
			{FlagName: "url-template", JSONPath: "url_template", Type: "string"},
			{FlagName: "is-alphanumeric", JSONPath: "is_alphanumeric", Type: "boolean"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	reposCreateAutolinkCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = reposCreateAutolinkCmd.MarkFlagRequired("owner")
	reposCreateAutolinkCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = reposCreateAutolinkCmd.MarkFlagRequired("repo")
	reposCreateAutolinkCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	reposCreateAutolinkCmd.Flags().String("key-prefix", "", "This prefix appended by certain characters will generate a link any time it is found in an issue, pull request, or commit.")
	_ = reposCreateAutolinkCmd.MarkFlagRequired("key-prefix")
	reposCreateAutolinkCmd.Flags().String("url-template", "", "The URL must contain `<num>` for the reference number. `<num>` matches different characters depending on the value of `is_alphanumeric`.")
	_ = reposCreateAutolinkCmd.MarkFlagRequired("url-template")
	reposCreateAutolinkCmd.Flags().String("is-alphanumeric", "true", "Whether this autolink reference matches alphanumeric characters. If true, the `<num>` parameter of the `url_template` matches alphanumeric characters `A-Z` (case insensitive), `0-9`, and `-`. If false, this autolink reference only matches numeric characters.")
}
