// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var reposGetOrgRuleSuitesCmd = &cobra.Command{
	Use:   "get-org-rule-suites",
	Short: "List organization rule suites",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/rulesets/rule-suites"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("ref"); v != "" {
			params["ref"] = v
		}
		if v, _ := cmd.Flags().GetString("repository-name"); v != "" {
			params["repository_name"] = v
		}
		if v, _ := cmd.Flags().GetString("time-period"); v != "" {
			params["time_period"] = v
		}
		if v, _ := cmd.Flags().GetString("actor-name"); v != "" {
			params["actor_name"] = v
		}
		if v, _ := cmd.Flags().GetString("rule-suite-result"); v != "" {
			params["rule_suite_result"] = v
		}
		if v, _ := cmd.Flags().GetString("per-page"); v != "" {
			params["per_page"] = v
		}
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	reposGetOrgRuleSuitesCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = reposGetOrgRuleSuitesCmd.MarkFlagRequired("org")
	reposGetOrgRuleSuitesCmd.Flags().String("ref", "", "The name of the ref. Cannot contain wildcard characters. Optionally prefix with `refs/heads/` to limit to branches or `refs/tags/` to limit to tags. Omit the prefix to search across all refs. When specified, only rule evaluations triggered for this ref will be returned.")
	reposGetOrgRuleSuitesCmd.Flags().String("repository-name", "", "The name of the repository to filter on.")
	reposGetOrgRuleSuitesCmd.Flags().String("time-period", "day", "The time period to filter by. For example, `day` will filter for rule suites that occurred in the past 24 hours, and `week` will filter for rule suites that occurred in the past 7 days (168 hours).")
	_ = reposGetOrgRuleSuitesCmd.RegisterFlagCompletionFunc("time-period", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"hour", "day", "week", "month"}, cobra.ShellCompDirectiveNoFileComp
	})
	reposGetOrgRuleSuitesCmd.Flags().String("actor-name", "", "The handle for the GitHub user account to filter on. When specified, only rule evaluations triggered by this actor will be returned.")
	reposGetOrgRuleSuitesCmd.Flags().String("rule-suite-result", "all", "The rule suite results to filter on. When specified, only suites with this result will be returned.")
	_ = reposGetOrgRuleSuitesCmd.RegisterFlagCompletionFunc("rule-suite-result", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"pass", "fail", "bypass", "all"}, cobra.ShellCompDirectiveNoFileComp
	})
	reposGetOrgRuleSuitesCmd.Flags().String("per-page", "30", "The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	reposGetOrgRuleSuitesCmd.Flags().String("page", "1", "The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
}
