// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var reposCreateCommitCommentCmd = &cobra.Command{
	Use:   "create-commit-comment",
	Short: "Create a commit comment",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/commits/{commit_sha}/comments"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		commitShaVal, _ := cmd.Flags().GetString("commit-sha")
		if commitShaVal == "" {
			return fmt.Errorf("required flag --%s not set", "commit-sha")
		}
		path = strings.Replace(path, "{commit_sha}", commitShaVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "body", JSONPath: "body", Type: "string"},
			{FlagName: "path", JSONPath: "path", Type: "string"},
			{FlagName: "position", JSONPath: "position", Type: "integer"},
			{FlagName: "line", JSONPath: "line", Type: "integer"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	reposCreateCommitCommentCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = reposCreateCommitCommentCmd.MarkFlagRequired("owner")
	reposCreateCommitCommentCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = reposCreateCommitCommentCmd.MarkFlagRequired("repo")
	reposCreateCommitCommentCmd.Flags().String("commit-sha", "", "The SHA of the commit.")
	_ = reposCreateCommitCommentCmd.MarkFlagRequired("commit-sha")
	reposCreateCommitCommentCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	reposCreateCommitCommentCmd.Flags().String("body", "", "The contents of the comment.")
	_ = reposCreateCommitCommentCmd.MarkFlagRequired("body")
	reposCreateCommitCommentCmd.Flags().String("path", "", "Relative path of the file to comment on.")
	reposCreateCommitCommentCmd.Flags().String("position", "", "Line index in the diff to comment on.")
	reposCreateCommitCommentCmd.Flags().String("line", "", "**Closing down notice**. Use **position** parameter instead. Line number in the file to comment on.")
}
