// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var reposGetRepoRuleSuitesCmd = &cobra.Command{
	Use:   "get-repo-rule-suites",
	Short: "List repository rule suites",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/rulesets/rule-suites"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("ref"); v != "" {
			params["ref"] = v
		}
		if v, _ := cmd.Flags().GetString("time-period"); v != "" {
			params["time_period"] = v
		}
		if v, _ := cmd.Flags().GetString("actor-name"); v != "" {
			params["actor_name"] = v
		}
		if v, _ := cmd.Flags().GetString("rule-suite-result"); v != "" {
			params["rule_suite_result"] = v
		}
		if v, _ := cmd.Flags().GetString("per-page"); v != "" {
			params["per_page"] = v
		}
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	reposGetRepoRuleSuitesCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = reposGetRepoRuleSuitesCmd.MarkFlagRequired("owner")
	reposGetRepoRuleSuitesCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = reposGetRepoRuleSuitesCmd.MarkFlagRequired("repo")
	reposGetRepoRuleSuitesCmd.Flags().String("ref", "", "The name of the ref. Cannot contain wildcard characters. Optionally prefix with `refs/heads/` to limit to branches or `refs/tags/` to limit to tags. Omit the prefix to search across all refs. When specified, only rule evaluations triggered for this ref will be returned.")
	reposGetRepoRuleSuitesCmd.Flags().String("time-period", "day", "The time period to filter by. For example, `day` will filter for rule suites that occurred in the past 24 hours, and `week` will filter for rule suites that occurred in the past 7 days (168 hours).")
	_ = reposGetRepoRuleSuitesCmd.RegisterFlagCompletionFunc("time-period", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"hour", "day", "week", "month"}, cobra.ShellCompDirectiveNoFileComp
	})
	reposGetRepoRuleSuitesCmd.Flags().String("actor-name", "", "The handle for the GitHub user account to filter on. When specified, only rule evaluations triggered by this actor will be returned.")
	reposGetRepoRuleSuitesCmd.Flags().String("rule-suite-result", "all", "The rule suite results to filter on. When specified, only suites with this result will be returned.")
	_ = reposGetRepoRuleSuitesCmd.RegisterFlagCompletionFunc("rule-suite-result", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"pass", "fail", "bypass", "all"}, cobra.ShellCompDirectiveNoFileComp
	})
	reposGetRepoRuleSuitesCmd.Flags().String("per-page", "30", "The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	reposGetRepoRuleSuitesCmd.Flags().String("page", "1", "The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
}
