// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var reposGetCollaboratorPermissionLevelCmd = &cobra.Command{
	Use:   "get-collaborator-permission-level",
	Short: "Get repository permissions for a user",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/collaborators/{username}/permission"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		usernameVal, _ := cmd.Flags().GetString("username")
		if usernameVal == "" {
			return fmt.Errorf("required flag --%s not set", "username")
		}
		path = strings.Replace(path, "{username}", usernameVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	reposGetCollaboratorPermissionLevelCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = reposGetCollaboratorPermissionLevelCmd.MarkFlagRequired("owner")
	reposGetCollaboratorPermissionLevelCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = reposGetCollaboratorPermissionLevelCmd.MarkFlagRequired("repo")
	reposGetCollaboratorPermissionLevelCmd.Flags().String("username", "", "The handle for the GitHub user account.")
	_ = reposGetCollaboratorPermissionLevelCmd.MarkFlagRequired("username")
}
