// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var reposListCommitsCmd = &cobra.Command{
	Use:   "list-commits",
	Short: "List commits",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/commits"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("sha"); v != "" {
			params["sha"] = v
		}
		if v, _ := cmd.Flags().GetString("path"); v != "" {
			params["path"] = v
		}
		if v, _ := cmd.Flags().GetString("author"); v != "" {
			params["author"] = v
		}
		if v, _ := cmd.Flags().GetString("committer"); v != "" {
			params["committer"] = v
		}
		if v, _ := cmd.Flags().GetString("since"); v != "" {
			params["since"] = v
		}
		if v, _ := cmd.Flags().GetString("until"); v != "" {
			params["until"] = v
		}
		if v, _ := cmd.Flags().GetString("per-page"); v != "" {
			params["per_page"] = v
		}
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	reposListCommitsCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = reposListCommitsCmd.MarkFlagRequired("owner")
	reposListCommitsCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = reposListCommitsCmd.MarkFlagRequired("repo")
	reposListCommitsCmd.Flags().String("sha", "", "SHA or branch to start listing commits from. Default: the repository’s default branch (usually `main`).")
	reposListCommitsCmd.Flags().String("path", "", "Only commits containing this file path will be returned.")
	reposListCommitsCmd.Flags().String("author", "", "GitHub username or email address to use to filter by commit author.")
	reposListCommitsCmd.Flags().String("committer", "", "GitHub username or email address to use to filter by commit committer.")
	reposListCommitsCmd.Flags().String("since", "", "Only show results that were last updated after the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`. Due to limitations of Git, timestamps must be between 1970-01-01 and 2099-12-31 (inclusive) or unexpected results may be returned.")
	reposListCommitsCmd.Flags().String("until", "", "Only commits before this date will be returned. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`. Due to limitations of Git, timestamps must be between 1970-01-01 and 2099-12-31 (inclusive) or unexpected results may be returned.")
	reposListCommitsCmd.Flags().String("per-page", "30", "The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	reposListCommitsCmd.Flags().String("page", "1", "The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
}
