// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var reposUpdateBranchProtectionCmd = &cobra.Command{
	Use:   "update-branch-protection",
	Short: "Update branch protection",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/branches/{branch}/protection"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		branchVal, _ := cmd.Flags().GetString("branch")
		if branchVal == "" {
			return fmt.Errorf("required flag --%s not set", "branch")
		}
		path = strings.Replace(path, "{branch}", branchVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "required-status-checks.strict", JSONPath: "required_status_checks.strict", Type: "boolean"},
			{FlagName: "required-status-checks.contexts", JSONPath: "required_status_checks.contexts", Type: "array"},
			{FlagName: "required-status-checks.checks", JSONPath: "required_status_checks.checks", Type: "array"},
			{FlagName: "enforce-admins", JSONPath: "enforce_admins", Type: "boolean"},
			{FlagName: "required-pull-request-reviews.dismissal-restrictions", JSONPath: "required_pull_request_reviews.dismissal_restrictions", Type: "object"},
			{FlagName: "required-pull-request-reviews.dismiss-stale-reviews", JSONPath: "required_pull_request_reviews.dismiss_stale_reviews", Type: "boolean"},
			{FlagName: "required-pull-request-reviews.require-code-owner-reviews", JSONPath: "required_pull_request_reviews.require_code_owner_reviews", Type: "boolean"},
			{FlagName: "required-pull-request-reviews.required-approving-review-count", JSONPath: "required_pull_request_reviews.required_approving_review_count", Type: "integer"},
			{FlagName: "required-pull-request-reviews.require-last-push-approval", JSONPath: "required_pull_request_reviews.require_last_push_approval", Type: "boolean"},
			{FlagName: "required-pull-request-reviews.bypass-pull-request-allowances", JSONPath: "required_pull_request_reviews.bypass_pull_request_allowances", Type: "object"},
			{FlagName: "restrictions.users", JSONPath: "restrictions.users", Type: "array"},
			{FlagName: "restrictions.teams", JSONPath: "restrictions.teams", Type: "array"},
			{FlagName: "restrictions.apps", JSONPath: "restrictions.apps", Type: "array"},
			{FlagName: "required-linear-history", JSONPath: "required_linear_history", Type: "boolean"},
			{FlagName: "allow-force-pushes", JSONPath: "allow_force_pushes", Type: "boolean"},
			{FlagName: "allow-deletions", JSONPath: "allow_deletions", Type: "boolean"},
			{FlagName: "block-creations", JSONPath: "block_creations", Type: "boolean"},
			{FlagName: "required-conversation-resolution", JSONPath: "required_conversation_resolution", Type: "boolean"},
			{FlagName: "lock-branch", JSONPath: "lock_branch", Type: "boolean"},
			{FlagName: "allow-fork-syncing", JSONPath: "allow_fork_syncing", Type: "boolean"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	reposUpdateBranchProtectionCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = reposUpdateBranchProtectionCmd.MarkFlagRequired("owner")
	reposUpdateBranchProtectionCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = reposUpdateBranchProtectionCmd.MarkFlagRequired("repo")
	reposUpdateBranchProtectionCmd.Flags().String("branch", "", "The name of the branch. Cannot contain wildcard characters. To use wildcard characters in branch names, use [the GraphQL API](https://docs.github.com/graphql).")
	_ = reposUpdateBranchProtectionCmd.MarkFlagRequired("branch")
	reposUpdateBranchProtectionCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	reposUpdateBranchProtectionCmd.Flags().String("required-status-checks.strict", "", "Require branches to be up to date before merging.")
	_ = reposUpdateBranchProtectionCmd.MarkFlagRequired("required-status-checks.strict")
	reposUpdateBranchProtectionCmd.Flags().String("required-status-checks.contexts", "", "**Closing down notice**: The list of status checks to require in order to merge into this branch. If any of these checks have recently been set by a particular GitHub App, they will be required to come from that app in future for the branch to merge. Use `checks` instead of `contexts` for more fine-grained control.")
	_ = reposUpdateBranchProtectionCmd.MarkFlagRequired("required-status-checks.contexts")
	reposUpdateBranchProtectionCmd.Flags().String("required-status-checks.checks", "", "The list of status checks to require in order to merge into this branch.")
	reposUpdateBranchProtectionCmd.Flags().String("enforce-admins", "", "Enforce all configured restrictions for administrators. Set to `true` to enforce required status checks for repository administrators. Set to `null` to disable.")
	_ = reposUpdateBranchProtectionCmd.MarkFlagRequired("enforce-admins")
	reposUpdateBranchProtectionCmd.Flags().String("required-pull-request-reviews.dismissal-restrictions", "", "Specify which users, teams, and apps can dismiss pull request reviews. Pass an empty `dismissal_restrictions` object to disable. User and team `dismissal_restrictions` are only available for organization-owned repositories. Omit this parameter for personal repositories.")
	reposUpdateBranchProtectionCmd.Flags().String("required-pull-request-reviews.dismiss-stale-reviews", "", "Set to `true` if you want to automatically dismiss approving reviews when someone pushes a new commit.")
	reposUpdateBranchProtectionCmd.Flags().String("required-pull-request-reviews.require-code-owner-reviews", "", "Blocks merging pull requests until [code owners](https://docs.github.com/articles/about-code-owners/) review them.")
	reposUpdateBranchProtectionCmd.Flags().String("required-pull-request-reviews.required-approving-review-count", "", "Specify the number of reviewers required to approve pull requests. Use a number between 1 and 6 or 0 to not require reviewers.")
	reposUpdateBranchProtectionCmd.Flags().String("required-pull-request-reviews.require-last-push-approval", "false", "Whether the most recent push must be approved by someone other than the person who pushed it. Default: `false`.")
	reposUpdateBranchProtectionCmd.Flags().String("required-pull-request-reviews.bypass-pull-request-allowances", "", "Allow specific users, teams, or apps to bypass pull request requirements.")
	reposUpdateBranchProtectionCmd.Flags().String("restrictions.users", "", "The list of user `login`s with push access")
	_ = reposUpdateBranchProtectionCmd.MarkFlagRequired("restrictions.users")
	reposUpdateBranchProtectionCmd.Flags().String("restrictions.teams", "", "The list of team `slug`s with push access")
	_ = reposUpdateBranchProtectionCmd.MarkFlagRequired("restrictions.teams")
	reposUpdateBranchProtectionCmd.Flags().String("restrictions.apps", "", "The list of app `slug`s with push access")
	reposUpdateBranchProtectionCmd.Flags().String("required-linear-history", "", "Enforces a linear commit Git history, which prevents anyone from pushing merge commits to a branch. Set to `true` to enforce a linear commit history. Set to `false` to disable a linear commit Git history. Your repository must allow squash merging or rebase merging before you can enable a linear commit history. Default: `false`. For more information, see \"[Requiring a linear commit history](https://docs.github.com/github/administering-a-repository/requiring-a-linear-commit-history)\" in the GitHub Help documentation.")
	reposUpdateBranchProtectionCmd.Flags().String("allow-force-pushes", "", "Permits force pushes to the protected branch by anyone with write access to the repository. Set to `true` to allow force pushes. Set to `false` or `null` to block force pushes. Default: `false`. For more information, see \"[Enabling force pushes to a protected branch](https://docs.github.com/github/administering-a-repository/enabling-force-pushes-to-a-protected-branch)\" in the GitHub Help documentation.\"")
	reposUpdateBranchProtectionCmd.Flags().String("allow-deletions", "", "Allows deletion of the protected branch by anyone with write access to the repository. Set to `false` to prevent deletion of the protected branch. Default: `false`. For more information, see \"[Enabling force pushes to a protected branch](https://docs.github.com/github/administering-a-repository/enabling-force-pushes-to-a-protected-branch)\" in the GitHub Help documentation.")
	reposUpdateBranchProtectionCmd.Flags().String("block-creations", "", "If set to `true`, the `restrictions` branch protection settings which limits who can push will also block pushes which create new branches, unless the push is initiated by a user, team, or app which has the ability to push. Set to `true` to restrict new branch creation. Default: `false`.")
	reposUpdateBranchProtectionCmd.Flags().String("required-conversation-resolution", "", "Requires all conversations on code to be resolved before a pull request can be merged into a branch that matches this rule. Set to `false` to disable. Default: `false`.")
	reposUpdateBranchProtectionCmd.Flags().String("lock-branch", "false", "Whether to set the branch as read-only. If this is true, users will not be able to push to the branch. Default: `false`.")
	reposUpdateBranchProtectionCmd.Flags().String("allow-fork-syncing", "false", "Whether users can pull changes from upstream when the branch is locked. Set to `true` to allow fork syncing. Set to `false` to prevent fork syncing. Default: `false`.")
}
