// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var reposUpdateReleaseCmd = &cobra.Command{
	Use:   "update-release",
	Short: "Update a release",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/releases/{release_id}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		releaseIdVal, _ := cmd.Flags().GetString("release-id")
		if releaseIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "release-id")
		}
		path = strings.Replace(path, "{release_id}", releaseIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "tag-name", JSONPath: "tag_name", Type: "string"},
			{FlagName: "target-commitish", JSONPath: "target_commitish", Type: "string"},
			{FlagName: "name", JSONPath: "name", Type: "string"},
			{FlagName: "body", JSONPath: "body", Type: "string"},
			{FlagName: "draft", JSONPath: "draft", Type: "boolean"},
			{FlagName: "prerelease", JSONPath: "prerelease", Type: "boolean"},
			{FlagName: "make-latest", JSONPath: "make_latest", Type: "string"},
			{FlagName: "discussion-category-name", JSONPath: "discussion_category_name", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PATCH", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	reposUpdateReleaseCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = reposUpdateReleaseCmd.MarkFlagRequired("owner")
	reposUpdateReleaseCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = reposUpdateReleaseCmd.MarkFlagRequired("repo")
	reposUpdateReleaseCmd.Flags().String("release-id", "", "The unique identifier of the release.")
	_ = reposUpdateReleaseCmd.MarkFlagRequired("release-id")
	reposUpdateReleaseCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	reposUpdateReleaseCmd.Flags().String("tag-name", "", "The name of the tag.")
	reposUpdateReleaseCmd.Flags().String("target-commitish", "", "Specifies the commitish value that determines where the Git tag is created from. Can be any branch or commit SHA. Unused if the Git tag already exists. Default: the repository's default branch.")
	reposUpdateReleaseCmd.Flags().String("name", "", "The name of the release.")
	reposUpdateReleaseCmd.Flags().String("body", "", "Text describing the contents of the tag.")
	reposUpdateReleaseCmd.Flags().String("draft", "", "`true` makes the release a draft, and `false` publishes the release.")
	reposUpdateReleaseCmd.Flags().String("prerelease", "", "`true` to identify the release as a prerelease, `false` to identify the release as a full release.")
	reposUpdateReleaseCmd.Flags().String("make-latest", "true", "Specifies whether this release should be set as the latest release for the repository. Drafts and prereleases cannot be set as latest. Defaults to `true` for newly published releases. `legacy` specifies that the latest release should be determined based on the release creation date and higher semantic version.")
	_ = reposUpdateReleaseCmd.RegisterFlagCompletionFunc("make-latest", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"true", "false", "legacy"}, cobra.ShellCompDirectiveNoFileComp
	})
	reposUpdateReleaseCmd.Flags().String("discussion-category-name", "", "If specified, a discussion of the specified category is created and linked to the release. The value must be a category that already exists in the repository. If there is already a discussion linked to the release, this parameter is ignored. For more information, see \"[Managing categories for discussions in your repository](https://docs.github.com/discussions/managing-discussions-for-your-community/managing-categories-for-discussions-in-your-repository).\"")
}
