// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var reposGetRepoRulesetVersionCmd = &cobra.Command{
	Use:   "get-repo-ruleset-version",
	Short: "Get repository ruleset version",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/rulesets/{ruleset_id}/history/{version_id}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		rulesetIdVal, _ := cmd.Flags().GetString("ruleset-id")
		if rulesetIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "ruleset-id")
		}
		path = strings.Replace(path, "{ruleset_id}", rulesetIdVal, 1)
		versionIdVal, _ := cmd.Flags().GetString("version-id")
		if versionIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "version-id")
		}
		path = strings.Replace(path, "{version_id}", versionIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	reposGetRepoRulesetVersionCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = reposGetRepoRulesetVersionCmd.MarkFlagRequired("owner")
	reposGetRepoRulesetVersionCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = reposGetRepoRulesetVersionCmd.MarkFlagRequired("repo")
	reposGetRepoRulesetVersionCmd.Flags().String("ruleset-id", "", "The ID of the ruleset.")
	_ = reposGetRepoRulesetVersionCmd.MarkFlagRequired("ruleset-id")
	reposGetRepoRulesetVersionCmd.Flags().String("version-id", "", "The ID of the version")
	_ = reposGetRepoRulesetVersionCmd.MarkFlagRequired("version-id")
}
