// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var reposGetDeploymentStatusCmd = &cobra.Command{
	Use:   "get-deployment-status",
	Short: "Get a deployment status",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/deployments/{deployment_id}/statuses/{status_id}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		deploymentIdVal, _ := cmd.Flags().GetString("deployment-id")
		if deploymentIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "deployment-id")
		}
		path = strings.Replace(path, "{deployment_id}", deploymentIdVal, 1)
		statusIdVal, _ := cmd.Flags().GetString("status-id")
		if statusIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "status-id")
		}
		path = strings.Replace(path, "{status_id}", statusIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	reposGetDeploymentStatusCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = reposGetDeploymentStatusCmd.MarkFlagRequired("owner")
	reposGetDeploymentStatusCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = reposGetDeploymentStatusCmd.MarkFlagRequired("repo")
	reposGetDeploymentStatusCmd.Flags().String("deployment-id", "", "deployment_id parameter")
	_ = reposGetDeploymentStatusCmd.MarkFlagRequired("deployment-id")
	reposGetDeploymentStatusCmd.Flags().String("status-id", "", "")
	_ = reposGetDeploymentStatusCmd.MarkFlagRequired("status-id")
}
