// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var reposGetAutolinkCmd = &cobra.Command{
	Use:   "get-autolink",
	Short: "Get an autolink reference of a repository",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/autolinks/{autolink_id}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		autolinkIdVal, _ := cmd.Flags().GetString("autolink-id")
		if autolinkIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "autolink-id")
		}
		path = strings.Replace(path, "{autolink_id}", autolinkIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	reposGetAutolinkCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = reposGetAutolinkCmd.MarkFlagRequired("owner")
	reposGetAutolinkCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = reposGetAutolinkCmd.MarkFlagRequired("repo")
	reposGetAutolinkCmd.Flags().String("autolink-id", "", "The unique identifier of the autolink.")
	_ = reposGetAutolinkCmd.MarkFlagRequired("autolink-id")
}
