// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var reposCodeownersErrorsCmd = &cobra.Command{
	Use:   "codeowners-errors",
	Short: "List CODEOWNERS errors",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/codeowners/errors"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("ref"); v != "" {
			params["ref"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	reposCodeownersErrorsCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = reposCodeownersErrorsCmd.MarkFlagRequired("owner")
	reposCodeownersErrorsCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = reposCodeownersErrorsCmd.MarkFlagRequired("repo")
	reposCodeownersErrorsCmd.Flags().String("ref", "", "A branch, tag or commit name used to determine which version of the CODEOWNERS file to use. Default: the repository's default branch (e.g. `main`)")
}
