// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var reposGetCustomDeploymentProtectionRuleCmd = &cobra.Command{
	Use:   "get-custom-deployment-protection-rule",
	Short: "Get a custom deployment protection rule",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/environments/{environment_name}/deployment_protection_rules/{protection_rule_id}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		environmentNameVal, _ := cmd.Flags().GetString("environment-name")
		if environmentNameVal == "" {
			return fmt.Errorf("required flag --%s not set", "environment-name")
		}
		path = strings.Replace(path, "{environment_name}", environmentNameVal, 1)
		protectionRuleIdVal, _ := cmd.Flags().GetString("protection-rule-id")
		if protectionRuleIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "protection-rule-id")
		}
		path = strings.Replace(path, "{protection_rule_id}", protectionRuleIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	reposGetCustomDeploymentProtectionRuleCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = reposGetCustomDeploymentProtectionRuleCmd.MarkFlagRequired("owner")
	reposGetCustomDeploymentProtectionRuleCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = reposGetCustomDeploymentProtectionRuleCmd.MarkFlagRequired("repo")
	reposGetCustomDeploymentProtectionRuleCmd.Flags().String("environment-name", "", "The name of the environment. The name must be URL encoded. For example, any slashes in the name must be replaced with `%2F`.")
	_ = reposGetCustomDeploymentProtectionRuleCmd.MarkFlagRequired("environment-name")
	reposGetCustomDeploymentProtectionRuleCmd.Flags().String("protection-rule-id", "", "The unique identifier of the protection rule.")
	_ = reposGetCustomDeploymentProtectionRuleCmd.MarkFlagRequired("protection-rule-id")
}
