// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var searchIssuesAndPullRequestsCmd = &cobra.Command{
	Use:   "issues-and-pull-requests",
	Short: "Search issues and pull requests",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/search/issues"

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("q"); v != "" {
			params["q"] = v
		}
		if v, _ := cmd.Flags().GetString("sort"); v != "" {
			params["sort"] = v
		}
		if v, _ := cmd.Flags().GetString("order"); v != "" {
			params["order"] = v
		}
		if v, _ := cmd.Flags().GetString("per-page"); v != "" {
			params["per_page"] = v
		}
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		if v, _ := cmd.Flags().GetString("advanced-search"); v != "" {
			params["advanced_search"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	searchIssuesAndPullRequestsCmd.Flags().String("q", "", "The query contains one or more search keywords and qualifiers. Qualifiers allow you to limit your search to specific areas of GitHub. The REST API supports the same qualifiers as the web interface for GitHub. To learn more about the format of the query, see [Constructing a search query](https://docs.github.com/rest/search/search#constructing-a-search-query). See \"[Searching issues and pull requests](https://docs.github.com/search-github/searching-on-github/searching-issues-and-pull-requests)\" for a detailed list of qualifiers.")
	_ = searchIssuesAndPullRequestsCmd.MarkFlagRequired("q")
	searchIssuesAndPullRequestsCmd.Flags().String("sort", "", "Sorts the results of your query by the number of `comments`, `reactions`, `reactions-+1`, `reactions--1`, `reactions-smile`, `reactions-thinking_face`, `reactions-heart`, `reactions-tada`, or `interactions`. You can also sort results by how recently the items were `created` or `updated`, Default: [best match](https://docs.github.com/rest/search/search#ranking-search-results)")
	_ = searchIssuesAndPullRequestsCmd.RegisterFlagCompletionFunc("sort", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"comments", "reactions", "reactions-+1", "reactions--1", "reactions-smile", "reactions-thinking_face", "reactions-heart", "reactions-tada", "interactions", "created", "updated"}, cobra.ShellCompDirectiveNoFileComp
	})
	searchIssuesAndPullRequestsCmd.Flags().String("order", "desc", "Determines whether the first search result returned is the highest number of matches (`desc`) or lowest number of matches (`asc`). This parameter is ignored unless you provide `sort`.")
	_ = searchIssuesAndPullRequestsCmd.RegisterFlagCompletionFunc("order", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"desc", "asc"}, cobra.ShellCompDirectiveNoFileComp
	})
	searchIssuesAndPullRequestsCmd.Flags().String("per-page", "30", "The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	searchIssuesAndPullRequestsCmd.Flags().String("page", "1", "The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	searchIssuesAndPullRequestsCmd.Flags().String("advanced-search", "", "Set to `true` to use advanced search. Example: `http://api.github.com/search/issues?q={query}&advanced_search=true`")
}
