// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var secretScanningUpdateOrgPatternConfigsCmd = &cobra.Command{
	Use:   "update-org-pattern-configs",
	Short: "Update organization pattern configurations",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/secret-scanning/pattern-configurations"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "pattern-config-version", JSONPath: "pattern_config_version", Type: "string"},
			{FlagName: "provider-pattern-settings", JSONPath: "provider_pattern_settings", Type: "array"},
			{FlagName: "custom-pattern-settings", JSONPath: "custom_pattern_settings", Type: "array"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PATCH", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	secretScanningUpdateOrgPatternConfigsCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = secretScanningUpdateOrgPatternConfigsCmd.MarkFlagRequired("org")
	secretScanningUpdateOrgPatternConfigsCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	secretScanningUpdateOrgPatternConfigsCmd.Flags().String("pattern-config-version", "", "The version of the entity. This is used to confirm you're updating the current version of the entity and mitigate unintentionally overriding someone else's update.")
	secretScanningUpdateOrgPatternConfigsCmd.Flags().String("provider-pattern-settings", "", "Pattern settings for provider patterns.")
	secretScanningUpdateOrgPatternConfigsCmd.Flags().String("custom-pattern-settings", "", "Pattern settings for custom patterns.")
}
