// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var secretScanningGetAlertCmd = &cobra.Command{
	Use:   "get-alert",
	Short: "Get a secret scanning alert",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		alertNumberVal, _ := cmd.Flags().GetString("alert-number")
		if alertNumberVal == "" {
			return fmt.Errorf("required flag --%s not set", "alert-number")
		}
		path = strings.Replace(path, "{alert_number}", alertNumberVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("hide-secret"); v != "" {
			params["hide_secret"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	secretScanningGetAlertCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = secretScanningGetAlertCmd.MarkFlagRequired("owner")
	secretScanningGetAlertCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = secretScanningGetAlertCmd.MarkFlagRequired("repo")
	secretScanningGetAlertCmd.Flags().String("alert-number", "", "The number that identifies an alert. You can find this at the end of the URL for a code scanning alert within GitHub, and in the `number` field in the response from the `GET /repos/{owner}/{repo}/code-scanning/alerts` operation.")
	_ = secretScanningGetAlertCmd.MarkFlagRequired("alert-number")
	secretScanningGetAlertCmd.Flags().String("hide-secret", "false", "A boolean value representing whether or not to hide literal secrets in the results.")
}
