// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var securityAdvisoriesGetRepositoryAdvisoryCmd = &cobra.Command{
	Use:   "get-repository-advisory",
	Short: "Get a repository security advisory",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/repos/{owner}/{repo}/security-advisories/{ghsa_id}"
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)
		ghsaIdVal, _ := cmd.Flags().GetString("ghsa-id")
		if ghsaIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "ghsa-id")
		}
		path = strings.Replace(path, "{ghsa_id}", ghsaIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	securityAdvisoriesGetRepositoryAdvisoryCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = securityAdvisoriesGetRepositoryAdvisoryCmd.MarkFlagRequired("owner")
	securityAdvisoriesGetRepositoryAdvisoryCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = securityAdvisoriesGetRepositoryAdvisoryCmd.MarkFlagRequired("repo")
	securityAdvisoriesGetRepositoryAdvisoryCmd.Flags().String("ghsa-id", "", "The GHSA (GitHub Security Advisory) identifier of the advisory.")
	_ = securityAdvisoriesGetRepositoryAdvisoryCmd.MarkFlagRequired("ghsa-id")
}
