// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var teamsAddOrUpdateMembershipForUserLegacyCmd = &cobra.Command{
	Use:   "add-or-update-membership-for-user-legacy",
	Short: "Add or update team membership for a user (Legacy)",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/teams/{team_id}/memberships/{username}"
		teamIdVal, _ := cmd.Flags().GetString("team-id")
		if teamIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "team-id")
		}
		path = strings.Replace(path, "{team_id}", teamIdVal, 1)
		usernameVal, _ := cmd.Flags().GetString("username")
		if usernameVal == "" {
			return fmt.Errorf("required flag --%s not set", "username")
		}
		path = strings.Replace(path, "{username}", usernameVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "role", JSONPath: "role", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	teamsAddOrUpdateMembershipForUserLegacyCmd.Flags().String("team-id", "", "The unique identifier of the team.")
	_ = teamsAddOrUpdateMembershipForUserLegacyCmd.MarkFlagRequired("team-id")
	teamsAddOrUpdateMembershipForUserLegacyCmd.Flags().String("username", "", "The handle for the GitHub user account.")
	_ = teamsAddOrUpdateMembershipForUserLegacyCmd.MarkFlagRequired("username")
	teamsAddOrUpdateMembershipForUserLegacyCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	teamsAddOrUpdateMembershipForUserLegacyCmd.Flags().String("role", "member", "The role that this user should have in the team.")
	_ = teamsAddOrUpdateMembershipForUserLegacyCmd.RegisterFlagCompletionFunc("role", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"member", "maintainer"}, cobra.ShellCompDirectiveNoFileComp
	})
}
