// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var teamsCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a team",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/teams"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "name", JSONPath: "name", Type: "string"},
			{FlagName: "description", JSONPath: "description", Type: "string"},
			{FlagName: "maintainers", JSONPath: "maintainers", Type: "array"},
			{FlagName: "repo-names", JSONPath: "repo_names", Type: "array"},
			{FlagName: "privacy", JSONPath: "privacy", Type: "string"},
			{FlagName: "notification-setting", JSONPath: "notification_setting", Type: "string"},
			{FlagName: "permission", JSONPath: "permission", Type: "string"},
			{FlagName: "parent-team-id", JSONPath: "parent_team_id", Type: "integer"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	teamsCreateCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = teamsCreateCmd.MarkFlagRequired("org")
	teamsCreateCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	teamsCreateCmd.Flags().String("name", "", "The name of the team.")
	_ = teamsCreateCmd.MarkFlagRequired("name")
	teamsCreateCmd.Flags().String("description", "", "The description of the team.")
	teamsCreateCmd.Flags().String("maintainers", "", "List GitHub usernames for organization members who will become team maintainers.")
	teamsCreateCmd.Flags().String("repo-names", "", "The full name (e.g., \"organization-name/repository-name\") of repositories to add the team to.")
	teamsCreateCmd.Flags().String("privacy", "", "The level of privacy this team should have. The options are: **For a non-nested team:** * `secret` - only visible to organization owners and members of this team. * `closed` - visible to all members of this organization. Default: `secret` **For a parent or child team:** * `closed` - visible to all members of this organization. Default for child team: `closed`")
	_ = teamsCreateCmd.RegisterFlagCompletionFunc("privacy", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"secret", "closed"}, cobra.ShellCompDirectiveNoFileComp
	})
	teamsCreateCmd.Flags().String("notification-setting", "", "The notification setting the team has chosen. The options are: * `notifications_enabled` - team members receive notifications when the team is @mentioned. * `notifications_disabled` - no one receives notifications. Default: `notifications_enabled`")
	_ = teamsCreateCmd.RegisterFlagCompletionFunc("notification-setting", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"notifications_enabled", "notifications_disabled"}, cobra.ShellCompDirectiveNoFileComp
	})
	teamsCreateCmd.Flags().String("permission", "pull", "**Closing down notice**. The permission that new repositories will be added to the team with when none is specified.")
	_ = teamsCreateCmd.RegisterFlagCompletionFunc("permission", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"pull", "push"}, cobra.ShellCompDirectiveNoFileComp
	})
	teamsCreateCmd.Flags().String("parent-team-id", "", "The ID of a team to set as the parent team.")
}
