// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var teamsCheckPermissionsForRepoInOrgCmd = &cobra.Command{
	Use:   "check-permissions-for-repo-in-org",
	Short: "Check team permissions for a repository",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		teamSlugVal, _ := cmd.Flags().GetString("team-slug")
		if teamSlugVal == "" {
			return fmt.Errorf("required flag --%s not set", "team-slug")
		}
		path = strings.Replace(path, "{team_slug}", teamSlugVal, 1)
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	teamsCheckPermissionsForRepoInOrgCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = teamsCheckPermissionsForRepoInOrgCmd.MarkFlagRequired("org")
	teamsCheckPermissionsForRepoInOrgCmd.Flags().String("team-slug", "", "The slug of the team name.")
	_ = teamsCheckPermissionsForRepoInOrgCmd.MarkFlagRequired("team-slug")
	teamsCheckPermissionsForRepoInOrgCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = teamsCheckPermissionsForRepoInOrgCmd.MarkFlagRequired("owner")
	teamsCheckPermissionsForRepoInOrgCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = teamsCheckPermissionsForRepoInOrgCmd.MarkFlagRequired("repo")
}
