// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var teamsGetMembershipForUserLegacyCmd = &cobra.Command{
	Use:   "get-membership-for-user-legacy",
	Short: "Get team membership for a user (Legacy)",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/teams/{team_id}/memberships/{username}"
		teamIdVal, _ := cmd.Flags().GetString("team-id")
		if teamIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "team-id")
		}
		path = strings.Replace(path, "{team_id}", teamIdVal, 1)
		usernameVal, _ := cmd.Flags().GetString("username")
		if usernameVal == "" {
			return fmt.Errorf("required flag --%s not set", "username")
		}
		path = strings.Replace(path, "{username}", usernameVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	teamsGetMembershipForUserLegacyCmd.Flags().String("team-id", "", "The unique identifier of the team.")
	_ = teamsGetMembershipForUserLegacyCmd.MarkFlagRequired("team-id")
	teamsGetMembershipForUserLegacyCmd.Flags().String("username", "", "The handle for the GitHub user account.")
	_ = teamsGetMembershipForUserLegacyCmd.MarkFlagRequired("username")
}
