// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var teamsAddOrUpdateMembershipForUserInOrgCmd = &cobra.Command{
	Use:   "add-or-update-membership-for-user-in-org",
	Short: "Add or update team membership for a user",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/orgs/{org}/teams/{team_slug}/memberships/{username}"
		orgVal, _ := cmd.Flags().GetString("org")
		if orgVal == "" {
			return fmt.Errorf("required flag --%s not set", "org")
		}
		path = strings.Replace(path, "{org}", orgVal, 1)
		teamSlugVal, _ := cmd.Flags().GetString("team-slug")
		if teamSlugVal == "" {
			return fmt.Errorf("required flag --%s not set", "team-slug")
		}
		path = strings.Replace(path, "{team_slug}", teamSlugVal, 1)
		usernameVal, _ := cmd.Flags().GetString("username")
		if usernameVal == "" {
			return fmt.Errorf("required flag --%s not set", "username")
		}
		path = strings.Replace(path, "{username}", usernameVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "role", JSONPath: "role", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	teamsAddOrUpdateMembershipForUserInOrgCmd.Flags().String("org", "", "The organization name. The name is not case sensitive.")
	_ = teamsAddOrUpdateMembershipForUserInOrgCmd.MarkFlagRequired("org")
	teamsAddOrUpdateMembershipForUserInOrgCmd.Flags().String("team-slug", "", "The slug of the team name.")
	_ = teamsAddOrUpdateMembershipForUserInOrgCmd.MarkFlagRequired("team-slug")
	teamsAddOrUpdateMembershipForUserInOrgCmd.Flags().String("username", "", "The handle for the GitHub user account.")
	_ = teamsAddOrUpdateMembershipForUserInOrgCmd.MarkFlagRequired("username")
	teamsAddOrUpdateMembershipForUserInOrgCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	teamsAddOrUpdateMembershipForUserInOrgCmd.Flags().String("role", "member", "The role that this user should have in the team.")
	_ = teamsAddOrUpdateMembershipForUserInOrgCmd.RegisterFlagCompletionFunc("role", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"member", "maintainer"}, cobra.ShellCompDirectiveNoFileComp
	})
}
