// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var teamsListChildLegacyCmd = &cobra.Command{
	Use:   "list-child-legacy",
	Short: "List child teams (Legacy)",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/teams/{team_id}/teams"
		teamIdVal, _ := cmd.Flags().GetString("team-id")
		if teamIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "team-id")
		}
		path = strings.Replace(path, "{team_id}", teamIdVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("per-page"); v != "" {
			params["per_page"] = v
		}
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	teamsListChildLegacyCmd.Flags().String("team-id", "", "The unique identifier of the team.")
	_ = teamsListChildLegacyCmd.MarkFlagRequired("team-id")
	teamsListChildLegacyCmd.Flags().String("per-page", "30", "The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
	teamsListChildLegacyCmd.Flags().String("page", "1", "The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
}
