// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var teamsAddOrUpdateRepoPermissionsLegacyCmd = &cobra.Command{
	Use:   "add-or-update-repo-permissions-legacy",
	Short: "Add or update team repository permissions (Legacy)",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/teams/{team_id}/repos/{owner}/{repo}"
		teamIdVal, _ := cmd.Flags().GetString("team-id")
		if teamIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "team-id")
		}
		path = strings.Replace(path, "{team_id}", teamIdVal, 1)
		ownerVal, _ := cmd.Flags().GetString("owner")
		if ownerVal == "" {
			return fmt.Errorf("required flag --%s not set", "owner")
		}
		path = strings.Replace(path, "{owner}", ownerVal, 1)
		repoVal, _ := cmd.Flags().GetString("repo")
		if repoVal == "" {
			return fmt.Errorf("required flag --%s not set", "repo")
		}
		path = strings.Replace(path, "{repo}", repoVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "permission", JSONPath: "permission", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	teamsAddOrUpdateRepoPermissionsLegacyCmd.Flags().String("team-id", "", "The unique identifier of the team.")
	_ = teamsAddOrUpdateRepoPermissionsLegacyCmd.MarkFlagRequired("team-id")
	teamsAddOrUpdateRepoPermissionsLegacyCmd.Flags().String("owner", "", "The account owner of the repository. The name is not case sensitive.")
	_ = teamsAddOrUpdateRepoPermissionsLegacyCmd.MarkFlagRequired("owner")
	teamsAddOrUpdateRepoPermissionsLegacyCmd.Flags().String("repo", "", "The name of the repository without the `.git` extension. The name is not case sensitive.")
	_ = teamsAddOrUpdateRepoPermissionsLegacyCmd.MarkFlagRequired("repo")
	teamsAddOrUpdateRepoPermissionsLegacyCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	teamsAddOrUpdateRepoPermissionsLegacyCmd.Flags().String("permission", "", "The permission to grant the team on this repository. If no permission is specified, the team's `permission` attribute will be used to determine what permission to grant the team on this repository.")
	_ = teamsAddOrUpdateRepoPermissionsLegacyCmd.RegisterFlagCompletionFunc("permission", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"pull", "push", "admin"}, cobra.ShellCompDirectiveNoFileComp
	})
}
