// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var teamsDeleteLegacyCmd = &cobra.Command{
	Use:   "delete-legacy",
	Short: "Delete a team (Legacy)",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/teams/{team_id}"
		teamIdVal, _ := cmd.Flags().GetString("team-id")
		if teamIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "team-id")
		}
		path = strings.Replace(path, "{team_id}", teamIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	teamsDeleteLegacyCmd.Flags().String("team-id", "", "The unique identifier of the team.")
	_ = teamsDeleteLegacyCmd.MarkFlagRequired("team-id")
}
