// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var usersCheckFollowingForUserCmd = &cobra.Command{
	Use:   "check-following-for-user",
	Short: "Check if a user follows another user",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/users/{username}/following/{target_user}"
		usernameVal, _ := cmd.Flags().GetString("username")
		if usernameVal == "" {
			return fmt.Errorf("required flag --%s not set", "username")
		}
		path = strings.Replace(path, "{username}", usernameVal, 1)
		targetUserVal, _ := cmd.Flags().GetString("target-user")
		if targetUserVal == "" {
			return fmt.Errorf("required flag --%s not set", "target-user")
		}
		path = strings.Replace(path, "{target_user}", targetUserVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	usersCheckFollowingForUserCmd.Flags().String("username", "", "The handle for the GitHub user account.")
	_ = usersCheckFollowingForUserCmd.MarkFlagRequired("username")
	usersCheckFollowingForUserCmd.Flags().String("target-user", "", "")
	_ = usersCheckFollowingForUserCmd.MarkFlagRequired("target-user")
}
