// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var usersCheckBlockedCmd = &cobra.Command{
	Use:   "check-blocked",
	Short: "Check if a user is blocked by the authenticated user",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/user/blocks/{username}"
		usernameVal, _ := cmd.Flags().GetString("username")
		if usernameVal == "" {
			return fmt.Errorf("required flag --%s not set", "username")
		}
		path = strings.Replace(path, "{username}", usernameVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	usersCheckBlockedCmd.Flags().String("username", "", "The handle for the GitHub user account.")
	_ = usersCheckBlockedCmd.MarkFlagRequired("username")
}
