// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var usersDeleteAttestationsBySubjectDigestCmd = &cobra.Command{
	Use:   "delete-attestations-by-subject-digest",
	Short: "Delete attestations by subject digest",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/users/{username}/attestations/digest/{subject_digest}"
		usernameVal, _ := cmd.Flags().GetString("username")
		if usernameVal == "" {
			return fmt.Errorf("required flag --%s not set", "username")
		}
		path = strings.Replace(path, "{username}", usernameVal, 1)
		subjectDigestVal, _ := cmd.Flags().GetString("subject-digest")
		if subjectDigestVal == "" {
			return fmt.Errorf("required flag --%s not set", "subject-digest")
		}
		path = strings.Replace(path, "{subject_digest}", subjectDigestVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	usersDeleteAttestationsBySubjectDigestCmd.Flags().String("username", "", "The handle for the GitHub user account.")
	_ = usersDeleteAttestationsBySubjectDigestCmd.MarkFlagRequired("username")
	usersDeleteAttestationsBySubjectDigestCmd.Flags().String("subject-digest", "", "Subject Digest")
	_ = usersDeleteAttestationsBySubjectDigestCmd.MarkFlagRequired("subject-digest")
}
