// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var usersUpdateAuthenticatedCmd = &cobra.Command{
	Use:   "update-authenticated",
	Short: "Update the authenticated user",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/user"

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "name", JSONPath: "name", Type: "string"},
			{FlagName: "email", JSONPath: "email", Type: "string"},
			{FlagName: "blog", JSONPath: "blog", Type: "string"},
			{FlagName: "twitter-username", JSONPath: "twitter_username", Type: "string"},
			{FlagName: "company", JSONPath: "company", Type: "string"},
			{FlagName: "location", JSONPath: "location", Type: "string"},
			{FlagName: "hireable", JSONPath: "hireable", Type: "boolean"},
			{FlagName: "bio", JSONPath: "bio", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PATCH", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	usersUpdateAuthenticatedCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	usersUpdateAuthenticatedCmd.Flags().String("name", "", "The new name of the user.")
	usersUpdateAuthenticatedCmd.Flags().String("email", "", "The publicly visible email address of the user.")
	usersUpdateAuthenticatedCmd.Flags().String("blog", "", "The new blog URL of the user.")
	usersUpdateAuthenticatedCmd.Flags().String("twitter-username", "", "The new Twitter username of the user.")
	usersUpdateAuthenticatedCmd.Flags().String("company", "", "The new company of the user.")
	usersUpdateAuthenticatedCmd.Flags().String("location", "", "The new location of the user.")
	usersUpdateAuthenticatedCmd.Flags().String("hireable", "", "The new hiring availability of the user.")
	usersUpdateAuthenticatedCmd.Flags().String("bio", "", "The new short biography of the user.")
}
