// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var usersGetSshSigningKeyForAuthenticatedUserCmd = &cobra.Command{
	Use:   "get-ssh-signing-key-for-authenticated-user",
	Short: "Get an SSH signing key for the authenticated user",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/user/ssh_signing_keys/{ssh_signing_key_id}"
		sshSigningKeyIdVal, _ := cmd.Flags().GetString("ssh-signing-key-id")
		if sshSigningKeyIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "ssh-signing-key-id")
		}
		path = strings.Replace(path, "{ssh_signing_key_id}", sshSigningKeyIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	usersGetSshSigningKeyForAuthenticatedUserCmd.Flags().String("ssh-signing-key-id", "", "The unique identifier of the SSH signing key.")
	_ = usersGetSshSigningKeyForAuthenticatedUserCmd.MarkFlagRequired("ssh-signing-key-id")
}
