// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/github/github-cli/runtime"
	"github.com/spf13/cobra"
)

var usersGetGpgKeyForAuthenticatedUserCmd = &cobra.Command{
	Use:   "get-gpg-key-for-authenticated-user",
	Short: "Get a GPG key for the authenticated user",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/user/gpg_keys/{gpg_key_id}"
		gpgKeyIdVal, _ := cmd.Flags().GetString("gpg-key-id")
		if gpgKeyIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "gpg-key-id")
		}
		path = strings.Replace(path, "{gpg_key_id}", gpgKeyIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	usersGetGpgKeyForAuthenticatedUserCmd.Flags().String("gpg-key-id", "", "The unique identifier of the GPG key.")
	_ = usersGetGpgKeyForAuthenticatedUserCmd.MarkFlagRequired("gpg-key-id")
}
