// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"

	"github.com/petstore/petstore-cli/runtime"
	"github.com/spf13/cobra"
)

var petUpdateCmd = &cobra.Command{
	Use:   "update",
	Short: "Update an existing pet.",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/pet"

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "id", JSONPath: "id", Type: "integer"},
			{FlagName: "name", JSONPath: "name", Type: "string"},
			{FlagName: "category.id", JSONPath: "category.id", Type: "integer"},
			{FlagName: "category.name", JSONPath: "category.name", Type: "string"},
			{FlagName: "photo-urls", JSONPath: "photoUrls", Type: "array"},
			{FlagName: "tags", JSONPath: "tags", Type: "array"},
			{FlagName: "status", JSONPath: "status", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	petUpdateCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	petUpdateCmd.Flags().String("id", "", "")
	petUpdateCmd.Flags().String("name", "", "")
	_ = petUpdateCmd.MarkFlagRequired("name")
	petUpdateCmd.Flags().String("category.id", "", "")
	petUpdateCmd.Flags().String("category.name", "", "")
	petUpdateCmd.Flags().String("photo-urls", "", "")
	_ = petUpdateCmd.MarkFlagRequired("photo-urls")
	petUpdateCmd.Flags().String("tags", "", "")
	petUpdateCmd.Flags().String("status", "", "pet status in the store")
	_ = petUpdateCmd.RegisterFlagCompletionFunc("status", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"available", "pending", "sold"}, cobra.ShellCompDirectiveNoFileComp
	})
}
