// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"github.com/petstore/petstore-cli/runtime"
	"github.com/spf13/cobra"
)

var petFindPetsByTagsCmd = &cobra.Command{
	Use:   "find-pets-by-tags",
	Short: "Finds Pets by tags.",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/pet/findByTags"

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("tags"); v != "" {
			params["tags"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	petFindPetsByTagsCmd.Flags().String("tags", "", "Tags to filter by")
	_ = petFindPetsByTagsCmd.MarkFlagRequired("tags")
}
