// Code generated by onlycli; DO NOT EDIT.

package commands

func init() {
	rootCmd.AddCommand(configCmd)
	rootCmd.AddCommand(authCmd)
	rootCmd.AddCommand(petCmd)
	petCmd.AddCommand(petAddCmd)
	petCmd.AddCommand(petDeleteCmd)
	petCmd.AddCommand(petFindPetsByStatusCmd)
	petCmd.AddCommand(petFindPetsByTagsCmd)
	petCmd.AddCommand(petGetPetByIdCmd)
	petCmd.AddCommand(petUpdateCmd)
	petCmd.AddCommand(petUpdatePetWithFormCmd)
	petCmd.AddCommand(petUploadFileCmd)
	rootCmd.AddCommand(storeCmd)
	storeCmd.AddCommand(storeDeleteOrderCmd)
	storeCmd.AddCommand(storeGetInventoryCmd)
	storeCmd.AddCommand(storeGetOrderByIdCmd)
	storeCmd.AddCommand(storePlaceOrderCmd)
	rootCmd.AddCommand(userCmd)
	userCmd.AddCommand(userCreateCmd)
	userCmd.AddCommand(userCreateUsersWithListInputCmd)
	userCmd.AddCommand(userDeleteCmd)
	userCmd.AddCommand(userGetUserByNameCmd)
	userCmd.AddCommand(userLoginCmd)
	userCmd.AddCommand(userLogoutCmd)
	userCmd.AddCommand(userUpdateCmd)
}
