// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"

	"github.com/petstore/petstore-cli/runtime"
	"github.com/spf13/cobra"
)

var storePlaceOrderCmd = &cobra.Command{
	Use:   "place-order",
	Short: "Place an order for a pet.",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/store/order"

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "id", JSONPath: "id", Type: "integer"},
			{FlagName: "pet-id", JSONPath: "petId", Type: "integer"},
			{FlagName: "quantity", JSONPath: "quantity", Type: "integer"},
			{FlagName: "ship-date", JSONPath: "shipDate", Type: "string"},
			{FlagName: "status", JSONPath: "status", Type: "string"},
			{FlagName: "complete", JSONPath: "complete", Type: "boolean"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	storePlaceOrderCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	storePlaceOrderCmd.Flags().String("id", "", "")
	storePlaceOrderCmd.Flags().String("pet-id", "", "")
	storePlaceOrderCmd.Flags().String("quantity", "", "")
	storePlaceOrderCmd.Flags().String("ship-date", "", "")
	storePlaceOrderCmd.Flags().String("status", "", "Order Status")
	_ = storePlaceOrderCmd.RegisterFlagCompletionFunc("status", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"placed", "approved", "delivered"}, cobra.ShellCompDirectiveNoFileComp
	})
	storePlaceOrderCmd.Flags().String("complete", "", "")
}
