// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"github.com/petstore/petstore-cli/runtime"
	"github.com/spf13/cobra"
)

var userLogoutCmd = &cobra.Command{
	Use:   "logout",
	Short: "Logs out current logged in user session.",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/user/logout"

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
}
