// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/petstore/petstore-cli/runtime"
	"github.com/spf13/cobra"
)

var userGetUserByNameCmd = &cobra.Command{
	Use:   "get-user-by-name",
	Short: "Get user by user name.",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/user/{username}"
		usernameVal, _ := cmd.Flags().GetString("username")
		if usernameVal == "" {
			return fmt.Errorf("required flag --%s not set", "username")
		}
		path = strings.Replace(path, "{username}", usernameVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	userGetUserByNameCmd.Flags().String("username", "", "The name that needs to be fetched. Use user1 for testing")
	_ = userGetUserByNameCmd.MarkFlagRequired("username")
}
