// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"

	"github.com/petstore/petstore-cli/runtime"
	"github.com/spf13/cobra"
)

var userCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Create user.",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/user"

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "id", JSONPath: "id", Type: "integer"},
			{FlagName: "username", JSONPath: "username", Type: "string"},
			{FlagName: "first-name", JSONPath: "firstName", Type: "string"},
			{FlagName: "last-name", JSONPath: "lastName", Type: "string"},
			{FlagName: "email", JSONPath: "email", Type: "string"},
			{FlagName: "password", JSONPath: "password", Type: "string"},
			{FlagName: "phone", JSONPath: "phone", Type: "string"},
			{FlagName: "user-status", JSONPath: "userStatus", Type: "integer"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	userCreateCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	userCreateCmd.Flags().String("id", "", "")
	userCreateCmd.Flags().String("username", "", "")
	userCreateCmd.Flags().String("first-name", "", "")
	userCreateCmd.Flags().String("last-name", "", "")
	userCreateCmd.Flags().String("email", "", "")
	userCreateCmd.Flags().String("password", "", "")
	userCreateCmd.Flags().String("phone", "", "")
	userCreateCmd.Flags().String("user-status", "", "User Status")
}
