title: OnlyCLI
description: "Turn any OpenAPI spec into a native CLI. 35x fewer tokens than MCP. Zero runtime. Zero bloat."
url: "https://onlycli.github.io"
baseurl: "/OnlyCLI"
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/
collections: null
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "page"
twitter:
  card: summary_large_image
social:
  name: OnlyCLI
  links:
    - https://github.com/onlycli/onlycli
author: OnlyCLI Team
google_analytics: G-FHB5NHHZDB
